huggingface:
  username: "prospaprospa"
  model_repo: "prospaprospa/Afrique-llama-8B"
  dataset_repo: "prospaprospa/africa-giants-dataset"
  space_repo: "prospaprospa/africa-giants-api"
  private: true
  token_env_var: "HF_TOKEN"
