#!/usr/bin/env python3
"""batch_008 part 1 — FIX 1 (30 GN487A penalty) + FIX 2 (20 GN487A scope) = 50 pairs."""
import json, os

SRC_GN487A = "https://tanzlii.org/akn/tz/act/gn/2025/487a/eng@2025-07-28"
SRC_NAME_GN = "TanzLII - GN 487A Business Licensing (Prohibition of Business Activities for Non-Citizens) Order 2025"
DATE = "20260612"

pairs = [

# ══════════════════════════════════════════════════════════
# FIX 1 — GN 487A PENALTY DISAMBIGUATION (30 pairs)
# Non-citizen: ≥TZS 10M AND ≤6mo AND visa revocation
# Tanzanian facilitator: ≤TZS 5M OR ≤3mo (no visa)
# ══════════════════════════════════════════════════════════

{"id":f"b008_gn487a_pen_001_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Adhabu ya mgeni (non-citizen) anayekutwa akifanya biashara iliyokatazwa chini ya GN 487A ni nini hasa?",
"answer_sw":"Adhabu kamili ya mgeni ni adhabu TATU PAMOJA: (1) faini ya ISIYOPUNGUA TZS 10,000,000 (si zaidi ya — ni kiwango cha CHINI); (2) kifungo kisichozidi miezi 6; NA (3) kufutwa kwa visa na kibali chake cha ukaazi. Maneno muhimu: 'isiyopungua' inamaanisha TZS 10M ni adhabu ya CHINI KABISA — korti inaweza kutoza zaidi. Adhabu hizi tatu zinakwenda pamoja — si moja au nyingine.",
"question_en":"What exactly is the penalty for a non-citizen caught conducting a prohibited business under GN 487A?",
"answer_en":"The full penalty for a non-citizen is THREE penalties TOGETHER: (1) a fine NOT LESS THAN TZS 10,000,000 (not a maximum — it is the MINIMUM); (2) imprisonment not exceeding 6 months; AND (3) revocation of their visa and residence permit. Key language: 'not less than' means TZS 10M is the FLOOR — a court may impose more. All three penalties apply together — not one or the other.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A penalty provisions","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_002_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Adhabu ya Mtanzania anayemsaidia mgeni kufanya biashara iliyokatazwa ni nini — ni sawa na ya mgeni?",
"answer_sw":"Hapana — adhabu ya msaidizi Mtanzania ni TOFAUTI kabisa na ya mgeni: faini ya ISIYOZIDI TZS 5,000,000 AU kifungo kisichozidi miezi 3 — si zote mbili pamoja. Tofauti kuu tatu: (1) kiasi: 5M si 10M; (2) muundo: AU (si NA); (3) hakuna kufutwa kwa visa kwa sababu Mtanzania si mgeni.",
"question_en":"Is the penalty for a Tanzanian who helps a non-citizen conduct a prohibited business the same as for the non-citizen?",
"answer_en":"No — the Tanzanian facilitator's penalty is completely DIFFERENT from the non-citizen's: a fine NOT EXCEEDING TZS 5,000,000 OR imprisonment not exceeding 3 months — not both together. Three key differences: (1) amount: 5M not 10M; (2) structure: OR not AND; (3) no visa revocation because the Tanzanian is not a foreigner.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A penalty provisions","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_003_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Faini ya TZS 5 milioni (msaidizi) ni kubwa zaidi kuliko faini ya TZS 10 milioni (mgeni)?",
"answer_sw":"Hapana — TZS 10,000,000 ni KUBWA ZAIDI kuliko TZS 5,000,000. Mgeni analipa faini ya angalau TZS 10M — mara mbili ya kiwango cha juu cha msaidizi. Msaidizi Mtanzania analipa hadi TZS 5M peke yake — nusu ya faini ya chini ya mgeni. Ukumbusho: kwa mgeni 10M ni KIWANGO CHA CHINI; kwa msaidizi 5M ni KIWANGO CHA JUU.",
"question_en":"Is the TZS 5 million fine (facilitator) larger than the TZS 10 million fine (non-citizen)?",
"answer_en":"No — TZS 10,000,000 is LARGER than TZS 5,000,000. The non-citizen pays at minimum TZS 10M — twice the facilitator's maximum. The Tanzanian facilitator pays up to TZS 5M only — half the non-citizen's minimum. Reminder: for the non-citizen 10M is the FLOOR; for the facilitator 5M is the CEILING.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A penalty provisions","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_004_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Je, visa ya mgeni inafutwa PAMOJA na faini na kifungo, au ni adhabu mbadala?",
"answer_sw":"Kufutwa kwa visa kunakwenda PAMOJA na faini na kifungo — si badala yake. Mgeni anakabiliwa na adhabu tatu wakati mmoja: (1) faini ya angalau TZS 10M, (2) kifungo hadi miezi 6, NA (3) visa kufutwa. Kufutwa kwa visa ni matokeo ya ziada — si uchaguzi wa korti bali ni lazima inayofuata uamuzi wa hatia.",
"question_en":"Is visa revocation for a non-citizen issued TOGETHER with the fine and imprisonment, or is it an alternative penalty?",
"answer_en":"Visa revocation comes TOGETHER with the fine and imprisonment — not instead of them. The non-citizen faces all three at the same time: (1) fine of at least TZS 10M, (2) imprisonment up to 6 months, AND (3) visa revocation. Visa revocation is an additional consequence — not a court choice but a mandatory result that follows a finding of guilt.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_005_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Msaidizi Mtanzania — visa yake inafutwa pia?",
"answer_sw":"Hapana — kufutwa kwa visa ni adhabu inayowahusu WAGENI peke yao chini ya GN 487A. Mtanzania msaidizi anakabiliwa na: faini ya hadi TZS 5,000,000 AU kifungo hadi miezi 3 — bila kufutwa kwa visa kwa sababu Mtanzania ana uraia na hana visa ya kuingia nchini kwake.",
"question_en":"Does a Tanzanian facilitator also have their visa revoked?",
"answer_en":"No — visa revocation is a penalty that applies to NON-CITIZENS only under GN 487A. A Tanzanian facilitator faces: a fine of up to TZS 5,000,000 OR imprisonment up to 3 months — without visa revocation because a Tanzanian citizen holds citizenship and has no entry visa in their own country.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_006_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Adhabu ya msaidizi Mtanzania ni faini YA TZS 5M NA kifungo miezi 3 — ni sahihi?",
"answer_sw":"Si sahihi — adhabu ya msaidizi ni faini ya hadi TZS 5M AU kifungo hadi miezi 3, si zote mbili. Neno 'AU' ni muhimu sana hapa — korti inachagua moja kati ya hizi mbili. Tofauti na mgeni ambapo adhabu TATU zinakwenda pamoja (faini NA kifungo NA visa kufutwa), msaidizi anapata adhabu moja tu kati ya mbili zilizotajwa.",
"question_en":"Is the Tanzanian facilitator's penalty a TZS 5M fine AND 3 months imprisonment — is that correct?",
"answer_en":"That is not correct — the facilitator's penalty is a fine of up to TZS 5M OR imprisonment up to 3 months, not both. The word 'OR' is critical here — the court chooses one of the two. Unlike the non-citizen where THREE penalties apply together (fine AND imprisonment AND visa revocation), the facilitator receives only one of the two stated penalties.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_007_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Jirani yangu Mtanzania alikopa leseni yake kwa mfanyabiashara wa Kichina ili aendeshe duka. Wote wawili wamekamatwa. Kila mmoja analipa nini?",
"answer_sw":"Adhabu ni tofauti kwa kila mmoja. Mfanyabiashara wa Kichina (mgeni): faini ya ANGALAU TZS 10,000,000 PAMOJA NA kifungo hadi miezi 6 NA kufutwa kwa visa yake. Jirani Mtanzania (msaidizi): faini ya hadi TZS 5,000,000 AU kifungo hadi miezi 3 — bila kufutwa kwa visa. Kila mmoja anapata adhabu yake mwenyewe — hazigawanyiki wala hazishirikiwi.",
"question_en":"My Tanzanian neighbour lent their licence to a Chinese businessman to run a shop. Both were arrested. What does each one pay?",
"answer_en":"The penalties are different for each. Chinese businessman (non-citizen): fine of AT LEAST TZS 10,000,000 PLUS imprisonment up to 6 months AND visa revocation. Tanzanian neighbour (facilitator): fine of up to TZS 5,000,000 OR imprisonment up to 3 months — no visa revocation. Each receives their own separate penalty — they are not shared or split.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_008_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"'Isiyopungua TZS 10M' inamaanisha nini kwa vitendo — korti inaweza kutoza zaidi ya 10M?",
"answer_sw":"Ndiyo — 'isiyopungua TZS 10,000,000' inamaanisha TZS 10M ni KIWANGO CHA CHINI. Korti inaweza kutoza 10M, 15M, 20M au zaidi kulingana na hali ya kesi — lakini haiwezi kutoza chini ya 10M. Hii ni tofauti na 'hadi TZS 10M' (yaani huwezi kutoza zaidi ya 10M). Lugha ya kisheria inabainisha: 'not less than' = minimum; 'not exceeding' = maximum.",
"question_en":"What does 'not less than TZS 10M' mean in practice — can the court impose more than 10M?",
"answer_en":"Yes — 'not less than TZS 10,000,000' means TZS 10M is the MINIMUM. A court may impose 10M, 15M, 20M or more depending on the circumstances — but it cannot impose less than 10M. This differs from 'up to TZS 10M' (meaning you cannot impose more than 10M). Legal language: 'not less than' = minimum floor; 'not exceeding' = maximum ceiling.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_009_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"'Hadi TZS 5M' (msaidizi) inamaanisha nini — korti lazima itoe 5M kamili?",
"answer_sw":"Hapana — 'hadi TZS 5,000,000' inamaanisha 5M ni KIWANGO CHA JUU. Korti inaweza kutoza chini ya 5M — 1M, 2M, 3M — lakini haiwezi kutoza zaidi ya 5M. Ukichanganya na muundo wa 'AU': korti inachagua kutoa faini (hadi 5M) AU kifungo (hadi miezi 3) — si zote mbili. Hii ni adhabu laini zaidi kuliko ya mgeni.",
"question_en":"Does 'up to TZS 5M' (facilitator) mean the court must give the full 5M?",
"answer_en":"No — 'up to TZS 5,000,000' means 5M is the MAXIMUM. A court may impose less — 1M, 2M, 3M — but cannot exceed 5M. Combined with the 'OR' structure: the court chooses to give either a fine (up to 5M) OR imprisonment (up to 3 months) — not both. This is a lighter penalty than the non-citizen's.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_010_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Kwa muhtasari — tofauti kuu tatu kati ya adhabu ya mgeni na adhabu ya msaidizi Mtanzania chini ya GN 487A?",
"answer_sw":"Tofauti tatu kuu: (1) KIASI — mgeni angalau TZS 10M (chini), msaidizi hadi TZS 5M (juu); (2) MUUNDO — mgeni: faini NA kifungo NA visa (zote tatu), msaidizi: faini AU kifungo (moja tu); (3) VISA — mgeni anapoteza visa, msaidizi hapotezi kitu cha aina hiyo. Kwa kifupi: mgeni anapewa adhabu kali zaidi, msaidizi anapewa adhabu nyepesi zaidi.",
"question_en":"Summary — what are the three main differences between a non-citizen's penalty and a Tanzanian facilitator's penalty under GN 487A?",
"answer_en":"Three key differences: (1) AMOUNT — non-citizen at least TZS 10M (floor), facilitator up to TZS 5M (ceiling); (2) STRUCTURE — non-citizen: fine AND imprisonment AND visa (all three), facilitator: fine OR imprisonment (one only); (3) VISA — non-citizen loses visa, facilitator loses nothing of that kind. In short: non-citizen receives a harsher penalty, facilitator receives a lighter one.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_011_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni aliyekamatwa akifanya biashara ya rejareja — anaweza kukwepa faini kwa kulipa haraka?",
"answer_sw":"Hapana — kulipa faini haraka haizuii adhabu nyingine. Adhabu za GN 487A zote tatu (faini ya angalau TZS 10M, kifungo hadi miezi 6, visa kufutwa) zinaamuliwa na korti. Kulipa faini si utaratibu wa makubaliano wa nje ya korti. Pia, kulipa faini hakuzuii kufutwa kwa visa — visa itafutwa hata kama faini imelipwa.",
"question_en":"A non-citizen caught conducting retail trade — can they avoid the penalty by paying quickly?",
"answer_en":"No — paying a fine quickly does not prevent the other penalties. All three GN 487A penalties (fine of at least TZS 10M, imprisonment up to 6 months, visa revocation) are decided by a court. Paying a fine is not an out-of-court settlement procedure. Also, paying the fine does not prevent visa revocation — the visa will be revoked even if the fine is paid.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_012_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Adhabu ya msaidizi ni laini sana — TZS 5M tu. Je, hii inamaanisha kuwa msaada wa wageni si kosa kubwa?",
"answer_sw":"Ingawa adhabu ya msaidizi ni ndogo kuliko ya mgeni, bado ni kosa kubwa la kisheria. Faini ya hadi TZS 5M AU miezi 3 jela ni adhabu nzito. Aidha, kumbuka kwamba mashitaka yanaweza kuwa ya jinai (criminal) ambayo yataathiri historia ya msaidizi na kazi yake ya siku zijazo. Msaidizi anaweza pia kupoteza leseni yake ya biashara kama korti itaona inafaa.",
"question_en":"The facilitator's penalty seems light — only TZS 5M. Does this mean helping non-citizens is not a serious offence?",
"answer_en":"Although the facilitator's penalty is smaller than the non-citizen's, it remains a serious criminal offence. A fine of up to TZS 5M OR 3 months' imprisonment is a significant punishment. Moreover, the charges may be criminal in nature which will affect the facilitator's record and future employment. A facilitator may also lose their business licence if the court sees fit.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_013_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni alipewa faini ya TZS 8 milioni na hakufungwa. Je, hii ni adhabu sahihi chini ya GN 487A?",
"answer_sw":"Hapana — faini ya TZS 8,000,000 ni CHINI ya kiwango cha chini cha TZS 10,000,000 kilichowekwa na GN 487A. Kama korti ilitoa adhabu hiyo, ni kosa la kisheria — faini lazima iwe TZS 10M au zaidi. Pia, kutofungwa na kutofutwa kwa visa ni tatizo tofauti — adhabu kamili zinapaswa kutolewa zote tatu. Mshtakiwa anaweza kupinga uamuzi huo mahakamani.",
"question_en":"A non-citizen was fined TZS 8 million and not imprisoned. Is this a correct penalty under GN 487A?",
"answer_en":"No — a fine of TZS 8,000,000 is BELOW the minimum of TZS 10,000,000 set by GN 487A. If a court issued such a penalty it would be a legal error — the fine must be TZS 10M or more. Also, not being imprisoned and not having the visa revoked raises separate issues — all three penalties should have been imposed. The defendant could challenge such a ruling on appeal.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_014_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Jirani Mtanzania alilipa TZS 5M na akafungwa miezi 3 kwa kumsaidia mgeni. Je, hii ni adhabu sahihi?",
"answer_sw":"Hapana — adhabu hii haiko sahihi. Adhabu ya msaidizi Mtanzania ni faini ya hadi TZS 5M AU kifungo hadi miezi 3 — si zote mbili pamoja. Kumlazimisha jirani alipe 5M NA kufungwa wakati huo huo ni kuvuka mipaka ya sheria. Jirani anastahili moja tu kati ya mbili: faini (hadi 5M) au kifungo (hadi miezi 3).",
"question_en":"A Tanzanian neighbour paid TZS 5M and was also imprisoned for 3 months for facilitating a non-citizen. Is this the correct penalty?",
"answer_en":"No — this penalty is incorrect. A Tanzanian facilitator's penalty is a fine of up to TZS 5M OR imprisonment up to 3 months — not both together. Forcing the neighbour to pay 5M AND be imprisoned simultaneously exceeds the legal limits. The neighbour is entitled to only one of the two: a fine (up to 5M) or imprisonment (up to 3 months).",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_015_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"GN 487A inasema mgeni atafungwa miezi 6 — hii ni lazima au korti inaweza kutoa chini ya miezi 6?",
"answer_sw":"Kifungo cha miezi 6 ni KIWANGO CHA JUU — si lazima. GN 487A inasema 'kisichozidi miezi 6' maana yake korti inaweza kutoa siku 1, mwezi 1, miezi 3, au hadi miezi 6 kulingana na hali. Kwa faini, GN 487A inasema 'isiyopungua TZS 10M' — hapa korti haiwezi kutoa chini ya 10M. Kwa hivyo faini ina kiwango cha chini (lazima angalau 10M) lakini kifungo hakina kiwango cha chini kilichowekwa.",
"question_en":"GN 487A says a non-citizen will be imprisoned for 6 months — is this mandatory or can the court give less than 6 months?",
"answer_en":"The 6-month imprisonment is a MAXIMUM — not mandatory. GN 487A says 'not exceeding 6 months' meaning a court may give 1 day, 1 month, 3 months, or up to 6 months depending on circumstances. For the fine, GN 487A says 'not less than TZS 10M' — here the court cannot give less than 10M. So the fine has a mandatory minimum (at least 10M) but imprisonment has no stated minimum.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_016_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Rafiki yangu wa Kiindia alipewa onyo tu bila faini wala kifungo. Je, GN 487A inaruhusu onyo?",
"answer_sw":"Sheria ya GN 487A haitaji 'onyo' kama adhabu rasmi — inabainisha faini ya angalau TZS 10M, kifungo hadi miezi 6, na kufutwa kwa visa. Onyo si adhabu iliyotajwa katika sheria. Hata hivyo, wakati wa ukaguzi wa mara ya kwanza au kabla ya kesi, mamlaka inaweza kutoa tahadhari ya kiutawala. Hii si onyo rasmi wa kisheria — ikiwa kesi itafunguliwa mahakamani, adhabu kamili zinatumika.",
"question_en":"My Indian friend was only warned with no fine or imprisonment. Does GN 487A allow warnings?",
"answer_en":"GN 487A law does not provide for a 'warning' as a formal penalty — it specifies a fine of at least TZS 10M, imprisonment up to 6 months, and visa revocation. A warning is not a stated penalty in the law. However, during initial inspections or pre-prosecution, authorities may issue an administrative caution. This is not a formal legal warning — if a case goes to court, the full penalties apply.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_017_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni na msaidizi wamekamatwa pamoja — wanashtakiwa pamoja au tofauti?",
"answer_sw":"Wanaweza kushtakiwa pamoja katika kesi moja au tofauti — hii inategemea uamuzi wa mkurugenzi wa mashtaka. Hata kama wanashtakiwa pamoja, adhabu zao ni tofauti kabisa: mgeni: angalau TZS 10M NA kifungo NA visa kufutwa; msaidizi: hadi TZS 5M AU kifungo miezi 3. Kushtakiwa pamoja haimaanishi wapate adhabu sawa — sheria inabainisha adhabu tofauti kwa kila mmoja.",
"question_en":"A non-citizen and facilitator are arrested together — are they prosecuted together or separately?",
"answer_en":"They may be prosecuted together in one case or separately — this depends on the prosecutor's decision. Even if prosecuted together, their penalties are completely different: non-citizen: at least TZS 10M AND imprisonment AND visa revocation; facilitator: up to TZS 5M OR imprisonment up to 3 months. Being prosecuted together does not mean receiving the same penalty — the law specifies different penalties for each.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_pen_018_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni ana biashara mbili zilizopigwa marufuku — anapata adhabu mara mbili?",
"answer_sw":"GN 487A haitoi jibu wazi kuhusu biashara nyingi zilizovunjwa wakati mmoja. Kanuni ya jumla ya kisheria Tanzania ni kwamba kila kosa tofauti linaweza kusababisha adhabu tofauti. Hata hivyo, mahakama inaweza kuunganisha adhabu (concurrent sentences) au kuzitoa tofauti (consecutive). Suala hili linahitaji mshauri wa kisheria kwa kesi yako mahususi.",
"question_en":"A non-citizen has two prohibited businesses — do they receive double penalties?",
"answer_en":"GN 487A does not give an explicit answer on multiple violations prosecuted simultaneously. The general Tanzanian legal principle is that each separate offence may result in a separate penalty. However, a court may impose concurrent sentences (running together) or consecutive sentences (one after another). This question requires a legal adviser for your specific case.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_pen_019_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Adhabu ya GN 487A kwa mgeni ni TZS 10M tu — hii ni ndogo sana kwa biashara kubwa ya jumla. Je, kuna adhabu nyingine?",
"answer_sw":"TZS 10M ni faini ya CHINI KABISA — korti inaweza kutoza zaidi. Aidha, adhabu za GN 487A si adhabu pekee: mgeni anaweza pia (1) kupoteza bidhaa zake kama mali iliyopatikana kupitia biashara haramu; (2) kufutwa kwa leseni za biashara; (3) kutenganishwa (deportation) baada ya kushughulikia adhabu ya jela. GN 487A ni msingi — sheria nyingine zinaweza pia kutumika.",
"question_en":"The GN 487A penalty for a non-citizen is only TZS 10M — this seems small for a large wholesale business. Are there other penalties?",
"answer_en":"TZS 10M is the MINIMUM fine — a court may impose more. Also, GN 487A penalties are not the only consequences: a non-citizen may also (1) forfeit goods acquired through the illegal business; (2) lose business licences; (3) be deported after serving a prison sentence. GN 487A is the basis — other laws may also apply.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_pen_020_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Msaidizi Mtanzania anaweza kupata faini ZAIDI ya TZS 5M ikiwa uharibifu ni mkubwa?",
"answer_sw":"Hapana — kwa makosa ya GN 487A peke yake, korti haiwezi kutoza msaidizi zaidi ya TZS 5M kwa sababu 5M ni kiwango cha juu kilichowekwa na sheria. Hata hivyo, ikiwa msaidizi amefanya makosa mengine ya kisheria — ulaghai, unyang'anyi wa biashara, au kuvunja sheria nyingine — korti inaweza kutoza adhabu za ziada kwa makosa hayo mengine.",
"question_en":"Can a Tanzanian facilitator be fined MORE than TZS 5M if the damage is extensive?",
"answer_en":"No — under GN 487A specifically, a court cannot fine a facilitator more than TZS 5M because 5M is the maximum ceiling set by the law. However, if the facilitator has committed other legal offences — fraud, business theft, or violation of other laws — a court may impose additional penalties for those separate offences.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_021_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Rafiki yangu Mchina anasema adhabu ya GN 487A ni 'hadi TZS 10M' — anasema ukweli?",
"answer_sw":"Hapana — rafiki yako ana kosa kubwa. GN 487A inasema faini 'ISIYOPUNGUA TZS 10,000,000' — maana yake 10M ni KIWANGO CHA CHINI, si cha juu. 'Hadi 10M' ingemaanisha korti inaweza kutoa chini ya 10M — hii si kweli. Usitegemee tafsiri ya mtu asiye mtaalamu wa sheria kwa suala hili — adhabu inaweza kuwa zaidi ya mara mbili ya unavyodhani.",
"question_en":"My Chinese friend says the GN 487A penalty is 'up to TZS 10M' — are they correct?",
"answer_en":"No — your friend has a serious misunderstanding. GN 487A states a fine 'NOT LESS THAN TZS 10,000,000' — meaning 10M is the MINIMUM, not the maximum. 'Up to 10M' would mean a court could give less than 10M — that is not true. Do not rely on a non-legal expert's interpretation on this matter — the penalty may be more than twice what you expect.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_pen_022_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Ni nani anayeweza kuripoti mgeni anayefanya biashara haramu chini ya GN 487A?",
"answer_sw":"Mtu yeyote anaweza kuripoti — raia, mshindani wa biashara, au afisa yeyote wa serikali. Idara kuu za utekelezaji ni: Idara ya Uhamiaji, TRA (Tanzania Revenue Authority), na polisi. Unaweza kuwasiliana na Idara ya Uhamiaji kupitia simu yao ya dharura au ofisi ya karibu nawe. Ripoti za siri (confidential reports) zinakubaliwa. Mripoti hakabiwi adhabu kwa kuripoti kwa nia njema.",
"question_en":"Who can report a non-citizen conducting an illegal business under GN 487A?",
"answer_en":"Anyone can report — a citizen, a business competitor, or any government official. The main enforcement departments are: the Immigration Department, TRA (Tanzania Revenue Authority), and the police. You can contact the Immigration Department through their emergency line or nearest office. Confidential reports are accepted. A reporter is not penalised for reporting in good faith.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_pen_023_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Adhabu ya GN 487A inaanza lini — tangu wakati wa kukamatwa au baada ya hukumu ya korti?",
"answer_sw":"Adhabu rasmi (faini, kifungo, visa kufutwa) zinaanza baada ya HUKUMU ya korti — si wakati wa kukamatwa au kushitakiwa. Wakati wa kukamatwa (arrest), mgeni anaweza kuwekwa kizuizini (remand) hadi kesi iishe. Kizuizini kabla ya hukumu ni tofauti na kifungo cha adhabu — ingawa mara nyingi muda wa kizuizini huhesabiwa katika jumla ya adhabu ya jela.",
"question_en":"When does a GN 487A penalty begin — from the time of arrest or after a court judgement?",
"answer_en":"Formal penalties (fine, imprisonment, visa revocation) begin AFTER a court JUDGEMENT — not at time of arrest or charging. At the time of arrest, the non-citizen may be held in remand custody until the case concludes. Pre-judgement remand is different from a punitive prison sentence — though the remand period is often counted against the total prison sentence.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_pen_024_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Nikiwa msaidizi, nikiri kosa — adhabu yangu itapungua?",
"answer_sw":"Kukiri kosa (guilty plea) kunaweza kupunguza adhabu katika mfumo wa mahakama Tanzania — korti inazingatia ushirikiano na ukweli wa kustahimili. Lakini adhabu ya msaidizi ina kikwazo cha juu cha TZS 5M AU miezi 3 jela — kukiri kosa kunaweza kusaidia kupata adhabu ndogo ndani ya mipaka hii, si kuvuka mipaka. Wasiliana na wakili kabla ya kutoa jibu lolote mahakamani.",
"question_en":"If I am a facilitator and plead guilty — will my penalty be reduced?",
"answer_en":"A guilty plea may reduce a penalty in Tanzania's court system — courts take cooperation and honest admission into account. However the facilitator's penalty already has a ceiling of TZS 5M OR 3 months' imprisonment — a guilty plea may help obtain a penalty at the lower end within those limits, not below them. Consult a lawyer before giving any answer in court.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_pen_025_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Je, TZS 10M (mgeni) au TZS 5M (msaidizi) zinahusu kila mwaka au mara moja tu?",
"answer_sw":"Faini zinazotolewa na GN 487A ni kwa KESI MOJA — si kila mwaka. Kila wakati mgeni anapokamatwa na kupatikana na hatia, analipa faini ya angalau TZS 10M kwa kesi hiyo. Biashara haramu inayoendelea bila kukaguliwa haiongezi faini kiotomatiki — lakini kila kamatwa na hukumu ni adhabu mpya tofauti.",
"question_en":"Are the TZS 10M (non-citizen) or TZS 5M (facilitator) penalties charged annually or just once?",
"answer_en":"The GN 487A penalties are per CASE — not annually. Each time a non-citizen is arrested and found guilty they pay a fine of at least TZS 10M for that case. A prohibited business continuing to operate without being caught does not automatically accumulate fines — but each arrest and conviction is a fresh separate penalty.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_pen_026_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Biashara ya rejareja iliyofanywa na mgeni kwa miaka mitatu. Adhabu itahesabiwa kwa miaka mitatu?",
"answer_sw":"Hapana — adhabu ya GN 487A inategemea USHAHIDI wa muda wa ukiukaji uliobainishwa mahakamani, si muda wote ambao biashara ilifanya kazi. Korti inazingatia ushahidi uliowasilishwa. Hata hivyo, muda mrefu wa ukiukaji unaweza kuathiri ukali wa adhabu ndani ya mipaka ya sheria — korti inaweza kutoza faini kubwa zaidi kuliko kiwango cha chini cha 10M.",
"question_en":"Retail business conducted by a non-citizen for three years. Will the penalty be calculated for three years?",
"answer_en":"No — the GN 487A penalty depends on the EVIDENCE of the violation period established in court, not the entire period the business operated. The court considers the evidence presented. However, a long period of violation may influence the severity of the penalty within the legal limits — a court may impose a higher fine than the 10M minimum.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_pen_027_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni aliyefukuzwa (deported) kabla ya kulipa faini yake — je, faini hiyo inaendelea kuwepo?",
"answer_sw":"Kwa kawaida, mtu aliyefukuzwa kabla ya kumaliza mchakato wa kisheria anakimbia adhabu — hii ni tatizo la kawaida la kisheria kimataifa. Tanzania inaweza kujaribu kutekeleza uamuzi wa korti kupitia njia za kisheria za kimataifa, lakini hii ni ngumu vitendo. Kufukuzwa huzuia utekelezaji wa muda mfupi lakini uamuzi wa korti unabaki halali.",
"question_en":"A non-citizen was deported before paying their fine — does the fine still exist?",
"answer_en":"Typically, a person deported before completing the legal process escapes the penalty — this is a common international legal challenge. Tanzania may attempt to enforce the court order through international legal channels, but this is difficult in practice. Deportation prevents short-term enforcement but the court order remains legally valid.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_pen_028_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Ni adhabu gani TATU za GN 487A kwa mgeni — zitaje kwa mpangilio?",
"answer_sw":"Adhabu TATU za GN 487A kwa mgeni (raia wa kigeni) kwa mpangilio: (1) FAINI isiyopungua TZS 10,000,000 — kiwango cha chini, korti inaweza kutoza zaidi; (2) KIFUNGO kisichozidi miezi 6 — kiwango cha juu; (3) KUFUTWA kwa visa na kibali cha ukaazi — lazima iende pamoja na adhabu nyingine. Neno la kiungo: NA — si AU. Zote tatu zinakwenda pamoja.",
"question_en":"What are the THREE GN 487A penalties for a non-citizen — list them in order?",
"answer_en":"The THREE GN 487A penalties for a non-citizen (foreign national) in order: (1) FINE not less than TZS 10,000,000 — minimum floor, court may impose more; (2) IMPRISONMENT not exceeding 6 months — maximum ceiling; (3) REVOCATION of visa and residence permit — must accompany the other penalties. Connective word: AND — not OR. All three go together.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_pen_029_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Ni adhabu gani MBILI za GN 487A kwa msaidizi Mtanzania — zitaje kwa mpangilio na maneno sahihi?",
"answer_sw":"Adhabu MBILI za GN 487A kwa msaidizi Mtanzania kwa mpangilio: (1) FAINI isiyozidi TZS 5,000,000 — kiwango cha juu (si cha chini); AU (2) KIFUNGO kisichozidi miezi 3 — kiwango cha juu. Neno la kiungo: AU — si NA. Korti inachagua moja kati ya mbili hizi. Hakuna kufutwa kwa visa — msaidizi ni Mtanzania. Msaidizi hana adhabu tatu — ana mbili tu na korti inachagua moja.",
"question_en":"What are the TWO GN 487A penalties for a Tanzanian facilitator — list them in order with exact words?",
"answer_en":"The TWO GN 487A penalties for a Tanzanian facilitator in order: (1) FINE not exceeding TZS 5,000,000 — a maximum ceiling (not a minimum); OR (2) IMPRISONMENT not exceeding 3 months — a maximum ceiling. Connective word: OR — not AND. The court chooses one of these two. No visa revocation — the facilitator is Tanzanian. The facilitator does not have three penalties — only two and the court picks one.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_pen_030_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Kwa muhtasari wa haraka: mgeni TZS ngapi? Msaidizi TZS ngapi? Ni NA au AU? Visa inahusu nani?",
"answer_sw":"Muhtasari: MGENI — faini ya angalau TZS 10,000,000 (kiwango cha chini) NA kifungo hadi miezi 6 NA visa kufutwa. MSAIDIZI — faini ya hadi TZS 5,000,000 (kiwango cha juu) AU kifungo hadi miezi 3. Kwa mgeni ni NA (zote tatu). Kwa msaidizi ni AU (moja ya mbili). Visa inahusu mgeni peke yake — si msaidizi Mtanzania.",
"question_en":"Quick summary: non-citizen how much? Facilitator how much? AND or OR? Visa for whom?",
"answer_en":"Summary: NON-CITIZEN — fine of at least TZS 10,000,000 (minimum) AND imprisonment up to 6 months AND visa revoked. FACILITATOR — fine of up to TZS 5,000,000 (maximum) OR imprisonment up to 3 months. For non-citizen it is AND (all three). For facilitator it is OR (one of two). Visa applies to non-citizen only — not Tanzanian facilitator.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

# ══════════════════════════════════════════════════════════
# FIX 2 — GN 487A SCOPE (20 pairs)
# Wholesale IS prohibited. Retail IS prohibited.
# Applies to NON-CITIZENS ONLY.
# ══════════════════════════════════════════════════════════

{"id":f"b008_gn487a_scp_001_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Je, biashara ya jumla (wholesale) imekatazwa kwa wageni chini ya GN 487A?",
"answer_sw":"NDIYO — biashara ya jumla (wholesale) iko katika orodha ya biashara 15 zilizopigwa marufuku kwa wageni chini ya GN 487A. Mgeni anayeendesha biashara ya jumla — kuuza bidhaa kwa maduka, wafanyabiashara wengine, au kwa wingi — anakiuka GN 487A na anastahili adhabu kamili: faini ya angalau TZS 10M, kifungo, na visa kufutwa.",
"question_en":"Is wholesale trade prohibited for non-citizens under GN 487A?",
"answer_en":"YES — wholesale trade is on the list of 15 business categories prohibited for non-citizens under GN 487A. A non-citizen running a wholesale business — selling goods to shops, other traders, or in bulk — is violating GN 487A and is subject to the full penalty: fine of at least TZS 10M, imprisonment, and visa revocation.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A prohibited category list","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_002_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Biashara ya rejareja (retail) imekatazwa kwa wageni — na biashara ya jumla pia?",
"answer_sw":"NDIYO kwa zote mbili. Biashara ya rejareja (kuuza bidhaa moja kwa moja kwa wateja) NA biashara ya jumla (kuuza bidhaa kwa wingi kwa maduka) — zote mbili ziko kwenye orodha ya biashara 15 zilizopigwa marufuku kwa wageni. Miongoni mwa biashara 15 zilizopigwa marufuku pia ni: uhamisho wa pesa za simu, ukarabati wa simu, salon za nywele, na kinyozi.",
"question_en":"Is retail trade prohibited for non-citizens — and also wholesale trade?",
"answer_en":"YES to both. Retail trade (selling goods directly to customers) AND wholesale trade (selling goods in bulk to shops) — both are on the list of 15 prohibited business categories for non-citizens. Among the other 15 prohibited businesses are also: mobile money transfers, phone repair, hair salons, and barbershops.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A prohibited category list","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_003_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"GN 487A inawahusu Watanzania pia au wageni tu?",
"answer_sw":"GN 487A inawahusu WAGENI (raia wa kigeni) TU — Watanzania hawakabiwi vikwazo vya GN 487A kwa biashara. Raia wa Tanzania wana uhuru wa kufanya biashara yoyote inayoruhusiwa kisheria nchini Tanzania bila kizuizi cha GN 487A. Adhabu ya GN 487A (faini ya TZS 10M+, kifungo, visa kufutwa) inatumika kwa wageni wanaovunja sheria hii — si kwa Watanzania.",
"question_en":"Does GN 487A apply to Tanzanians too or only to non-citizens?",
"answer_en":"GN 487A applies to NON-CITIZENS (foreign nationals) ONLY — Tanzanians are not subject to GN 487A business prohibitions. Tanzanian citizens are free to conduct any legally permitted business in Tanzania without GN 487A restrictions. GN 487A penalties (TZS 10M+ fine, imprisonment, visa revocation) apply to non-citizens who violate the law — not to Tanzanians.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_004_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mimi ni Mtanzania — GN 487A inazuia mimi kufanya rejareja au jumla?",
"answer_sw":"Hapana — GN 487A haikuzuii wewe kama Mtanzania kufanya biashara ya rejareja au jumla. Vikwazo vya GN 487A ni kwa wageni peke yake. Wewe kama raia wa Tanzania una uhuru kamili wa kufanya biashara hizi na biashara zingine zote zinazoruhusiwa na sheria ya Tanzania. Unastahili tu kufuata sheria za kawaida za biashara: TIN, leseni, BRELA, nk.",
"question_en":"I am a Tanzanian — does GN 487A prohibit me from doing retail or wholesale trade?",
"answer_en":"No — GN 487A does not prohibit you as a Tanzanian from conducting retail or wholesale trade. GN 487A restrictions are for non-citizens only. As a Tanzanian citizen you are fully free to conduct these and all other businesses permitted by Tanzanian law. You only need to comply with the usual business regulations: TIN, licences, BRELA registration, etc.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_005_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"GN 487A ina orodha ya biashara ngapi zilizopigwa marufuku kwa wageni — na ni zipi kuu?",
"answer_sw":"GN 487A inapiga marufuku makundi 15 ya biashara kwa wageni. Miongoni mwa biashara zilizotajwa: (1) biashara ya rejareja, (2) biashara ya jumla, (3) uhamisho wa pesa za simu (mobile money agent), (4) ukarabati wa simu za mkononi, (5) salon ya nywele na biashara ya uzuri, (6) kinyozi, (7) ushonaji wa nguo, (8) mkahawa wa chakula wa kiwango kidogo, (9) huduma za usafi wa nyumba, na makundi 6 mengine. Thibitisha orodha kamili na Idara ya Uhamiaji au TanzLII.",
"question_en":"How many business categories does GN 487A prohibit for non-citizens — and what are the main ones?",
"answer_en":"GN 487A prohibits 15 categories of business for non-citizens. Among the listed businesses: (1) retail trade, (2) wholesale trade, (3) mobile money transfer services, (4) mobile phone repair, (5) hair salons and beauty business, (6) barbershops, (7) tailoring and garment making, (8) small-scale food outlets, (9) domestic cleaning services, and 6 other categories. Verify the complete list with the Immigration Department or TanzLII.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A prohibited category list","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_scp_006_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni wa China ana duka la simu (ukarabati) na duka la rejareja — ni moja au yote mawili yanabeba tatizo la GN 487A?",
"answer_sw":"Yote MAWILI yanabeba tatizo. Ukarabati wa simu NA biashara ya rejareja — zote mbili ziko kwenye orodha ya biashara 15 zilizopigwa marufuku kwa wageni chini ya GN 487A. Mgeni anayeendesha duka moja au duka mbili za aina hizi anakiuka GN 487A. Kila kesi ni ukiukaji tofauti unaostahili adhabu.",
"question_en":"A Chinese non-citizen has a phone repair shop and a retail shop — does only one or do both carry a GN 487A problem?",
"answer_en":"BOTH carry a problem. Phone repair AND retail trade — both are on the list of 15 prohibited business categories for non-citizens under GN 487A. A non-citizen running one or both shops of these types is violating GN 487A. Each case is a separate violation that deserves a penalty.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_007_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni anayefanya biashara ya jumla (wholesale) anasema sheria inazuia rejareja tu — si jumla. Ana haki?",
"answer_sw":"Hapana — ana kosa kubwa. GN 487A inapiga marufuku BIASHARA ZA JUMLA NA REJAREJA zote mbili. Orodha ya biashara 15 zilizopigwa marufuku inajumuisha wazi biashara ya jumla na biashara ya rejareja kama makundi tofauti. Mgeni anayeendesha jumla anakiuka GN 487A kama vile mwenye duka la rejareja. Jibu hili 'jumla tu inaruhusiwa' ni hatari na si kweli.",
"question_en":"A non-citizen wholesale trader says the law only prohibits retail, not wholesale. Are they correct?",
"answer_en":"No — they have a serious misunderstanding. GN 487A prohibits BOTH wholesale AND retail trade. The list of 15 prohibited categories explicitly includes wholesale trade and retail trade as separate categories. A non-citizen running wholesale is violating GN 487A just as much as a retail shop owner. The claim 'only retail is prohibited' is dangerous and incorrect.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_008_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mkenya anayeendesha salon ya nywele Dar es Salaam, mkahawa mdogo, na huduma za M-Pesa — ni ipi kati ya hizi inayokiuka GN 487A?",
"answer_sw":"ZOTE TATU zinakiuka GN 487A. (1) Salon ya nywele — ipo kwenye orodha ya biashara zilizopigwa marufuku. (2) Mkahawa mdogo wa chakula — ipo kwenye orodha. (3) Wakala wa M-Pesa/huduma za uhamisho wa pesa za simu — ipo kwenye orodha. Mkenya (au mgeni yeyote asiye raia wa Tanzania) anayefanya biashara hizi tatu anakiuka GN 487A kwa makosa matatu tofauti.",
"question_en":"A Kenyan national runs a hair salon in Dar es Salaam, a small food outlet, and M-Pesa services — which of these violates GN 487A?",
"answer_en":"ALL THREE violate GN 487A. (1) Hair salon — is on the list of prohibited businesses. (2) Small food outlet — is on the list. (3) M-Pesa agent/mobile money transfer services — is on the list. A Kenyan (or any non-Tanzanian citizen) running all three of these businesses is violating GN 487A for three separate offences.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_009_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"GN 487A inaathiri Watanzania wote? Au ni wageni wa nchi fulani tu?",
"answer_sw":"GN 487A inawahusu WAGENI (raia wa kigeni) WOTE — bila kujali utaifa wao. Inazuia raia wa Kenya, China, India, Uropa, na nchi yoyote nyingine kufanya biashara zilizoorodheshwa. Watanzania wote (wa asili na wenye uraia) hawaathiriwi na vikwazo vya GN 487A kwa biashara. Hivyo, utaifa si kigezo — uraia wa Tanzania ndicho kigezo.",
"question_en":"Does GN 487A affect all Tanzanians? Or only non-citizens from certain countries?",
"answer_en":"GN 487A applies to ALL NON-CITIZENS (foreign nationals) — regardless of their nationality. It prohibits citizens of Kenya, China, India, Europe, and any other country from conducting the listed businesses. All Tanzanians (by birth or naturalisation) are unaffected by GN 487A business prohibitions. So nationality is not the criterion — Tanzanian citizenship is the criterion.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_010_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni ana kinyozi na pia anafundisha kukata nywele. Kufundisha pia kunakatazwa?",
"answer_sw":"Kinyozi (barbershop) kama biashara ya uendeshaji imekatazwa wazi. Kufundisha (training/shule ya ufundi) ni swali tofauti — GN 487A inazuia biashara za uendeshaji zilizoorodheshwa, si kila aina ya shughuli inayohusiana. Hata hivyo, kama 'kufundisha' ni njia ya kukwepa kinyozi kilichokatazwa (mnunuzi wa huduma ni mteja wa kinyozi), inaweza bado kuzingatiwa ukiukaji. Wasiliana na Idara ya Uhamiaji kwa ufafanuzi.",
"question_en":"A non-citizen runs a barbershop and also teaches haircutting. Is the teaching also prohibited?",
"answer_en":"A barbershop as an operational business is explicitly prohibited. Teaching (training/vocational school) is a separate question — GN 487A prohibits the listed operational businesses, not every related activity. However, if the 'teaching' is a way to disguise a prohibited barbershop (the service recipient is effectively a barber customer), it may still be considered a violation. Consult the Immigration Department for clarification.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_scp_011_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Kampuni ya Tanzania inayomilikiwa na mgeni — inaweza kufanya biashara ya rejareja?",
"answer_sw":"Hapana — umiliki wa kampuni si njia ya kukwepa GN 487A. Sheria inazuia mgeni kufanya biashara zilizoorodheshwa — hata kwa njia ya kampuni inayomilikiwa na mgeni. Ikiwa mgeni ndiye mmiliki na mwenye nguvu za uamuzi wa kampuni inayofanya rejareja, hii inachukuliwa ukiukaji wa GN 487A. Muundo wa kisheria (kampuni vs mtu binafsi) hauzuii utekelezaji wa sheria.",
"question_en":"A Tanzania company owned by a non-citizen — can it conduct retail trade?",
"answer_en":"No — company ownership is not a way to circumvent GN 487A. The law prohibits a non-citizen from conducting the listed businesses — including through a company owned by a non-citizen. If a non-citizen is the owner and decision-maker of a company conducting retail trade, this is treated as a GN 487A violation. Legal structure (company vs individual) does not prevent law enforcement.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_012_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"GN 487A inahusu Tanzania Bara tu au Zanzibar pia?",
"answer_sw":"GN 487A ni amri ya serikali ya Tanzania Bara (Mainland Tanzania) — haina nguvu moja kwa moja Zanzibar. Zanzibar ina mfumo wake wa kisheria na usimamizi wa biashara unaotawaliwa na Serikali ya Mapinduzi ya Zanzibar (SMZ). Hata hivyo, biashara zinazofanywa katika Tanzania Bara, hata na watu wanaishi Zanzibar, zinaathiriwa na GN 487A.",
"question_en":"Does GN 487A apply to Tanzania Mainland only or also Zanzibar?",
"answer_en":"GN 487A is an order of the Tanzania Mainland government — it does not apply directly to Zanzibar. Zanzibar has its own legal framework and business regulation governed by the Revolutionary Government of Zanzibar (RGoZ). However, businesses conducted in Tanzania Mainland, even by people living in Zanzibar, are affected by GN 487A.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or Zanzibar business regulation changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_scp_013_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Ushonaji wa nguo — umekatazwa kwa wageni chini ya GN 487A?",
"answer_sw":"Ndiyo — ushonaji wa nguo (tailoring and garment making) uko kwenye orodha ya biashara zilizopigwa marufuku kwa wageni chini ya GN 487A, pamoja na biashara nyingine kama rejareja, jumla, uhamisho wa pesa, ukarabati wa simu, salon, na kinyozi. Wageni wanaofanya kazi ya ushonaji kama biashara ya kibiashara wanakiuka GN 487A.",
"question_en":"Is tailoring/garment making prohibited for non-citizens under GN 487A?",
"answer_en":"Yes — tailoring and garment making is on the list of business categories prohibited for non-citizens under GN 487A, alongside other businesses such as retail, wholesale, mobile money transfers, phone repair, hair salons, and barbershops. Non-citizens conducting tailoring as a commercial business are violating GN 487A.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A prohibited category list","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_scp_014_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni anayemiliki majengo na kukodisha maduka — anakiuka GN 487A?",
"answer_sw":"Kukodisha mali (real estate rental) kwa ujumla si miongoni mwa biashara 15 zilizopigwa marufuku moja kwa moja na GN 487A. Hata hivyo, mipaka inaweza kuwa na utata — kama mgeni anamiliki na kuendesha jengo kama mkahawa au duka la rejareja mwenyewe ndiye muendesha, inaweza kuzingatiwa ukiukaji. Kuhusu kukodisha maduka kwa Watanzania wengine kuendesha — hii kwa kawaida ipo nje ya marufuku ya GN 487A. Thibitisha na Idara ya Uhamiaji.",
"question_en":"A non-citizen who owns buildings and rents out shops — do they violate GN 487A?",
"answer_en":"Renting out property (real estate rental) is not directly among the 15 business categories explicitly prohibited by GN 487A. However, the boundaries may be complex — if a non-citizen owns and personally operates a building as a food outlet or retail shop, it could be considered a violation. Renting shops to other Tanzanians to operate — this is generally outside GN 487A's prohibition. Verify with the Immigration Department.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_scp_015_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"GN 487A ilitangazwa lini na ilianza kutumika lini?",
"answer_sw":"GN 487A ilitangazwa tarehe 28 Julai 2025 na ilianza kutumika mara moja siku hiyo hiyo. Idara ya Uhamiaji ilifanya operesheni ya utekelezaji kati ya tarehe 11 Septemba 2025 na 8 Oktoba 2025. Amri hii ni ya mwaka 2025 — si 2023 wala 2024. Jina kamili: Business Licensing (Prohibition of Business Activities for Non-Citizens) Order 2025.",
"question_en":"When was GN 487A gazetted and when did it take effect?",
"answer_en":"GN 487A was gazetted on 28 July 2025 and took effect immediately on the same day. The Immigration Department conducted an enforcement operation between 11 September 2025 and 8 October 2025. This order is from 2025 — not 2023 or 2024. Full name: Business Licensing (Prohibition of Business Activities for Non-Citizens) Order 2025.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_scp_016_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni anafanya biashara ya kuuza bidhaa za mikono ya pili (second-hand goods). Je, hii imekatazwa?",
"answer_sw":"Biashara ya bidhaa za mikono ya pili (second-hand goods trading) iko kwenye aina za biashara zilizopigwa marufuku kwa wageni chini ya GN 487A. Wageni wanaouza nguo za pili mkono, vifaa vya nyumbani vya pili mkono, au bidhaa nyingine za pili kwenye masoko au madukani wanakiuka GN 487A. Thibitisha kategoria kamili kwenye tovuti ya TanzLII au Idara ya Uhamiaji.",
"question_en":"A non-citizen trades second-hand goods. Is this prohibited?",
"answer_en":"Second-hand goods trading is among the business categories prohibited for non-citizens under GN 487A. Non-citizens selling second-hand clothes, second-hand household goods, or other used items at markets or shops are violating GN 487A. Verify the complete category list at TanzLII or the Immigration Department website.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A prohibited category list","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_scp_017_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Je, huduma za usafi wa nyumba (cleaning services) zimekatazwa kwa wageni?",
"answer_sw":"Ndiyo — huduma za usafi wa nyumba na ofisi (domestic and commercial cleaning services) ziko kwenye orodha ya biashara 15 zilizopigwa marufuku kwa wageni chini ya GN 487A. Wageni wanaoendesha kampuni za usafi, kuajiri wafanyakazi wa kusafisha, au kutoa huduma za usafi kama biashara wanakiuka GN 487A.",
"question_en":"Are domestic and commercial cleaning services prohibited for non-citizens?",
"answer_en":"Yes — domestic and commercial cleaning services are on the list of 15 business categories prohibited for non-citizens under GN 487A. Non-citizens who operate cleaning companies, employ cleaning workers, or provide cleaning services as a business are violating GN 487A.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A prohibited category list","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_scp_018_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni Mreno anauza mboga na matunda sokoni Kariakoo. Hii inakiuka GN 487A?",
"answer_sw":"Ndiyo — biashara ya kuuza mazao ya kilimo na bidhaa za msingi sokoni (petty trade / market vending) iko miongoni mwa biashara zilizopigwa marufuku kwa wageni. Mgeni Mreno (au mwingine yeyote asiye raia wa Tanzania) anayeuza mboga, matunda, au bidhaa nyingine za msingi sokoni Kariakoo au mahali popote Tanzania Bara anakiuka GN 487A.",
"question_en":"A Portuguese non-citizen sells vegetables and fruits at Kariakoo market. Does this violate GN 487A?",
"answer_en":"Yes — the business of selling agricultural produce and basic goods at markets (petty trade / market vending) is among the businesses prohibited for non-citizens. A Portuguese national (or any other non-Tanzanian citizen) selling vegetables, fruits, or other basic goods at Kariakoo or anywhere in Tanzania Mainland is violating GN 487A.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_scp_019_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Biashara za kimataifa za bidhaa (import/export) pia zinakatazwa kwa wageni?",
"answer_sw":"Biashara za uagizaji na uuzaji nje (import/export) si miongoni mwa biashara 15 zilizopigwa marufuku moja kwa moja na GN 487A. GN 487A inazuia hasa biashara ndogo na za kati zinazofanywa moja kwa moja na wageni kwenye masoko ya ndani. Wageni wanaweza kwa ujumla kufanya biashara za kimataifa ikiwa wana vibali sahihi vya biashara. Hata hivyo, uuzaji wa bidhaa zilizoagizwa moja kwa moja kwa wateja wa kawaida (retail import) unaweza kuzingatiwa ukiukaji.",
"question_en":"Are international goods trade (import/export) businesses also prohibited for non-citizens?",
"answer_en":"Import and export trade is not directly among the 15 business categories explicitly prohibited by GN 487A. GN 487A specifically prohibits small and medium businesses conducted directly by non-citizens in domestic markets. Non-citizens may generally conduct international trade businesses if they have the correct business permits. However, selling imported goods directly to ordinary customers (retail import) may be considered a violation.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_scp_020_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Kwa muhtasari: GN 487A inawahusu nani, inapiga marufuku nini, na kwa eneo gani?",
"answer_sw":"Muhtasari wa GN 487A: (1) NANI inawahusu: raia wa kigeni (wageni) wote — si Watanzania; (2) NINI inapiga marufuku: makundi 15 ya biashara ikiwemo rejareja, jumla, uhamisho wa pesa za simu, ukarabati wa simu, salon, kinyozi, ushonaji, mkahawa mdogo, huduma za usafi, bidhaa za pili mkono, na mengine; (3) ENEO: Tanzania Bara tu — si Zanzibar. Ilianza: 28 Julai 2025.",
"question_en":"Summary: who does GN 487A apply to, what does it prohibit, and in which area?",
"answer_en":"GN 487A summary: (1) WHO it applies to: all foreign nationals (non-citizens) — not Tanzanians; (2) WHAT it prohibits: 15 business categories including retail, wholesale, mobile money transfers, phone repair, hair salons, barbershops, tailoring, small food outlets, cleaning services, second-hand goods trade, and others; (3) AREA: Tanzania Mainland only — not Zanzibar. Effective: 28 July 2025.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

]

OUT = "datasets/tier1a/raw_sources/raw_pairs_batch_008.jsonl"
mode = "a" if os.path.exists(OUT) else "w"
with open(OUT, mode, encoding="utf-8") as f:
    for p in pairs:
        f.write(json.dumps(p, ensure_ascii=False) + "\n")

print(f"Part 1 written: {len(pairs)} pairs to {OUT}")
regs = {}
for p in pairs:
    r = p["register"]; regs[r] = regs.get(r,0)+1
for k,v in sorted(regs.items()):
    print(f"  {k}: {v} ({v/len(pairs)*100:.0f}%)")
