#!/usr/bin/env python3
"""batch_008 part 2 — FIX 3 (10 facilitator/marriage) + FIX 4 (15 VAT professional)
+ FIX 5 (10 VAT 6-month threshold) + FIX 6 (15 VAT procedural) = 50 pairs."""
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

SRC_GN487A = "https://tanzlii.org/akn/tz/act/gn/2025/487a/eng@2025-07-28"
SRC_NAME_GN = "TanzLII - GN 487A Business Licensing (Prohibition of Business Activities for Non-Citizens) Order 2025"
SRC_VAT = "https://www.tra.go.tz/page/value-added-tax"
SRC_NAME_VAT = "TRA - Value Added Tax"
DATE = "20260612"

pairs = [

# ══════════════════════════════════════════════════════════
# FIX 3 — FACILITATOR DEFINITION + MARRIAGE (10 pairs)
# ══════════════════════════════════════════════════════════

{"id":f"b008_gn487a_fac_001_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Msaidizi (facilitator) katika GN 487A ni nani hasa — maana yake ni nini?",
"answer_sw":"'Msaidizi' (facilitator) chini ya GN 487A ni Mtanzania anayeruhusu mgeni kutumia jina lake, leseni yake, TIN yake, au usajili wake wa biashara ili mgeni aweze kufanya biashara iliyokatazwa. Mifano: kukopa jina la biashara lililosajiliwa BRELA, kuonyesha mgeni kama mfanyakazi wakati kweli ni mmiliki, au kutoa leseni ya biashara yako kwa mgeni atumie. Adhabu: hadi TZS 5M AU hadi miezi 3 jela.",
"question_en":"Who exactly is a 'facilitator' (msaidizi) under GN 487A — what does it mean?",
"answer_en":"A 'facilitator' under GN 487A is a Tanzanian who allows a non-citizen to use their name, business licence, TIN, or business registration to conduct a prohibited business. Examples: lending a BRELA-registered business name, presenting a non-citizen as an employee when they are actually the owner, or giving your business licence to a non-citizen to use. Penalty: up to TZS 5M OR up to 3 months' imprisonment.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_fac_002_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Je, kumwambia mgeni 'tumia jina langu kwenye biashara' ni msaada wa kisheria?",
"answer_sw":"Hapana — hii ni mfano wa kawaida wa 'kuwezesha' (facilitating) kwa maana ya GN 487A. Kuruhusu mgeni kutumia jina lako kusajili biashara au kuendesha biashara inayofanywa kweli na mgeni kunakufanya 'msaidizi' chini ya GN 487A. Adhabu yako kama msaidizi: hadi TZS 5,000,000 AU kifungo hadi miezi 3. Mbinu hii ya 'dawa ya siri' ni maarufu lakini ni kosa la kisheria.",
"question_en":"Is telling a non-citizen 'use my name for the business' legal assistance?",
"answer_en":"No — this is a classic example of 'facilitating' within the meaning of GN 487A. Allowing a non-citizen to use your name to register a business or run a business actually operated by a non-citizen makes you a 'facilitator' under GN 487A. Your penalty as a facilitator: up to TZS 5,000,000 OR imprisonment up to 3 months. This 'secret medicine' method is popular but is a criminal offence.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_fac_003_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Ninaoa mwanawake wa China — baada ya ndoa ninaweza kufanya biashara ya rejareja kwa haki zake za ndoa?",
"answer_sw":"Hapana — ndoa na raia wa Tanzania haibadilishi hadhi ya kisheria ya mwenza wa ndoa chini ya GN 487A. Mwanawake wa China anabaki 'mgeni' (non-citizen) hata baada ya ndoa na Mtanzania. GN 487A inaangalia URAIA wa biashara, si hali ya ndoa. Njia pekee ya kubadilisha hadhi ni kupata uraia wa Tanzania kupitia mchakato wa kisheria — si kupitia ndoa haraka.",
"question_en":"I am marrying a Chinese woman — after marriage can she conduct retail trade using her marriage rights?",
"answer_en":"No — marriage to a Tanzanian citizen does not change a spouse's legal status under GN 487A. A Chinese woman remains a 'non-citizen' even after marrying a Tanzanian. GN 487A looks at CITIZENSHIP for business, not marital status. The only way to change status is to obtain Tanzanian citizenship through the legal process — not through marriage alone.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_fac_004_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Bibi yangu ni raia wa Ufaransa, ameishi Tanzania miaka 20. Ana haki ya kufanya biashara ya rejareja?",
"answer_sw":"Kuishi Tanzania muda mrefu peke yake hakumpi mgeni haki ya kufanya biashara zilizopigwa marufuku na GN 487A. Haki ya kufanya biashara hizi inatokana na URAIA wa Tanzania — si kipindi cha makazi. Bibi yako, hata kama ana vibali vya ukaazi na anaishi Tanzania miaka 20, bado ni 'mgeni' kwa maana ya GN 487A hadi atakapopata uraia wa Tanzania rasmi.",
"question_en":"My grandmother is a French citizen who has lived in Tanzania for 20 years. Does she have the right to conduct retail trade?",
"answer_en":"Long residency in Tanzania alone does not give a non-citizen the right to conduct businesses prohibited by GN 487A. The right to conduct these businesses comes from Tanzanian CITIZENSHIP — not the length of residence. Your grandmother, even with residence permits and 20 years living in Tanzania, remains a 'non-citizen' within the meaning of GN 487A until she formally obtains Tanzanian citizenship.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_fac_005_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mtanzania anayeonyesha mgeni kama mfanyakazi wake kwenye biashara — hii ni msaada (facilitating)?",
"answer_sw":"Ndiyo — kuonyesha mgeni kama 'mfanyakazi' wakati kweli ni yeye anayeendesha au kumiliki biashara ni njia ya kawaida ya 'kuwezesha' iliyopigwa marufuku na GN 487A. Idara ya Uhamiaji na TRA wanachunguza hali kama hizi — wanaangalia ni nani anafanya maamuzi ya biashara, kupokea pesa, na kuendesha operesheni za kila siku. Udhihirisho wa kisheria (jina la kumbukumbu) si kinga dhidi ya uchunguzi.",
"question_en":"A Tanzanian shows a non-citizen as their employee in the business — is this facilitating?",
"answer_en":"Yes — presenting a non-citizen as an 'employee' when they are actually running or owning the business is a common method of 'facilitating' prohibited by GN 487A. The Immigration Department and TRA investigate such arrangements — they look at who makes business decisions, receives money, and runs daily operations. Formal appearance (name on record) is not protection against investigation.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_fac_006_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mtanzania anaomba mgeni 'changa' tu kwa ajili ya usajili — si mmiliki halisi. Hii ni tatizo?",
"answer_sw":"Ndiyo — hii ni aina nyingine ya 'kuwezesha'. Hata kama Mtanzania anasema yeye ni 'mmiliki' rasmi na mgeni ni 'mchangiaji' tu, ikiwa mgeni ndiye anayeendesha biashara halisi, ana maamuzi, na anapata faida — hali hii inachukuliwa ukiukaji wa GN 487A. Sheria inaangalia hali halisi ya biashara, si mikataba ya uwongo. Mtanzania anakuwa msaidizi na ana hatari ya adhabu.",
"question_en":"A Tanzanian asks a non-citizen to 'just contribute funds' for registration — not the real owner. Is this a problem?",
"answer_en":"Yes — this is another form of 'facilitating'. Even if a Tanzanian claims to be the formal 'owner' and the non-citizen is just a 'contributor', if the non-citizen is actually running the real business, making decisions, and receiving profits — this situation is treated as a GN 487A violation. The law looks at the real business substance, not fake contracts. The Tanzanian becomes a facilitator and faces penalty risk.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_fac_007_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Ndoa na Mtanzania inabadilisha uraia wa mgeni haraka?",
"answer_sw":"Hapana — ndoa peke yake haibadilishi uraia wa Tanzania haraka. Mchakato wa kupata uraia wa Tanzania unahusisha: maombi rasmi kwa Wizara ya Mambo ya Ndani, kipindi cha makazi ya lazima (miaka kadhaa), na idhini ya Rais wa Tanzania. Ndoa inaweza kusaidia mchakato wa kupata uraia lakini si njia ya moja kwa moja au ya haraka. Hadi uraia unapatikana rasmi, mwenza wa ndoa bado ana hadhi ya mgeni.",
"question_en":"Does marriage to a Tanzanian quickly change a non-citizen's citizenship?",
"answer_en":"No — marriage alone does not quickly change Tanzanian citizenship. The process of obtaining Tanzanian citizenship involves: a formal application to the Ministry of Home Affairs, a mandatory residency period (several years), and Presidential approval. Marriage may facilitate the citizenship process but is not a direct or quick path. Until citizenship is formally granted, the non-citizen spouse retains non-citizen status.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or citizenship law changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_fac_008_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"TIN ya Mtanzania inaweza kutumika na mgeni kufanya biashara?",
"answer_sw":"Hapana — TIN ya Mtanzania ni ya kibinafsi na haiwezi kutumika kisheria na mtu mwingine. Kutumia TIN ya mtu mwingine ni ulaghai wa kodi (tax fraud) chini ya Sheria ya Usimamizi wa Kodi na pia ni 'kuwezesha' kwa maana ya GN 487A. Mtu anayekuacha utumie TIN yake anakuwa msaidizi na ana hatari ya adhabu. TRA inachunguza TIN zinazotumika kwa biashara nyingi au zinazoonekana kutumika na watu tofauti.",
"question_en":"Can a Tanzanian's TIN be used by a non-citizen to conduct business?",
"answer_en":"No — a Tanzanian's TIN is personal and cannot legally be used by another person. Using someone else's TIN is tax fraud under the Tax Administration Act and also constitutes 'facilitating' within the meaning of GN 487A. A person who allows you to use their TIN becomes a facilitator and faces penalty risk. TRA investigates TINs used for multiple businesses or those appearing to be used by different people.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_fac_009_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mtanzania mmiliki wa biashara anaenda likizoni na kuacha mgeni aendeshe duka kwa wiki mbili. Ni shida?",
"answer_sw":"Inategemea mazingira. Mgeni akisimamia duka kwa muda mfupi kama msimamizi au mfanyakazi wa kawaida wakati mmiliki yuko mbali — hii kwa kawaida si ukiukaji mkubwa wa GN 487A. Lakini kama mgeni anafanya maamuzi ya biashara, kupokea mapato, na kuendesha biashara halisi — hata kwa wiki mbili — inaweza kuzingatiwa ukiukaji. Mmiliki Mtanzania anapaswa kuwa na mfanyakazi Mtanzania asimamie badala yake.",
"question_en":"A Tanzanian business owner goes on leave and leaves a non-citizen to run the shop for two weeks. Is this a problem?",
"answer_en":"It depends on the circumstances. A non-citizen supervising a shop briefly as a caretaker or regular employee while the owner is away — this is generally not a major GN 487A violation. But if the non-citizen is making business decisions, receiving income, and running the actual business — even for two weeks — this may be considered a violation. The Tanzanian owner should have a Tanzanian employee manage instead.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_fac_010_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mwanandoa wa kigeni ana uraia wa nchi mbili — Tanzania na nchi yake ya asili. Je, ana tatizo la GN 487A?",
"answer_sw":"Hapana — mtu mwenye uraia wa Tanzania (hata kama pia ana uraia wa nchi nyingine) hana matatizo ya GN 487A kwa biashara. GN 487A inaangalia kama mtu ni 'raia wa Tanzania' kwa maana ya BRELA, TRA, na Idara ya Uhamiaji. Mtu mwenye pasipoti ya Tanzania na TIN ya Tanzania anachukuliwa raia kwa madhumuni haya hata kama ana uraia mwingine pia.",
"question_en":"A foreign-born spouse has dual citizenship — Tanzania and their country of origin. Do they have a GN 487A problem?",
"answer_en":"No — a person with Tanzanian citizenship (even if they also hold another country's citizenship) has no GN 487A problem for business. GN 487A looks at whether a person is a 'Tanzanian citizen' in the sense recognised by BRELA, TRA, and the Immigration Department. A person with a Tanzanian passport and Tanzanian TIN is treated as a citizen for these purposes even if they also hold another citizenship.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or citizenship law changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

# ══════════════════════════════════════════════════════════
# FIX 4 — VAT PROFESSIONAL MANDATORY REGISTRATION (15 pairs)
# CPA, wakili, mhandisi, daktari, architect — ALL must
# register VAT REGARDLESS of turnover threshold.
# ══════════════════════════════════════════════════════════

{"id":f"b008_vat_pro_001_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Mimi ni CPA (Certified Public Accountant) aliyesajiliwa. Je, lazima nisajili VAT hata kama sina wateja wengi?",
"answer_sw":"NDIYO — kama CPA aliyesajiliwa chini ya sheria ya Tanzania, lazima usajili VAT BILA KUJALI kiasi cha mauzo yako. Kanuni hii inazuia fani zilizoidhinishwa (regulated professions) kama vile wahasibu walioidhinishwa, mawakili, wahandisi, madaktari, na wasanifu majengo. Kizingiti cha kawaida cha TZS 200M kwa miezi 12 kinatumika kwa biashara za kawaida — si kwa fani zilizoorodheshwa.",
"question_en":"I am a registered CPA (Certified Public Accountant). Must I register for VAT even if I have few clients?",
"answer_en":"YES — as a registered CPA under Tanzanian law, you must register for VAT REGARDLESS of the amount of your fees. This rule covers regulated professions such as certified accountants, lawyers, engineers, doctors, and architects. The standard threshold of TZS 200M per 12 months applies to ordinary businesses — not to the listed regulated professions.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing VAT registration rules for professionals","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_pro_002_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Wakili aliyesajiliwa Tanzania — ana mauzo ya TZS 50M kwa mwaka tu. Lazima asajili VAT?",
"answer_sw":"NDIYO — wakili aliyesajiliwa (advocate) lazima asajili VAT bila kujali kiasi cha mauzo yake. Hata kama ana mauzo ya TZS 50M, TZS 10M, au hata hakuna mauzo yoyote bado — usajili wa VAT ni sharti la kufanya kazi kama wakili aliyeidhinishwa. Hii ni tofauti na biashara ya kawaida ambayo inahitaji kufikia kizingiti cha TZS 200M kwanza.",
"question_en":"A registered advocate in Tanzania — their annual fees are only TZS 50M. Must they register for VAT?",
"answer_en":"YES — a registered advocate must register for VAT regardless of the amount of their fees. Even if they earn TZS 50M, TZS 10M, or even zero fees yet — VAT registration is a requirement for practising as a licensed advocate. This differs from ordinary businesses which need to reach the TZS 200M threshold first.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing VAT registration rules for professionals","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_pro_003_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Mhandisi aliyepewa leseni ya kufanya kazi Tanzania — kizingiti cha TZS 200M kinamhusu?",
"answer_sw":"Hapana — kizingiti cha TZS 200M kwa miezi 12 ni kwa biashara za kawaida, si kwa mhandisi aliyeidhinishwa (registered engineer). Mhandisi lazima asajili VAT kama sehemu ya mahitaji ya kufanya kazi kisheria Tanzania. TRA imeweka sharti hili kwa fani zinazohitaji leseni maalum za kitaalamu kwa sababu huduma zao zinazalisha mapato makubwa na zinapaswa kuwa katika mfumo wa kodi.",
"question_en":"A licensed engineer in Tanzania — does the TZS 200M threshold apply to them?",
"answer_en":"No — the TZS 200M per 12-month threshold is for ordinary businesses, not for a registered engineer. An engineer must register for VAT as part of the requirements to practise legally in Tanzania. TRA has set this requirement for professions requiring special professional licences because their services generate significant revenue and should be within the tax system.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing VAT rules for professionals","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_pro_004_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Daktari binafsi aliyefungua kliniki ndogo — anahitaji kusajili VAT kuanzia siku ya kwanza?",
"answer_sw":"NDIYO — daktari aliyesajiliwa (registered medical practitioner) anahitaji kusajili VAT kama sehemu ya mahitaji ya kufanya mazoezi ya dawa Tanzania, bila kujali ukubwa wa kliniki au idadi ya wagonjwa. Hata kama kliniki ni ndogo na ana wagonjwa wachache — usajili wa VAT ni lazima. Fani za afya zinaonekana kama fani zilizoidhinishwa zinazohitaji usajili wa VAT mara moja.",
"question_en":"A private doctor who has opened a small clinic — do they need to register for VAT from day one?",
"answer_en":"YES — a registered medical practitioner needs to register for VAT as part of the requirements to practise medicine in Tanzania, regardless of the clinic size or number of patients. Even if the clinic is small and has few patients — VAT registration is mandatory. Medical professions are treated as regulated professions requiring immediate VAT registration.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_pro_005_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Msanifu majengo (architect) mpya — anaweza kusubiri hadi mauzo yake yafike TZS 200M kwanza?",
"answer_sw":"Hapana — msanifu majengo aliyesajiliwa (registered architect) hawezi kusubiri kizingiti cha TZS 200M. Kama daktari, wakili, na mhandisi, msanifu majengo lazima asajili VAT kama sehemu ya mahitaji ya kupata na kudumisha leseni yake ya kitaalamu. Kutosajili VAT wakati ukiendesha biashara ya kitaalamu kama msanifu majengo aliyeidhinishwa ni ukiukaji wa sheria ya kodi.",
"question_en":"A new architect — can they wait until their fees reach TZS 200M first?",
"answer_en":"No — a registered architect cannot wait for the TZS 200M threshold. Like doctors, lawyers, and engineers, an architect must register for VAT as part of the requirements to obtain and maintain their professional licence. Failing to register for VAT while operating as a licensed professional architect is a violation of tax law.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_pro_006_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Kwa nini fani kama wakili, CPA, mhandisi wanahitajika kusajili VAT bila kujali mauzo — mantiki yake ni nini?",
"answer_sw":"TRA imeweka kanuni hii kwa sababu fani zinazodhibitiwa na sheria zinatoa huduma maalum zinazolipa vizuri na zinazohitaji ufuatiliaji wa kodi. Hoja kuu: (1) fani hizi zinadhibitiwa na bodi za kitaalamu (NBAA kwa wahasibu, Tanganyika Law Society kwa mawakili, nk) — usajili wa VAT ni sehemu ya ufuatiliaji; (2) wateja wao mara nyingi wanaweza kudai input VAT — mfumo wa VAT unahitaji msajili upande wa pili; (3) mapato yao yanaweza kuwa makubwa hata kama wateja ni wachache.",
"question_en":"Why must professions like lawyers, CPAs, engineers register for VAT regardless of fees — what is the reasoning?",
"answer_en":"TRA has set this rule because professionally regulated occupations provide specialised high-value services requiring tax monitoring. Key reasons: (1) these professions are regulated by professional boards (NBAA for accountants, Tanganyika Law Society for lawyers, etc.) — VAT registration is part of compliance monitoring; (2) their clients can often claim input VAT — the system needs a registered party on the supply side; (3) their revenue may be high even with few clients.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_pro_007_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"CPA wangu alisema hakuhitaji kusajili VAT kwa sababu ana wateja wachache. Anasema ukweli?",
"answer_sw":"Hapana — CPA wako ana kosa. Kama CPA aliyesajiliwa na NBAA Tanzania, anahitajika kusajili VAT BILA KUJALI idadi ya wateja au kiasi cha mapato. Kizingiti cha TZS 200M kinachukulia biashara za kawaida — si fani zilizodhibitiwa kama uhasibu wa kitaalamu. CPA asiyesajili VAT anaweza kukabiliwa na adhabu za kodi na kupoteza leseni yake ya kitaalamu.",
"question_en":"My CPA told me they don't need to register for VAT because they have few clients. Is that true?",
"answer_en":"No — your CPA is mistaken. As a CPA registered with NBAA Tanzania, they are required to register for VAT REGARDLESS of the number of clients or amount of income. The TZS 200M threshold is for ordinary businesses — not for regulated professions like professional accounting. A CPA who fails to register for VAT may face tax penalties and risk losing their professional licence.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_pro_008_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Ni fani zipi hasa ambazo lazima zisajili VAT bila kujali mauzo chini ya sheria ya Tanzania?",
"answer_sw":"Fani kuu zinazohitajika kusajili VAT bila kujali mauzo ni: (1) Mawakili (advocates) walioidhinishwa na Tanganyika Law Society; (2) Wahasibu na wakaguzi (CPA/auditors) walioidhinishwa na NBAA; (3) Wahandisi walioidhinishwa na Engineers Registration Board (ERB); (4) Wasanifu majengo walioidhinishwa na Architects and Quantity Surveyors Registration Board; (5) Madaktari walioidhinishwa na Medical Council. Orodha kamili inapatikana kutoka TRA moja kwa moja.",
"question_en":"Which professions specifically must register for VAT regardless of turnover under Tanzanian law?",
"answer_en":"The main professions required to register for VAT regardless of turnover are: (1) Advocates licensed by the Tanganyika Law Society; (2) Accountants and auditors (CPA/auditors) licensed by NBAA; (3) Engineers licensed by the Engineers Registration Board (ERB); (4) Architects licensed by the Architects and Quantity Surveyors Registration Board; (5) Doctors licensed by the Medical Council. A complete list is available directly from TRA.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment or TRA update to professional VAT list","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_pro_009_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Daktari anasema: 'Huduma za afya zimesamehewa VAT — kwa hivyo sijasajilishwa.' Je, hoja hii ni sahihi?",
"answer_sw":"Hoja hii ina nuance muhimu. Kweli fulani: huduma za afya za msingi (basic health services) zinaweza kuwa exempt au zero-rated kwa VAT. Lakini: hii haimaanishi daktari hauhitaji KUSAJILIWA VAT. Hata kama huduma zako ziko exempt, unastahili kusajiliwa kama fani iliyodhibitiwa. Pia, si huduma zote za madaktari ni exempt — huduma za kibinafsi za hali ya juu, huduma za urembo, na zingine zinaweza kuwa taxable.",
"question_en":"A doctor says: 'Health services are VAT-exempt — so I have not registered.' Is this argument correct?",
"answer_en":"This argument has an important nuance. Partly true: basic health services may be exempt or zero-rated for VAT. But: this does not mean a doctor does not need to BE REGISTERED for VAT. Even if your services are exempt, you are still required to register as a regulated profession. Also, not all doctors' services are exempt — high-end private services, cosmetic services, and others may be taxable.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_pro_010_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Ninaendesha biashara ya ushauri wa IT (IT consulting) — si fani iliyodhibitiwa. Je, lazima nisajili VAT?",
"answer_sw":"Kwa IT consultant asiye na leseni ya fani iliyodhibitiwa, kizingiti cha kawaida cha TZS 200M kwa miezi 12 kinatumika. Huhitajiki kusajili VAT mpaka mauzo yako yafike kizingiti hiki. Hata hivyo: kama una leseni ya uhandisi wa programu (software engineering) kutoka ERB au leseni nyingine ya kitaalamu, kanuni ya fani zinazodhibitiwa inaweza kutumika. Thibitisha hali yako maalum na TRA.",
"question_en":"I run an IT consulting business — it is not a regulated profession. Must I register for VAT?",
"answer_en":"For an IT consultant without a regulated professional licence, the standard threshold of TZS 200M per 12 months applies. You are not required to register for VAT until your sales reach this threshold. However: if you hold a software engineering licence from ERB or another professional licence, the regulated profession rule may apply. Confirm your specific situation with TRA.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_vat_pro_011_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Wakili mpya aliyeidhinishwa leo — anaweza kuanza kufanya kazi bila kusajili VAT kwanza?",
"answer_sw":"Hapana — wakili aliyeidhinishwa hivi karibuni anapaswa kusajili VAT kama sehemu ya mahitaji ya kuweza kufanya mazoezi ya kisheria Tanzania. Ni vizuri kusajili VAT KABLA au WAKATI wa kuanza mazoezi — si baadaye. Kusimamia wateja bila usajili wa VAT unapoishia linapaswa kulipa inaweza kusababisha adhabu za kodi na matatizo na Tanganyika Law Society.",
"question_en":"A newly admitted advocate today — can they start practising without first registering for VAT?",
"answer_en":"No — a newly admitted advocate should register for VAT as part of the requirements to practise law in Tanzania. It is advisable to register for VAT BEFORE or AT THE TIME of starting practice — not later. Managing clients without VAT registration when you should be registered may result in tax penalties and complications with the Tanganyika Law Society.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_pro_012_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Mhandisi ana ofisi ya kibinafsi na pia ana kazi ya mshahara serikalini. Je, anahitaji kusajili VAT kwa ofisi yake binafsi?",
"answer_sw":"Ndiyo — hata kama mhandisi ana kazi ya mshahara serikalini, ofisi yake ya kibinafsi (consultancy) inastahili usajili wa VAT kwa sababu ana leseni ya kitaalamu ya ERB. Shughuli mbili tofauti: kazi ya mshahara (kodi inazingatiwa na mwajiri) na ofisi binafsi (lazima asimamie mwenyewe kodi ikiwa ni pamoja na VAT). Mapato yote ya ofisi binafsi lazima yaorodheshwe kwa TRA.",
"question_en":"An engineer has a private office and also salaried government employment. Do they need to register for VAT for their private office?",
"answer_en":"Yes — even if an engineer is salaried in government, their private office (consultancy) requires VAT registration because they hold an ERB professional licence. Two separate activities: salaried employment (tax managed by employer) and private office (must manage own taxes including VAT). All private office income must be declared to TRA.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_pro_013_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"CPA aliyestaafu kazi bado ana leseni yake ya NBAA. Anahitaji kudumisha usajili wa VAT?",
"answer_sw":"Kama CPA aliyestaafu bado ana leseni hai ya NBAA na bado anafanya kazi yoyote ya uhasibu au ukaguzi — hata kwa wateja wachache — usajili wa VAT bado unatumika. Kama amestaafu kabisa na HAJAFANYI biashara yoyote ya kitaalamu, anaweza kuomba TRA kufuta usajili wake wa VAT kwa mujibu wa taratibu sahihi. Hata hivyo, kuwa na leseni inayoendelea bila kufanya kazi mara nyingi si tatizo la VAT — tatizo linatokea ukifanya kazi bila usajili.",
"question_en":"A retired CPA still holds their active NBAA licence. Do they need to maintain VAT registration?",
"answer_en":"If a retired CPA still holds an active NBAA licence and is still doing any accounting or auditing work — even for a few clients — VAT registration still applies. If fully retired and NOT conducting any professional business, they may apply to TRA to deregister their VAT following proper procedures. However, holding a continuing licence while not working is generally not a VAT problem — the problem arises if working without registration.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_pro_014_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Biashara yangu ya kawaida (duka la nguo) haijafika TZS 200M. Lakini pia mimi ni CPA. Je, lazima nisajili VAT?",
"answer_sw":"Ndiyo — kama CPA aliyesajiliwa, lazima usajili VAT kwa biashara ZOTE unazofanya, ikiwa ni pamoja na duka lako la nguo. Leseni yako ya CPA inakufanya 'fani inayodhibitiwa' ambayo inahitaji usajili wa VAT bila kujali mauzo. Hata kama ungekuwa tu mfanyabiashara wa nguo bila leseni ya CPA, ungepaswa pia kusajili VAT ukifikia kizingiti cha TZS 200M. Kwa hali yako, usajili ni wa lazima haraka.",
"question_en":"My ordinary business (clothing shop) has not reached TZS 200M. But I am also a CPA. Must I register for VAT?",
"answer_en":"Yes — as a registered CPA, you must register for VAT for ALL your businesses including your clothing shop. Your CPA licence makes you a 'regulated profession' requiring VAT registration regardless of sales volume. Even if you were just a clothing trader without a CPA licence, you would need to register for VAT once reaching the TZS 200M threshold. In your situation, registration is immediately mandatory.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_pro_015_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Kwa muhtasari: biashara ya kawaida VS fani iliyodhibitiwa — tofauti yao katika VAT ni nini?",
"answer_sw":"Tofauti kuu: BIASHARA YA KAWAIDA — usajili wa VAT ni wa lazima tu ukifika kizingiti cha TZS 200M kwa miezi 12 au TZS 100M kwa miezi 6. FANI ZILIZODHIBITIWA (wakili, CPA, mhandisi, daktari, msanifu majengo) — usajili wa VAT ni wa lazima MARA MOJA ukipata leseni ya kitaalamu, bila kujali mauzo. Hakuna kizingiti cha mauzo kwa fani zilizodhibitiwa — zinahitaji kusajiliwa mapema.",
"question_en":"Summary: ordinary business VS regulated profession — what is the difference for VAT?",
"answer_en":"Key difference: ORDINARY BUSINESS — VAT registration is mandatory only when reaching TZS 200M per 12 months or TZS 100M per 6 months threshold. REGULATED PROFESSIONS (lawyer, CPA, engineer, doctor, architect) — VAT registration is mandatory IMMEDIATELY upon obtaining a professional licence, regardless of income. There is no income threshold for regulated professions — they must register early.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

# ══════════════════════════════════════════════════════════
# FIX 5 — VAT 6-MONTH THRESHOLD (10 pairs)
# TZS 100M in any 6 months = mandatory registration.
# EITHER 12-month OR 6-month triggers independently.
# ══════════════════════════════════════════════════════════

{"id":f"b008_vat_thr_001_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Kizingiti cha VAT cha miezi 6 ni TZS ngapi — ni sawa na kizingiti cha miezi 12?",
"answer_sw":"Hapana — viwango ni tofauti. Kizingiti cha miezi 12: TZS 200,000,000 (milioni 200). Kizingiti cha miezi 6: TZS 100,000,000 (milioni 100) tu. Si kizingiti kimoja cha TZS 200M kinachotumika kwa njia zote mbili. Kizingiti cha miezi 6 ni nusu ya cha miezi 12. Kila kimoja kinafanya kazi kwa njia yake: ukizidi MOJA tu kati ya viwango hivi viwili, usajili wa VAT ni wa lazima mara moja.",
"question_en":"What is the 6-month VAT threshold — is it the same as the 12-month threshold?",
"answer_en":"No — the thresholds are different. 12-month threshold: TZS 200,000,000 (200 million). 6-month threshold: TZS 100,000,000 (100 million) only. It is not one threshold of TZS 200M applied in both ways. The 6-month threshold is half of the 12-month one. Each works independently: if you exceed EITHER ONE of these two thresholds, VAT registration is immediately mandatory.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing VAT registration thresholds","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_thr_002_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Mauzo yangu ni TZS 110M katika miezi 6 lakini TZS 160M kwa miezi 12. Je, lazima nisajili VAT?",
"answer_sw":"NDIYO — lazima usajili VAT. Hata kama mauzo ya miezi 12 (TZS 160M) hayajafika kizingiti cha TZS 200M, mauzo yako ya miezi 6 (TZS 110M) yamezidi kizingiti cha TZS 100M. Viwango viwili vinafanya kazi kwa UHURU — kuzidi kimoja kimoja kunafanya usajili kuwa wa lazima mara moja. Katika hali yako, kizingiti cha miezi 6 kimezidiwa — usajili wa VAT ni wa lazima leo.",
"question_en":"My sales are TZS 110M in 6 months but TZS 160M over 12 months. Must I register for VAT?",
"answer_en":"YES — you must register for VAT. Even if the 12-month sales (TZS 160M) have not reached the TZS 200M threshold, your 6-month sales (TZS 110M) have exceeded the TZS 100M threshold. The two thresholds work INDEPENDENTLY — exceeding either one individually makes registration immediately mandatory. In your situation the 6-month threshold has been exceeded — VAT registration is mandatory today.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_thr_003_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Je, kizingiti cha miezi 6 cha TZS 100M kinatumika kwa miezi sita MAALUM (Jan-Jun) au kipindi chochote?",
"answer_sw":"Kizingiti cha miezi 6 kinatumika kwa KIPINDI CHOCHOTE cha miezi 6 mfululizo — si kwa miezi sita maalum ya mwaka. Hii inamaanisha TRA inaangalia mauzo yako katika kipindi cha kuzunguka (rolling 6-month period). Mauzo ya miezi Januari-Juni, Februari-Julai, Machi-Agosti — yote yanachaguliwa. Ukizidi TZS 100M katika kipindi chochote cha miezi 6, usajili ni wa lazima.",
"question_en":"Does the 6-month TZS 100M threshold apply to SPECIFIC months (Jan-Jun) or any 6-month period?",
"answer_en":"The 6-month threshold applies to ANY consecutive 6-month period — not specific calendar months. This means TRA looks at your sales in a rolling 6-month period. Sales for January-June, February-July, March-August — all are considered. If you exceed TZS 100M in any 6-month period at all, registration is mandatory.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_thr_004_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Rafiki yangu alisema kizingiti cha VAT cha miezi 6 pia ni TZS 200M — kweli au uwongo?",
"answer_sw":"UWONGO — rafiki yako ana kosa. Kizingiti cha miezi 6 ni TZS 100,000,000 (milioni MIA), si TZS 200M. Kizingiti cha TZS 200M ni cha miezi 12 tu. Makosa kama haya yanaweza kusababisha biashara nyingi kukosa usajili wa VAT waliotakiwa — TRA inaweza kutoza adhabu za kodi na faida kwa kipindi chote ambacho biashara ilikimbia usajili.",
"question_en":"My friend said the 6-month VAT threshold is also TZS 200M — true or false?",
"answer_en":"FALSE — your friend is mistaken. The 6-month threshold is TZS 100,000,000 (one hundred million), not TZS 200M. The TZS 200M threshold applies only to the 12-month period. Errors like this can cause many businesses to miss required VAT registration — TRA may charge tax penalties and interest for the entire period during which the business evaded registration.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_thr_005_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Kwa muhtasari: viwango vya VAT Tanzania ni vipi?",
"answer_sw":"Viwango VYA LAZIMA (mandatory) vya usajili wa VAT Tanzania: (1) TZS 200,000,000 katika KIPINDI CHOCHOTE cha miezi 12 mfululizo; AU (2) TZS 100,000,000 katika KIPINDI CHOCHOTE cha miezi 6 mfululizo. Moja tu ya viwango hivi kuzidiwa kunafanya usajili kuwa wa lazima mara moja. Fani zilizodhibitiwa (wakili, CPA, nk) lazima zisajilishwe mara moja bila kujali mauzo. Pia: unaweza kusajili VAT kwa hiari hata kama hujafika viwango hivi.",
"question_en":"Summary: what are Tanzania's VAT registration thresholds?",
"answer_en":"MANDATORY VAT registration thresholds in Tanzania: (1) TZS 200,000,000 in ANY consecutive 12-month period; OR (2) TZS 100,000,000 in ANY consecutive 6-month period. Exceeding either one of these thresholds alone makes registration immediately mandatory. Regulated professions (lawyers, CPAs, etc.) must register immediately regardless of sales. Also: you may voluntarily register for VAT even if you have not reached these thresholds.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_thr_006_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Nilikuwa na mauzo ya TZS 90M kwa miezi 6 na TZS 185M kwa miezi 12. Je, ninahitaji kusajili VAT?",
"answer_sw":"Hapana — bado haujafika kizingiti. Mauzo ya TZS 90M kwa miezi 6 ni chini ya kizingiti cha TZS 100M cha miezi 6. Mauzo ya TZS 185M kwa miezi 12 ni chini ya kizingiti cha TZS 200M cha miezi 12. Viwango vyote viwili havijazidiwa — kwa hivyo usajili wa VAT wa lazima haujafika. Hata hivyo, angalia kipindi kinachofuata — ukiwa karibu na viwango, zingatia usajili wa hiari au panga vizuri.",
"question_en":"I had sales of TZS 90M over 6 months and TZS 185M over 12 months. Do I need to register for VAT?",
"answer_en":"No — you have not yet reached either threshold. Sales of TZS 90M over 6 months are below the TZS 100M 6-month threshold. Sales of TZS 185M over 12 months are below the TZS 200M 12-month threshold. Neither threshold has been exceeded — so mandatory VAT registration has not been triggered. However, watch the next period — if you are close, consider voluntary registration or careful planning.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_thr_007_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Mauzo yangu yalifika TZS 201M kwa miezi 12 — hatua yangu ya kwanza ni nini?",
"answer_sw":"Hatua ya KWANZA mara moja: WASILIANA NA TRA na anza mchakato wa usajili wa VAT. Usiendelee kufanya biashara bila VAT ukisha kuzidi kizingiti — kila siku ya kuchelewa ni siku ya kukiuka sheria. TRA inaweza kutoza adhabu za VAT yote iliyopaswa kulipwa tangu ulipozidi kizingiti, pamoja na faida ya kuchelewa. Usisubiri mwisho wa mwezi au mwaka — hatua ya kwanza ni kuwasiliana na TRA MARA MOJA.",
"question_en":"My sales have reached TZS 201M over 12 months — what is my first step?",
"answer_en":"Your FIRST step immediately: CONTACT TRA and start the VAT registration process. Do not continue trading without VAT once you have exceeded the threshold — every day of delay is a day of violating the law. TRA may charge penalties for all VAT that should have been paid since you crossed the threshold, plus late payment interest. Do not wait until end of month or year — the first step is to contact TRA IMMEDIATELY.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_thr_008_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Biashara yangu ina msimu wa biashara (seasonal business) — mauzo yangu ya majira ya kiangazi ni TZS 130M kwa miezi 4. Je, lazima nisajili VAT?",
"answer_sw":"Hata kama ni biashara ya msimu, ukizidi TZS 100M katika kipindi chochote cha miezi 6 — au TZS 200M katika kipindi chochote cha miezi 12 — usajili wa VAT ni wa lazima. Mauzo ya TZS 130M kwa miezi 4 ni mauzo ya haraka sana. Angalia kama katika kipindi chochote cha miezi 6 unaathiriwa na msimu huo mauzo yanazidi TZS 100M — kama ndivyo, usajili ni wa lazima. Msimu wa biashara haukuepusha na sheria ya VAT.",
"question_en":"My business is seasonal — my summer sales are TZS 130M over 4 months. Must I register for VAT?",
"answer_en":"Even if it is a seasonal business, if you exceed TZS 100M in any 6-month period — or TZS 200M in any 12-month period — VAT registration is mandatory. Sales of TZS 130M over 4 months is a very high rate. Check whether in any 6-month period affected by that season the sales exceed TZS 100M — if so, registration is mandatory. Seasonal trading does not exempt you from VAT law.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_thr_009_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Ninashiriki mauzo pamoja na mwangu (joint business) — mauzo ya kila mmoja wetu yanashughulikiwa tofauti kwa VAT?",
"answer_sw":"Inategemea muundo wa kisheria wa biashara. Kama mnafanya kazi kama biashara MOJA iliyosajiliwa pamoja — mauzo yanaunganishwa na kizingiti kinahesabiwa kwa biashara nzima. Kama kila mmoja ana biashara YAKE iliyosajiliwa tofauti (kwa TIN tofauti) — kizingiti kinachaguliwa kwa kila biashara tofauti. Mgawanyo bandia wa biashara moja kuepuka VAT ni haramu — TRA inaweza kuunganisha biashara kama ikiamua mfumo wa mgawanyo ni wa kubuni.",
"question_en":"I share a business with my son (joint business) — are each of our sales treated separately for VAT?",
"answer_en":"It depends on the legal structure of the business. If you operate as ONE jointly registered business — sales are combined and the threshold is calculated for the whole business. If each has their OWN separately registered business (with different TINs) — the threshold is assessed for each business separately. Artificial splitting of one business to avoid VAT is illegal — TRA may consolidate businesses if it determines the split is fabricated.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_vat_thr_010_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Kuna viwango VIWILI vya usajili wa VAT Tanzania — taja vyote viwili kwa usahihi.",
"answer_sw":"Viwango VYA LAZIMA vya usajili wa VAT Tanzania ni viwili: (1) Kizingiti cha MIEZI 12: mauzo yanayozidi TZS 200,000,000 katika kipindi chochote cha miezi 12 mfululizo; (2) Kizingiti cha MIEZI 6: mauzo yanayozidi TZS 100,000,000 katika kipindi chochote cha miezi 6 mfululizo. Kama kizingiti KIMOJA tu kati ya hivi viwili kimezidiwa, usajili wa VAT ni wa lazima mara moja — huhitajiki kuzidi vyote viwili.",
"question_en":"There are TWO VAT registration thresholds in Tanzania — state both accurately.",
"answer_en":"Tanzania's TWO mandatory VAT registration thresholds are: (1) 12-MONTH threshold: sales exceeding TZS 200,000,000 in any consecutive 12-month period; (2) 6-MONTH threshold: sales exceeding TZS 100,000,000 in any consecutive 6-month period. If EITHER ONE of these thresholds is exceeded, VAT registration is immediately mandatory — you do not need to exceed both.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing VAT registration thresholds","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

# ══════════════════════════════════════════════════════════
# FIX 6 — VAT PROCEDURAL GAPS (15 pairs)
# - Exempt = NO input VAT recovery (hard rule)
# - Unregistered CANNOT charge VAT on invoices
# - Qualifying buyer = government bodies + designated agents
# - Exceeded threshold: FIRST step = contact TRA for registration
# ══════════════════════════════════════════════════════════

{"id":f"b008_vat_prc_001_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Biashara yangu inatoa huduma za exempt (zisizo na VAT). Je, naweza kudai mkopo wa VAT ya pembejeo?",
"answer_sw":"HAPANA — hii ni kanuni ngumu bila ubaguzi. Ukitoa huduma au bidhaa za EXEMPT, huwezi kudai mkopo wa VAT ya pembejeo (input VAT) inayohusiana na huduma hizo. Hii ndiyo tofauti kuu kati ya exempt na zero-rated: zero-rated = unalipishwa VAT 0% LAKINI unaweza kudai input VAT; exempt = haulipishwi VAT NA huwezi kudai input VAT. Kwa biashara za exempt, gharama za VAT za pembejeo ni gharama za biashara — hazirudi.",
"question_en":"My business provides exempt (non-VAT) services. Can I claim input VAT credits?",
"answer_en":"NO — this is a hard rule with no exceptions. If you supply EXEMPT services or goods, you cannot claim input VAT credits related to those exempt supplies. This is the key difference between exempt and zero-rated: zero-rated = you charge 0% VAT AND you can claim input VAT; exempt = you do not charge VAT AND you cannot claim input VAT. For exempt businesses, input VAT costs are business expenses — they do not come back.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing exempt supply rules","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_prc_002_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Ninafanya biashara ya exempt — 'kwa ujumla' naweza kudai input VAT au si?",
"answer_sw":"Hapana — si 'kwa ujumla' bali KAMWE. Kanuni ya exempt haibadiliki: kama biashara yako ina asili ya exempt, huwezi kudai input VAT inayohusiana na biashara hiyo. Lugha ya hedging kama 'kwa ujumla' au 'inategemea hali' si sahihi kwa kanuni hii — ni kanuni ngumu (hard rule) ya sheria ya VAT Tanzania. Ikiwa una biashara zote mbili (exempt na taxable), unaweza kudai input VAT ya sehemu ya taxable tu — si ya sehemu ya exempt.",
"question_en":"I run an exempt business — 'in general' can I claim input VAT or not?",
"answer_en":"No — not 'in general' but NEVER. The exempt rule does not change: if your business is exempt in nature, you cannot claim input VAT related to that business. Hedging language like 'in general' or 'it depends on the situation' is not accurate for this rule — it is a hard rule in Tanzanian VAT law. If you have both (exempt and taxable) activities, you may claim input VAT for the taxable portion only — not for the exempt portion.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_prc_003_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Biashara yangu haijasajiliwa VAT — lakini ninaweka VAT ya 18% kwenye invoice zangu kwa sababu wateja wanauliza. Je, hii inaruhusiwa?",
"answer_sw":"HAPANA — hii ni kinyume kabisa cha sheria. Ni biashara zilizosajiliwa VAT TU ambazo zinaruhusiwa kukusanya VAT na kuitoa kwenye invoice. Biashara isiyosajiliwa VAT inayoweka VAT kwenye invoice inafanya vitendo viwili visivyo halali: (1) inakusanya pesa ambazo si yake kisheria na si zake kwa wateja; (2) inaweza kutoa 'input VAT credit ya uwongo' kwa wateja wanaotaka kudai mkopo. TRA inaweza kushtaki biashara kama hiyo na kutoza adhabu kali.",
"question_en":"My business is not VAT registered — but I put 18% VAT on my invoices because clients ask for it. Is this permitted?",
"answer_en":"NO — this is completely against the law. Only VAT-REGISTERED businesses are permitted to charge VAT and show it on invoices. An unregistered business putting VAT on invoices commits two unlawful acts: (1) it is collecting money it is not legally entitled to from clients; (2) it may be issuing 'false input VAT credits' to clients who want to claim credits. TRA may prosecute such a business and impose severe penalties.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_prc_004_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"'Mnunuzi anayehitimu' (qualifying buyer) kwa VAT withholding ni nani hasa — ni mtu yeyote aliyesajili VAT?",
"answer_sw":"Hapana — 'mnunuzi anayehitimu' (qualifying buyer) si mtu yeyote aliyesajili VAT. Qualifying buyer ni: (a) Wizara za Serikali na taasisi za serikali; (b) taasisi zinazohifadhi mapato yake mwenyewe (self-accounting entities); au (c) mtu aliyeteuliwa rasmi na Kamishna Mkuu wa TRA kama wakala wa zuio la VAT (designated VAT withholding agent). Kampuni ya kawaida iliyosajili VAT si qualifying buyer — haiwezi kuzuia VAT ya wasambazaji wake bila uteuzi maalum wa TRA.",
"question_en":"Who exactly is a 'qualifying buyer' for VAT withholding — is it anyone who has registered for VAT?",
"answer_en":"No — a 'qualifying buyer' is not anyone who has registered for VAT. A qualifying buyer is: (a) Government ministries and government institutions; (b) self-accounting entities; or (c) a person formally designated by the TRA Commissioner General as a designated VAT withholding agent. An ordinary company that has registered for VAT is NOT a qualifying buyer — it cannot withhold VAT from its suppliers without a specific TRA designation.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing qualifying buyer definition","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_prc_005_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Je, serikali ya mtaa (manispaa) inaweza kuzuia VAT kwenye malipo yake kwa wasambazaji?",
"answer_sw":"NDIYO — serikali za mitaa, manispaa, na taasisi za serikali zote ni 'qualifying buyers' ambazo zinaweza kuzuia VAT. Zinazuia: (a) asilimia 3 ya VAT kwenye malipo ya bidhaa, au (b) asilimia 6 ya VAT kwenye malipo ya huduma. Serikali au taasisi lazima itoe hati ya zuio la VAT kwa msambazaji siku ambayo VAT inastahili kulipwa — si tarehe ya 20 ya mwezi.",
"question_en":"Can a local government (municipality) withhold VAT from its payments to suppliers?",
"answer_en":"YES — local governments, municipalities, and all government institutions are 'qualifying buyers' that can withhold VAT. They withhold: (a) 3% VAT on goods payments, or (b) 6% VAT on services payments. The government or institution must issue a VAT withholding certificate to the supplier on the day the VAT becomes payable — not on the 20th of the month.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_prc_006_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Nilizidi kizingiti cha VAT wiki hii — hatua ya KWANZA ninayopaswa kuchukua ni nini?",
"answer_sw":"Hatua ya KWANZA ni KUWASILIANA NA TRA MARA MOJA na kuomba usajili wa VAT. Usiendelee kufanya biashara bila VAT baada ya kuzidi kizingiti — hii ni ukiukaji wa sheria ya kodi. USIFANYE: (1) usiwasilishe 'return ya mwisho' (final VAT return) — hii ni ya usimamizi wa VAT uliopo, si ya kuanza usajili mpya; (2) usisubiri mwezi mzima au mwaka — muda wa kuchelewa ni gharama ya adhabu. Nenda TRA leo.",
"question_en":"I exceeded the VAT threshold this week — what is the FIRST step I should take?",
"answer_en":"The FIRST step is to CONTACT TRA IMMEDIATELY and apply for VAT registration. Do not continue trading without VAT after exceeding the threshold — this is a tax law violation. DO NOT: (1) do not submit a 'final VAT return' — that is for winding up an existing VAT registration, not starting a new one; (2) do not wait a full month or year — delay time is penalty cost. Go to TRA today.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_prc_007_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Baada ya kuzidi kizingiti cha VAT, ninaweza kuendelea kufanya biashara wakati wa kusubiri TRA kunisajili?",
"answer_sw":"Unaweza kuendelea na biashara LAKINI lazima uanze kutunza kumbukumbu za mauzo yako vizuri kuanzia siku uliyozidi kizingiti. Kwa vitendo: huwezi kukusanya VAT rasmi kutoka kwa wateja mpaka usajili ukamilike — lakini unastahili kufanya hivyo baada ya usajili. TRA inaweza kukuambia ulipe VAT ya kipindi chote tangu ulipozidi kizingiti hata kabla ya usajili rasmi. Inashauriwa: funga mauzo mapya mpya baada ya kusajilishwa.",
"question_en":"After exceeding the VAT threshold, can I continue trading while waiting for TRA to register me?",
"answer_en":"You may continue trading BUT you must start keeping careful sales records from the day you exceeded the threshold. Practically: you cannot formally collect VAT from customers until registration is complete — but you should do so after registration. TRA may ask you to pay VAT for the entire period since you exceeded the threshold even before formal registration. Advisable: apply proper VAT from the date of registration.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_prc_008_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Adhabu ya biashara isiyosajiliwa VAT inayokusanya VAT ni nini?",
"answer_sw":"Biashara isiyosajiliwa inayokusanya VAT inaweza kukabiliwa na adhabu kama vile: (1) kurudisha VAT yote iliyokusanywa kwa TRA bila kupewa mkopo wowote wa pembejeo; (2) faini za kodi za ziada kwa ukiukaji wa makusudi; (3) kuzuiwa kwa biashara hadi kusajilishwa. Pia: wateja waliodai input VAT kutoka biashara isiyosajiliwa wanaweza kukabiliwa na marekebisho ya kodi — TRA inaweza kukataa madai yao.",
"question_en":"What is the penalty for an unregistered business that collects VAT?",
"answer_en":"An unregistered business collecting VAT may face penalties such as: (1) remitting all collected VAT to TRA without receiving any input VAT credit; (2) additional tax penalties for deliberate violation; (3) business closure until registration. Also: customers who claimed input VAT from the unregistered business may face tax assessments — TRA may reject their claims.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_prc_009_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Wakati wa VAT withholding — TRA inasema hati ya zuio lazima itolewa 'tarehe ya 20'. Ni kweli?",
"answer_sw":"HAPANA — hii ni kosa maarufu. Hati ya zuio la VAT (VAT withholding certificate) lazima itolewa SIKU AMBAYO VAT INASTAHILI KULIPWA — si tarehe ya 20. Tarehe ya 20 ni tarehe ya kuwasilisha RETURN ya VAT na kulipa VAT — hii ni wajibu tofauti kabisa. Zuio la VAT na utoaji wa hati lazima ufanyike wakati wa malipo au siku VAT inastahili — si mwezi mzima baadaye.",
"question_en":"For VAT withholding — TRA says the withholding certificate must be issued by 'the 20th'. Is this correct?",
"answer_en":"NO — this is a common error. A VAT withholding certificate must be issued on THE DAY THE VAT BECOMES PAYABLE — not the 20th. The 20th is the date for submitting the VAT RETURN and paying VAT — this is a completely separate obligation. VAT withholding and certificate issuance must happen at the time of payment or when VAT becomes due — not a full month later.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_vat_prc_010_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Tofauti kati ya tarehe ya 20 (VAT return) na tarehe ya hati ya zuio la VAT?",
"answer_sw":"Tarehe MBILI tofauti: (1) TAREHE YA 20 ya kila mwezi: hii ni mwisho wa kuwasilisha return ya VAT (VAT return) na kulipa VAT unayodaiwa. Inahusu biashara yoyote iliyosajiliwa VAT. (2) TAREHE YA KUTOA HATI YA ZUIO: hii ni siku ambayo VAT inastahili kulipwa — si mwishoni mwa mwezi. Inahusu manunuzi anayehitimu (qualifying buyer) anayezuia VAT. Kufanya kazi kama qualifying buyer na kutoa hati tarehe ya 20 ni kuchelewa — lazima itolewa mara tu wakati wa zuio.",
"question_en":"What is the difference between the 20th (VAT return) and the VAT withholding certificate date?",
"answer_en":"TWO different dates: (1) THE 20TH of each month: this is the deadline for submitting a VAT return and paying the VAT owed. It applies to any VAT-registered business. (2) VAT WITHHOLDING CERTIFICATE DATE: this is the day the VAT becomes payable — not at month end. It applies to a qualifying buyer who withholds VAT. Operating as a qualifying buyer and issuing certificates on the 20th is late — they must be issued immediately at the time of withholding.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_vat_prc_011_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Ninajua biashara yangu itafika kizingiti cha VAT mwezi ujao. Ninaweza kusajili leo kabla ya kufika?",
"answer_sw":"Ndiyo — unaweza kusajili VAT kwa HIARI kabla ya kufika kizingiti. Hii inaitwa usajili wa hiari (voluntary registration). Faida: unaweza kuanza kudai mkopo wa VAT ya pembejeo mara moja, na wateja wako wa biashara wanaweza kudai input VAT kutoka kwa mahesabu yako. Usajili wa hiari unakufanya uanze kupeleka return ya kila mwezi na kukusanya VAT tangu tarehe ya usajili — si kipindi cha nyuma.",
"question_en":"I know my business will reach the VAT threshold next month. Can I register today before reaching it?",
"answer_en":"Yes — you can register for VAT VOLUNTARILY before reaching the threshold. This is called voluntary registration. Benefit: you can start claiming input VAT credits immediately, and your business clients can claim input VAT from your invoices. Voluntary registration means you start submitting monthly returns and collecting VAT from the registration date — not for any past period.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_prc_012_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Biashara yangu ina mauzo ya taxable NA ya exempt pamoja. Ninaweza kudai input VAT yote?",
"answer_sw":"Unaweza kudai input VAT ya SEHEMU YA TAXABLE tu. Kwa biashara zenye mchanganyiko wa taxable na exempt, TRA inatumia kanuni ya 'partial attribution' — unagawanya input VAT kulingana na uwiano wa mauzo ya taxable kwa mauzo yote. Mfano: kama 70% ya mauzo ni taxable na 30% exempt, unaweza kudai 70% ya input VAT yako tu. Sehemu ya 30% inayohusiana na mauzo ya exempt hairejeshwi.",
"question_en":"My business has both taxable AND exempt sales. Can I claim all input VAT?",
"answer_en":"You can claim input VAT for the TAXABLE PORTION only. For businesses with a mix of taxable and exempt supplies, TRA applies a 'partial attribution' rule — you apportion input VAT based on the ratio of taxable sales to total sales. Example: if 70% of sales are taxable and 30% exempt, you may claim 70% of your input VAT only. The 30% portion related to exempt supplies is not refunded.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_prc_013_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Ninaweza kukataa ombi la mteja kuzuia VAT kwenye invoice yangu?",
"answer_sw":"Inategemea hali ya mteja wako. Kama mteja ni 'qualifying buyer' (serikali, taasisi ya serikali, au wakala aliyeteuliwa na TRA) — hana chaguo: wana wajibu wa kisheria wa kuzuia VAT. Huwezi kuwakatalia kisheria kuzuia VAT wanapostahili kufanya hivyo. Kama mteja ni kampuni ya kawaida isiyokuwa 'qualifying buyer' — hawana haki ya kuzuia VAT na unaomba kwamba walipe VAT kamili.",
"question_en":"Can I refuse a client's request to withhold VAT on my invoice?",
"answer_en":"It depends on your client's status. If the client is a 'qualifying buyer' (government, government institution, or TRA-designated agent) — there is no choice: they have a legal obligation to withhold VAT. You cannot legally prevent them from withholding VAT when they are required to do so. If the client is an ordinary company that is not a 'qualifying buyer' — they have no right to withhold VAT and you should ask them to pay VAT in full.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_prc_014_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"TRA inazuia VAT gani kwa malipo ya bidhaa na kwa malipo ya huduma?",
"answer_sw":"VAT withholding ya Tanzania (Finance Act 2025, kuanza Julai 2025): BIDHAA — asilimia 3 ya VAT inazuiwa; HUDUMA — asilimia 6 ya VAT inazuiwa. Tofauti: kiwango cha bidhaa (3%) ni nusu ya kiwango cha huduma (6%). Kumbuka: hizi si viwango vya VAT vyenyewe (ambayo ni 18%) — ni sehemu tu ya VAT inayozuiwa na qualifying buyer kabla ya kufikia msambazaji.",
"question_en":"What VAT withholding rate does TRA apply to goods payments and services payments?",
"answer_en":"Tanzania VAT withholding (Finance Act 2025, effective July 2025): GOODS — 3% VAT is withheld; SERVICES — 6% VAT is withheld. The difference: the goods rate (3%) is half the services rate (6%). Note: these are not the VAT rates themselves (which are 18%) — they are only the portion of VAT withheld by the qualifying buyer before it reaches the supplier.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing VAT withholding rates","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_vat_prc_015_{DATE}","domain":"tier1a","subdomain":"vat_registration",
"question_sw":"Kwa muhtasari — kanuni ngumu tatu za VAT ambazo kila mfanyabiashara lazima azijue.",
"answer_sw":"Kanuni tatu ngumu (hard rules) za VAT Tanzania: (1) EXEMPT = HAKUNA input VAT — ukitoa huduma/bidhaa za exempt, huwezi kudai input VAT inayohusiana nazo, bila ubaguzi; (2) USAJILI WA LAZIMA MARA MOJA — ukizidi kizingiti cha TZS 200M/miezi 12 au TZS 100M/miezi 6, wasiliana na TRA leo — usichelewesha; (3) BIASHARA ISIYOSAJILIWA HAIKUSANYI VAT — ni kinyume cha sheria kuweka VAT kwenye invoice kama hujasajiliwa.",
"question_en":"Summary — three hard VAT rules every business person must know.",
"answer_en":"Three hard rules of Tanzanian VAT: (1) EXEMPT = NO input VAT — if you supply exempt services/goods, you cannot claim related input VAT, no exceptions; (2) MANDATORY IMMEDIATE REGISTRATION — if you exceed TZS 200M/12 months or TZS 100M/6 months threshold, contact TRA today — do not delay; (3) UNREGISTERED BUSINESS DOES NOT CHARGE VAT — it is against the law to put VAT on invoices if you are not registered.",
"primary_source_url":SRC_VAT,"primary_source_name":SRC_NAME_VAT,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

]

OUT = "datasets/tier1a/raw_sources/raw_pairs_batch_008.jsonl"
with open(OUT, "a", encoding="utf-8") as f:
    for p in pairs:
        f.write(json.dumps(p, ensure_ascii=False) + "\n")

print(f"Part 2 written: {len(pairs)} pairs appended to {OUT}")
regs = {}
for p in pairs:
    r = p["register"]; regs[r] = regs.get(r,0)+1
for k,v in sorted(regs.items()):
    print(f"  {k}: {v} ({v/len(pairs)*100:.0f}%)")
