#!/usr/bin/env python3
"""batch_008 part 3 — FIX 7 (20 refusals) + FIX 8 (15 PAYE) + FIX 9 (15 GN487A depth) = 50 pairs."""
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

SRC_GN487A = "https://tanzlii.org/akn/tz/act/gn/2025/487a/eng@2025-07-28"
SRC_NAME_GN = "TanzLII - GN 487A Business Licensing (Prohibition of Business Activities for Non-Citizens) Order 2025"
SRC_PAYE = "https://www.tra.go.tz/page/pay-as-you-earn-paye"
SRC_NAME_PAYE = "TRA - Pay As You Earn (PAYE)"
SRC_TRA = "https://www.tra.go.tz/index.php/tax-information"
SRC_NAME_TRA = "TRA - Tax Information"
DATE = "20260612"

REFUSAL_SW = "Mada hii iko nje ya mipaka yangu ya sasa. Thibitisha na TRA au mshauri wa kodi aliyehitimu."
REFUSAL_EN = "This topic is outside my current coverage. Please verify with TRA or a qualified tax adviser."

pairs = [

# ══════════════════════════════════════════════════════════
# FIX 7 — OUT-OF-CORPUS REFUSALS (20 pairs)
# ══════════════════════════════════════════════════════════

{"id":f"b008_refusal_001_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Mfanyakazi wangu ana mshahara wa TZS 800,000 kwa mwezi — PAYE yake ni kiasi gani?",
"answer_sw":f"Siwezi kukuhesabia PAYE ya mshahara mahususi — hii inahitaji hisabati ya kesi kwa kesi ambayo inategemea makato mengine (NSSF, hifadhi ya mazingira, nk). {REFUSAL_SW} Kwa mahesabu sahihi: tumia kikokotoo cha TRA IDRAS (taidras.tra.go.tz) ambacho kinajumuisha mazingira yote. Ninajua viwango vya PAYE (bendi 1: 0%; bendi 2: 8%; bendi 3: 20%; bendi 4: 25%; bendi 5: 30%; punguzo la kibinafsi TZS 26,000) lakini mahesabu ya kibinafsi ni kazi ya TRA IDRAS.",
"question_en":"My employee earns TZS 800,000 per month — how much is their PAYE?",
"answer_en":f"I cannot calculate PAYE for a specific salary — this requires case-by-case arithmetic that depends on other deductions (NSSF, etc.). {REFUSAL_EN} For accurate calculations: use the TRA IDRAS calculator (taidras.tra.go.tz) which accounts for all factors. I know the PAYE bands (band 1: 0%; band 2: 8%; band 3: 20%; band 4: 25%; band 5: 30%; personal relief TZS 26,000) but individual calculations are work for TRA IDRAS.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing PAYE bands","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_002_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Mshahara wa TZS 1,200,000 — PAYE halisi ni ngapi?",
"answer_sw":f"Mahesabu ya PAYE ya mshahara mahususi yako nje ya mipaka yangu. {REFUSAL_SW} Tumia kikokotoo cha TRA IDRAS (taidras.tra.go.tz) kwa jibu sahihi. Ninaweza kukuambia kwamba mshahara wa TZS 1.2M unaathiriwa na bendi nyingi za PAYE lakini punguzo la kibinafsi la TZS 26,000/mwezi litapunguza kiasi. Mhesabu wa kodi au kikokotoo cha TRA IDRAS ndiyo chanzo sahihi.",
"question_en":"Salary of TZS 1,200,000 — what is the exact PAYE?",
"answer_en":f"Calculating PAYE for a specific salary is outside my coverage. {REFUSAL_EN} Use the TRA IDRAS calculator (taidras.tra.go.tz) for an accurate answer. I can tell you that a TZS 1.2M salary is affected by multiple PAYE bands but the personal relief of TZS 26,000/month will reduce the amount. A tax accountant or the TRA IDRAS calculator is the accurate source.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_003_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Niliuza ardhi yangu kwa TZS 80M — capital gains tax (kodi ya mapato ya mtaji) ni kiasi gani?",
"answer_sw":f"Kodi ya mapato ya mtaji (capital gains tax) kwenye ardhi ni mada ngumu inayohitaji maarifa ya kina ya sheria ya mapato ya Tanzania — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Suala hili linahusisha: thamani ya ununuzi wa awali, muda wa umiliki, aina ya ardhi (title deed vs hati nyingine), na msamaha wa kisheria unaowezekana. Muona wakili au mhesabu wa kodi aliyehitimu.",
"question_en":"I sold my land for TZS 80M — how much is the capital gains tax?",
"answer_en":f"Capital gains tax on land is a complex topic requiring detailed knowledge of Tanzanian income tax law — this is outside my current coverage. {REFUSAL_EN} This matter involves: the original purchase value, ownership period, type of land documentation, and possible legal exemptions. Consult a qualified lawyer or tax accountant.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment on capital gains","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_004_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Niliuza nyumba yangu kwa faida ya TZS 30M — je, kuna kodi ya mtaji?",
"answer_sw":f"Mauzo ya mali isiyohamishika (real property) na kodi inayohusiana yanazidi mipaka yangu ya sasa. {REFUSAL_SW} Mauzo ya nyumba yanaweza kuathiriwa na sheria ya Mapato ya Watu Binafsi — hali inategemea nyumba hiyo ilitumika kwa nini (makazi ya msingi au uwekezaji), muda wa umiliki, na mambo mengine. Wasiliana na mhesabu wa kodi aliyehitimu au TRA moja kwa moja.",
"question_en":"I sold my house at a profit of TZS 30M — is there a capital gains tax?",
"answer_en":f"Property sales and related taxation are beyond my current coverage. {REFUSAL_EN} House sale tax may be affected by the Personal Income Tax Act — the situation depends on how the property was used (primary residence or investment), ownership period, and other factors. Contact a qualified tax accountant or TRA directly.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment on capital gains","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_005_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Nilinunua Bitcoin kwa TZS 2M na kuiuza kwa TZS 5M — ni kodi gani ninastahili kulipa?",
"answer_sw":f"Ushuru wa mapato ya cryptocurrency (Bitcoin, USDT, nk) ni mada inayohitaji uelewa wa hivi karibuni wa miongozo ya TRA — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Tanzania bado inaendelea kuweka sera yake ya kodi ya cryptocurrency. Muona TRA moja kwa moja au mhesabu wa kodi aliyehitimu kwa mwongozo wa hivi karibuni. Epuka kutoa maelezo ya kodi yanayoweza kukusababishia matatizo ya kisheria.",
"question_en":"I bought Bitcoin for TZS 2M and sold it for TZS 5M — what tax do I owe?",
"answer_en":f"Tax on cryptocurrency income (Bitcoin, USDT, etc.) requires current knowledge of TRA guidelines — this is outside my current coverage. {REFUSAL_EN} Tanzania is still developing its cryptocurrency tax policy. Consult TRA directly or a qualified tax accountant for the most current guidance. Avoid acting on tax advice that could cause you legal problems.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"TRA cryptocurrency tax policy publication","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_006_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Kampuni yangu mama iko India na inanisaidia kwa mkopo wa hisa. Mahitaji ya bei ya uhamisho (transfer pricing) Tanzania ni yapi?",
"answer_sw":f"Bei ya uhamisho (transfer pricing) kwa miamala ya kimataifa baina ya makampuni yanayohusiana ni mada ya kina inayohitaji ujuzi maalum — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Tanzania ina mwongozo wa transfer pricing ndani ya Sheria ya Mapato lakini matumizi yake kwa hali yako mahususi yanahitaji uchambuzi wa kina. Muona mhesabu wa kodi wa kimataifa aliyehitimu.",
"question_en":"My parent company is in India and supports me with a related-party loan. What are Tanzania's transfer pricing requirements?",
"answer_en":f"Transfer pricing for international transactions between related companies is a deep specialist topic — this is outside my current coverage. {REFUSAL_EN} Tanzania has transfer pricing guidance within the Income Tax Act but its application to your specific situation requires detailed analysis. Consult a qualified international tax accountant.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"TRA transfer pricing guideline updates","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_007_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Tanzania ina mkataba wa kuzuia kodi mara mbili (double taxation treaty) na India — inaathiri nini biashara yangu?",
"answer_sw":f"Mikataba ya kuzuia kodi mara mbili (double taxation treaties) ni eneo la kisheria la kimataifa linaloenda zaidi ya mipaka yangu ya sasa. {REFUSAL_SW} Tanzania ina mikataba kadhaa na nchi mbalimbali. Athari kwa biashara yako mahususi inategemea muundo wako wa kimataifa na aina ya mapato. Muona wakili wa kodi ya kimataifa au mhesabu wa kodi aliyehitimu.",
"question_en":"Tanzania has a double taxation treaty with India — how does it affect my business?",
"answer_en":f"Double taxation treaties are an international legal area that goes beyond my current coverage. {REFUSAL_EN} Tanzania has several treaties with various countries. The effect on your specific business depends on your international structure and income types. Consult an international tax lawyer or qualified tax accountant.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Tanzania double taxation treaty updates","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_008_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Shirika la madini linanipa mrabaha (royalty) — kiwango cha kodi ya mrabaha ni kiasi gani?",
"answer_sw":f"Kodi ya mrabaha wa madini (mining royalties) ni eneo maalum la uchumi wa madini Tanzania — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Viwango vya mrabaha vya madini vinasimamiwa na Sheria ya Madini na vinatofautiana kulingana na aina ya madini (dhahabu, almasi, makaa ya mawe, nk). Muona mhesabu wa kodi aliyebobea katika sekta ya madini au Wizara ya Madini Tanzania moja kwa moja.",
"question_en":"A mining company is giving me royalties — what is the royalty tax rate?",
"answer_en":f"Mining royalty tax is a specialised area of Tanzania's mining economy — this is outside my current coverage. {REFUSAL_EN} Mining royalty rates are governed by the Mining Act and vary depending on the type of mineral (gold, diamonds, coal, etc.). Consult a tax accountant specialised in the mining sector or the Tanzania Ministry of Minerals directly.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Mining Act or Finance Act amendment on royalty rates","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_009_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Kampuni yangu ya bima — kiwango cha ushuru wa malipo ya bima (insurance premium levy) Tanzania ni kiasi gani?",
"answer_sw":f"Ushuru wa malipo ya bima (insurance premium levy) ni eneo la Mamlaka ya Udhibiti wa Bima Tanzania (TIRA) na sheria za bima — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Kiwango cha ushuru na mahitaji yake yanategemea aina ya bima (maisha, gari, afya, nk). Wasiliana na TIRA (tira.go.tz) au mhesabu wa kodi aliyebobea katika sekta ya bima.",
"question_en":"My insurance company — what is the insurance premium levy rate in Tanzania?",
"answer_en":f"Insurance premium levy falls under the Tanzania Insurance Regulatory Authority (TIRA) and insurance laws — this is outside my current coverage. {REFUSAL_EN} The levy rate and requirements depend on the type of insurance (life, motor, health, etc.). Contact TIRA (tira.go.tz) or a tax accountant specialised in the insurance sector.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"TIRA insurance levy rate changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_010_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Thamani ya ardhi yangu inakadiriwa vipi kwa ajili ya stamp duty Tanzania?",
"answer_sw":f"Mbinu ya kukadiri thamani ya ardhi kwa ajili ya stamp duty inahitaji ujuzi wa kitaalamu wa tathmini ya mali — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Ninajua kwamba stamp duty inahesabiwa kwenye thamani ya soko ya mali lakini njia ya kufikia thamani hiyo (tathmini rasmi, njia ya soko, tathmini ya serikali) inahitaji mtaalam wa mali isiyohamishika (registered valuer) au mshauri wa kisheria.",
"question_en":"How is the value of my land assessed for stamp duty purposes in Tanzania?",
"answer_en":f"The methodology for valuing land for stamp duty requires specialist property valuation expertise — this is outside my current coverage. {REFUSAL_EN} I know that stamp duty is calculated on the market value of property but the way to arrive at that value (formal valuation, market approach, government assessment) requires a registered property valuer or legal adviser.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Stamp duty legislation changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_011_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Kodi ya forodha (customs duty) kwa kuagiza simu 100 kutoka China ni kiasi gani?",
"answer_sw":f"Viwango vya ushuru wa forodha (customs duty) kwa bidhaa maalum vinasimamiwa na Tanzania Revenue Authority — Idara ya Forodha na Kenya/EAC tariff schedules — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Viwango vinatofautiana kulingana na HS code ya bidhaa, nchi ya asili, na makubaliano ya kikanda (EAC). Wasiliana na TRA — Idara ya Forodha au mwingizi wa forodha (clearing agent) aliyehitimu.",
"question_en":"How much customs duty applies to importing 100 mobile phones from China?",
"answer_en":f"Customs duty rates for specific goods are governed by Tanzania Revenue Authority — Customs Department and EAC tariff schedules — this is outside my current coverage. {REFUSAL_EN} Rates vary depending on the HS code of the goods, country of origin, and regional agreements (EAC). Contact TRA — Customs Department or a licensed clearing agent.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"EAC or national customs tariff changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_012_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Mfuko wangu wa pensheni (pension fund) — kodi yake inakuwaje wakati wa kustaafu?",
"answer_sw":f"Ushuru wa mafao ya pensheni na mifuko ya pensheni wakati wa kustaafu ni eneo maalum la sheria ya jamii na kodi — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Kodi ya mafao ya pensheni inategemea mfuko (NSSF, PSPF, GEPF, nk), aina ya malipo (mkupuo au malipo ya kila mwezi), na sheria inayosimamia mfuko huo. Wasiliana na msimamizi wa mfuko wako au mhesabu wa kodi aliyehitimu.",
"question_en":"My pension fund — how is it taxed when I retire?",
"answer_en":f"Taxation of pension benefits and pension funds at retirement is a specialised area of social security and tax law — this is outside my current coverage. {REFUSAL_EN} Pension benefit taxation depends on the fund (NSSF, PSPF, GEPF, etc.), type of payment (lump sum or monthly), and the law governing that fund. Contact your fund administrator or a qualified tax accountant.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Pension fund or income tax legislation changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_013_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Sheria ya Tanzania inasema nini kuhusu ushuru wa kupindukia (excise duty) kwa vinywaji baridi?",
"answer_sw":f"Ushuru wa kupindukia (excise duty) kwa vinywaji na bidhaa nyingine maalum ni eneo la sheria ya Excise Duty na Finance Act ambalo linaenda zaidi ya mipaka yangu ya sasa. {REFUSAL_SW} Viwango vya excise duty hasa kwa vinywaji baridi, pombe, sigara, nk vinaweza kubadilika kila mwaka na Finance Act. Wasiliana na TRA — Idara ya Kodi za Ndani au angalia Finance Act ya hivi karibuni.",
"question_en":"What does Tanzanian law say about excise duty on soft drinks?",
"answer_en":f"Excise duty on beverages and other specific goods is an area of Excise Duty law and the Finance Act that goes beyond my current coverage. {REFUSAL_EN} Excise duty rates specifically for soft drinks, alcohol, cigarettes, etc. may change annually with the Finance Act. Contact TRA — Domestic Revenue Department or check the latest Finance Act.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment on excise duty rates","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_014_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Ninataka kufanya uwekezaji wa hisa kwenye DSE (Dar es Salaam Stock Exchange) — kodi ya gawio (dividend) ni kiasi gani?",
"answer_sw":f"Kodi ya gawio (dividend withholding tax) kwa hisa za DSE na uwekezaji wa DSE kwa ujumla ni eneo linaloenda zaidi ya mipaka yangu ya sasa. {REFUSAL_SW} Ninajua kwamba Tanzania ina kodi ya zuio kwa gawio lakini kiwango kinachofaa kwa hali yako (raia wa Tanzania, mgeni, mtu binafsi, kampuni) kinatofautiana. Wasiliana na brokers wa DSE, TRA, au mhesabu wa uwekezaji aliyehitimu.",
"question_en":"I want to invest in shares on the DSE — how much is the dividend tax?",
"answer_en":f"Dividend withholding tax on DSE shares and DSE investment generally is beyond my current coverage. {REFUSAL_EN} I know Tanzania has a withholding tax on dividends but the applicable rate for your situation (Tanzanian citizen, non-citizen, individual, company) varies. Contact DSE brokers, TRA, or a qualified investment accountant.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment on dividend WHT rates","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_015_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Ninauza mchanga na mawe kwa ajili ya ujenzi — kuna kodi maalum ya rasilimali za ardhi?",
"answer_sw":f"Kodi na tozo zinazohusiana na uchimbaji na uuzaji wa rasilimali za ardhi (mchanga, mawe, kokoto) ni eneo la kisheria la madini na mazingira — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Shughuli hizi zinasimamiwa na Wizara ya Madini, NEMC (National Environment Management Council), na serikali za mitaa ambazo zinaweza kutoza ada na ushuru maalum. Wasiliana na mamlaka hizi moja kwa moja.",
"question_en":"I sell sand and stones for construction — is there a special natural resources tax?",
"answer_en":f"Taxes and levies related to extraction and sale of natural resources (sand, stones, gravel) are a legal area of mining and environment law — this is outside my current coverage. {REFUSAL_EN} These activities are regulated by the Ministry of Minerals, NEMC (National Environment Management Council), and local governments which may charge special fees and levies. Contact these authorities directly.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Mining or natural resources regulation changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_016_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Serikali ya Kenya inazuia nini kwa wafanyabiashara wa Tanzania wanaouza Kenya?",
"answer_sw":f"Sheria za biashara na kodi za Kenya ziko nje ya mipaka yangu kabisa — ninashughulikia Tanzania Bara tu. {REFUSAL_SW} Kwa maswali ya biashara nchini Kenya: wasiliana na Kenya Revenue Authority (KRA) au biashara.go.ke. Ninaweza kukusaidia kuhusu mahitaji ya Tanzania kwa bidhaa zinazotoka Tanzania kwenda Kenya (kama export procedures, EAC STR, nk).",
"question_en":"What does the Kenyan government restrict for Tanzanian traders selling in Kenya?",
"answer_en":f"Kenyan trade laws and taxes are completely outside my scope — I cover Tanzania Mainland only. {REFUSAL_EN} For Kenya business questions: contact Kenya Revenue Authority (KRA) or biashara.go.ke. I can help you with Tanzania-side requirements for goods moving from Tanzania to Kenya (such as export procedures, EAC STR, etc.).",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Not applicable — Kenya out of scope","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_017_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Kodi za Zanzibar ziko sawa na Tanzania Bara — ninaweza kutumia TIN moja kwa biashara zangu zote?",
"answer_sw":f"Zanzibar ina mfumo wake wa kodi na usimamizi tofauti na Tanzania Bara — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Zanzibar ina Mamlaka ya Mapato ya Zanzibar (ZRB) tofauti na TRA ya Tanzania Bara. Suala la TIN na umoja wake kati ya mifumo miwili linahitaji ufafanuzi kutoka TRA na ZRB moja kwa moja.",
"question_en":"Are Zanzibar taxes the same as Tanzania Mainland — can I use one TIN for all my businesses?",
"answer_en":f"Zanzibar has its own tax system and administration different from Tanzania Mainland — this is outside my current coverage. {REFUSAL_EN} Zanzibar has the Zanzibar Revenue Board (ZRB) separate from Tanzania Mainland's TRA. The question of TIN and its unity between the two systems requires clarification from TRA and ZRB directly.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Zanzibar-Mainland tax harmonisation changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_018_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Mshahara wa TZS 520,000 hasa — PAYE ni ngapi kwa mujibu wa bendi za kodi?",
"answer_sw":f"Mahesabu ya PAYE ya mshahara mahususi yako nje ya mipaka yangu — hii ni huduma ya TRA IDRAS. {REFUSAL_SW} Ninaweza kukuambia kwamba TZS 520,000 iko mwisho wa bendi ya pili (ambayo ni asilimia 8 — si asilimia 9) lakini mahesabu kamili yanajumuisha punguzo la kibinafsi la TZS 26,000/mwezi na hali nyingine za kibinafsi. Tumia kikokotoo cha TRA IDRAS (taidras.tra.go.tz) kwa jibu sahihi.",
"question_en":"Salary of exactly TZS 520,000 — how much is the PAYE according to the tax bands?",
"answer_en":f"Calculating PAYE for a specific salary is outside my coverage — this is a TRA IDRAS service. {REFUSAL_EN} I can tell you that TZS 520,000 sits at the top of the second band (which is 8% — not 9%) but a full calculation includes the personal relief of TZS 26,000/month and other personal circumstances. Use the TRA IDRAS calculator (taidras.tra.go.tz) for an accurate answer.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing PAYE bands","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_019_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Ninafanya kazi nje ya nchi (UK) na kupata mshahara hapo — lazima nilipe PAYE Tanzania?",
"answer_sw":f"PAYE ya mapato ya watu wanaoishi au kufanya kazi nje ya Tanzania ni eneo ngumu la sheria ya mapato ya kimataifa — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Suala hili linahusisha hali ya makazi ya kodi (tax residency), mikataba ya kuzuia kodi mara mbili, na sheria ya ndani ya Tanzania. Muona mhesabu wa kodi wa kimataifa aliyehitimu.",
"question_en":"I work abroad (UK) and earn a salary there — must I pay PAYE in Tanzania?",
"answer_en":f"PAYE on income for people living or working outside Tanzania is a complex area of international income tax law — this is outside my current coverage. {REFUSAL_EN} This issue involves tax residency status, double taxation treaties, and Tanzania's domestic law. Consult a qualified international tax accountant.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Income Tax Act changes or treaty updates","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_refusal_020_{DATE}","domain":"tier1a","subdomain":"out_of_corpus_refusal",
"question_sw":"Kodi ya watu binafsi kwa mapato ya uvuvi (fishing income) Tanzania ni kiasi gani?",
"answer_sw":f"Kodi ya mapato ya uvuvi na sekta ya samaki ni eneo maalum la sheria ya mapato — hii iko nje ya mipaka yangu ya sasa. {REFUSAL_SW} Sekta ya uvuvi inaweza kuathiriwa na msamaha maalum wa kodi, ushuru wa sekta, na sheria za uvuvi Tanzania. Wasiliana na TRA moja kwa moja au Wizara ya Mifugo na Uvuvi kwa mwongozo uliofaa.",
"question_en":"What is the personal income tax rate on fishing income in Tanzania?",
"answer_en":f"Income tax on fishing and the fisheries sector is a specialised area of tax law — this is outside my current coverage. {REFUSAL_EN} The fisheries sector may be affected by special tax exemptions, sector levies, and Tanzanian fishing laws. Contact TRA directly or the Ministry of Livestock and Fisheries for appropriate guidance.",
"primary_source_url":SRC_TRA,"primary_source_name":SRC_NAME_TRA,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Income Tax Act or fisheries law changes","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"out_of_corpus_refusal","eval_set":False},

# ══════════════════════════════════════════════════════════
# FIX 8 — PAYE BAND 2 REINFORCEMENT (15 pairs)
# Band 2 is 8% NOT 9%.
# All 5 bands stated correctly in every pair.
# ══════════════════════════════════════════════════════════

{"id":f"b008_paye_adv_001_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Bendi ya pili ya PAYE Tanzania ni asilimia 9 — ni kweli?",
"answer_sw":"UWONGO — bendi ya pili ya PAYE ni asilimia 8, si 9. Bendi zote tano za PAYE kwa kipindi cha 2025/2026: Bendi 1: TZS 0-270,000 = 0%; Bendi 2: TZS 270,001-520,000 = 8%; Bendi 3: TZS 520,001-760,000 = 20%; Bendi 4: TZS 760,001-1,000,000 = 25%; Bendi 5: Zaidi ya TZS 1,000,000 = 30%. Punguzo la kibinafsi: TZS 26,000/mwezi. Kumbuka: bendi ya 2 ni 8% — si 9% — kosa hili ni la kawaida.",
"question_en":"The second PAYE band in Tanzania is 9% — is this true?",
"answer_en":"FALSE — the second PAYE band is 8%, not 9%. All five PAYE bands for 2025/2026: Band 1: TZS 0-270,000 = 0%; Band 2: TZS 270,001-520,000 = 8%; Band 3: TZS 520,001-760,000 = 20%; Band 4: TZS 760,001-1,000,000 = 25%; Band 5: Above TZS 1,000,000 = 30%. Personal relief: TZS 26,000/month. Remember: band 2 is 8% — not 9% — this error is very common.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing PAYE bands","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_paye_adv_002_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Bendi za PAYE za Tanzania kwa mwaka 2025/2026 ni zipi — zitaje zote tano kwa usahihi?",
"answer_sw":"Bendi tano za PAYE Tanzania 2025/2026: (1) TZS 0 hadi 270,000: kiwango 0%; (2) TZS 270,001 hadi 520,000: kiwango 8% (si 9%); (3) TZS 520,001 hadi 760,000: kiwango 20%; (4) TZS 760,001 hadi 1,000,000: kiwango 25%; (5) Zaidi ya TZS 1,000,000: kiwango 30%. Punguzo la kibinafsi la kila mwezi: TZS 26,000. Kodi inazingatiwa kwenye KIPATO KINACHOPITA kizingiti cha kila bendi — si kwenye mshahara wote.",
"question_en":"What are Tanzania's PAYE bands for 2025/2026 — list all five accurately?",
"answer_en":"Five PAYE bands for Tanzania 2025/2026: (1) TZS 0 to 270,000: rate 0%; (2) TZS 270,001 to 520,000: rate 8% (not 9%); (3) TZS 520,001 to 760,000: rate 20%; (4) TZS 760,001 to 1,000,000: rate 25%; (5) Above TZS 1,000,000: rate 30%. Monthly personal relief: TZS 26,000. Tax applies to income ABOVE each band threshold — not on the total salary.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing PAYE bands","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_paye_adv_003_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Mhesabu wangu alisema bendi ya 2 ya PAYE ni asilimia 9. Je, ana haki?",
"answer_sw":"Hapana — mhesabu wako ana kosa. Bendi ya pili ya PAYE Tanzania ni asilimia 8 (si 9). Kosa hili la asilimia 9 linaonekana mara kwa mara katika mifumo ya kuandikia mishahara ya zamani na vitabu vya kodi visivyosasishwa. Kiwango sahihi: TZS 270,001-520,000 = 8%. Ikiwa mhesabu wako anatumia 9%, mfanyakazi wako analipa PAYE zaidi ya inayostahili — unastahili kurekebisha mfumo wako wa mishahara.",
"question_en":"My accountant said PAYE band 2 is 9%. Are they correct?",
"answer_en":"No — your accountant is mistaken. The second PAYE band in Tanzania is 8% (not 9%). This 9% error appears frequently in outdated payroll systems and uncorrected tax references. The correct rate: TZS 270,001-520,000 = 8%. If your accountant is using 9%, your employees are paying more PAYE than they should — you should correct your payroll system.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_paye_adv_004_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"PAYE inafanya kazi vipi — inatumika kwenye mshahara wote au kwa bendi?",
"answer_sw":"PAYE inafanya kazi KWA BENDI (progressive taxation) — si kwenye mshahara wote kwa kiwango kimoja. Mfano wa mshahara wa TZS 600,000: Bendi 1 (0-270,000): TZS 0 kodi; Bendi 2 (270,001-520,000): TZS 250,000 × 8% = TZS 20,000; Bendi 3 (520,001-600,000): TZS 80,000 × 20% = TZS 16,000; Jumla ya PAYE kabla ya punguzo: TZS 36,000; Punguzo la kibinafsi: TZS 26,000; PAYE ya kulipa: TZS 10,000. Tafadhali tumia TRA IDRAS kwa mahesabu sahihi ya mshahara wako.",
"question_en":"How does PAYE work — does it apply to the full salary or by band?",
"answer_en":"PAYE works BY BAND (progressive taxation) — not on the full salary at one rate. Example for TZS 600,000 salary: Band 1 (0-270,000): TZS 0 tax; Band 2 (270,001-520,000): TZS 250,000 × 8% = TZS 20,000; Band 3 (520,001-600,000): TZS 80,000 × 20% = TZS 16,000; Total PAYE before relief: TZS 36,000; Personal relief: TZS 26,000; PAYE to pay: TZS 10,000. Please use TRA IDRAS for accurate calculations for your specific salary.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_paye_adv_005_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Punguzo la kibinafsi la PAYE Tanzania ni TZS ngapi kwa mwezi?",
"answer_sw":"Punguzo la kibinafsi (personal relief) la PAYE Tanzania ni TZS 26,000 kwa mwezi. Punguzo hili linapunguzwa kutoka PAYE iliyohesabiwa kwa kutumia bendi zote. Mfano: kama bendi za PAYE zinatolea TZS 20,000 lakini punguzo ni TZS 26,000 — PAYE ya kulipa ni TZS 0 (punguzo linafunika PAYE yote). Punguzo hili ni la kiotomatiki kwa kila mfanyakazi — mwajiri haombi.",
"question_en":"What is Tanzania's personal relief for PAYE per month?",
"answer_en":"The personal relief (personal relief) for PAYE Tanzania is TZS 26,000 per month. This relief is subtracted from PAYE calculated using all bands. Example: if PAYE bands produce TZS 20,000 but relief is TZS 26,000 — PAYE payable is TZS 0 (the relief covers all the PAYE). This relief is automatic for every employee — the employer does not need to apply for it.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing personal relief","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_paye_adv_006_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Wafanyakazi walio na mshahara chini ya TZS 270,000 kwa mwezi wanalipa PAYE?",
"answer_sw":"Hapana — wafanyakazi wenye mshahara wa TZS 270,000 au chini wako katika bendi ya kwanza ya PAYE ambayo ina kiwango cha 0%. Hawalipi PAYE yoyote. Mwajiri bado ana wajibu wa kuweka kumbukumbu za mishahara hii na kuwasilisha taarifa za PAYE hata kama kiasi cha kulipa ni TZS 0. Taarifa ya PAYE ni wajibu hata kama hakuna kodi ya kulipa.",
"question_en":"Do employees earning less than TZS 270,000 per month pay PAYE?",
"answer_en":"No — employees earning TZS 270,000 or less are in the first PAYE band which has a 0% rate. They pay no PAYE at all. An employer still has an obligation to keep records of these wages and submit PAYE returns even if the amount to pay is TZS 0. The PAYE return is a filing obligation even when there is no tax to pay.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing PAYE bands","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"rural_conversational","pair_type":"standard","eval_set":False},

{"id":f"b008_paye_adv_007_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Mshahara wa TZS 270,001 (shilingi moja zaidi ya kizingiti) — mfanyakazi analipa PAYE?",
"answer_sw":"Ndiyo — mshahara wa TZS 270,001 unaathiriwa na bendi ya pili ya PAYE. Lakini: kodi inazingatiwa kwenye sehemu inayopita kizingiti cha TZS 270,000 tu — si mshahara wote. TZS 1 × 8% = TZS 0.08 (si hadi 0 kwa kuwa punguzo la kibinafsi la TZS 26,000 linafunika kiasi hiki kidogo). Kwa vitendo: mfanyakazi hatalipa PAYE hadi mshahara wake ufikiapo kiasi ambacho bendi za PAYE zinazalisha PAYE inayozidi TZS 26,000.",
"question_en":"Salary of TZS 270,001 (one shilling above the threshold) — does the employee pay PAYE?",
"answer_en":"Yes — a salary of TZS 270,001 is affected by the second PAYE band. But: tax applies to the portion exceeding the TZS 270,000 threshold only — not the full salary. TZS 1 × 8% = TZS 0.08 (effectively zero because the TZS 26,000 personal relief covers this tiny amount). In practice: an employee will not pay PAYE until their salary reaches the level where PAYE bands generate PAYE exceeding TZS 26,000.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_paye_adv_008_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Mwajiri alitumia mfumo wa zamani wa PAYE unaotumia bendi ya 9%. Wafanyakazi wanapaswa kupata rejesho la ziada waliyolipa?",
"answer_sw":"Ndiyo — ikiwa mfumo ulitumia 9% badala ya 8% kwa bendi ya pili, mfanyakazi alikuwa akilipa PAYE zaidi ya inayostahili. Tofauti ni 1% ya mapato kati ya TZS 270,001 na TZS 520,000. Mfanyakazi anastahili rejesho la ziada iliyolipwa. Mwajiri anapaswa: (1) kuhesabu tofauti; (2) kuomba TRA marekebisho (amendment) au rejesho (refund); (3) kusasisha mfumo wa mishahara kwa bendi sahihi za 2025/2026.",
"question_en":"An employer used an old PAYE system using a 9% band 2 rate. Are employees entitled to a refund of excess paid?",
"answer_en":"Yes — if the system used 9% instead of 8% for the second band, the employee was paying more PAYE than required. The difference is 1% of income between TZS 270,001 and TZS 520,000. The employee is entitled to a refund of the excess paid. The employer should: (1) calculate the difference; (2) apply to TRA for an amendment or refund; (3) update the payroll system to the correct 2025/2026 bands.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_paye_adv_009_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Kwa nini watu wengi wanasema bendi ya 2 ya PAYE ni 9% — kosa hili limetoka wapi?",
"answer_sw":"Kosa la 9% limetoka kwenye bendi za zamani za PAYE za Tanzania ambazo zilitumika kabla ya marekebisho. Bendi hii ilibadilishwa kwa 8% kupitia Finance Act ya miaka iliyopita. Mifumo mingi ya mishahara ya zamani, vitabu vya kodi visivyosasishwa, na wataalam fulani bado wanatumia kiwango cha zamani. Wajibu wa mwajiri ni kuhakikisha anatumia bendi za hivi karibuni za TRA — tazama tovuti ya TRA au wasiliana nao moja kwa moja kwa uthibitisho.",
"question_en":"Why do many people say PAYE band 2 is 9% — where did this error come from?",
"answer_en":"The 9% error comes from Tanzania's old PAYE bands that were used before amendments. This band was changed to 8% through a Finance Act in prior years. Many old payroll systems, uncorrected tax books, and some professionals still use the old rate. An employer's obligation is to use TRA's current latest bands — check the TRA website or contact them directly for confirmation.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing PAYE bands","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_paye_adv_010_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Je, mimi kama mwajiri ninaweza kukokotoa PAYE ya mfanyakazi mwenyewe au lazima nitumie TRA IDRAS?",
"answer_sw":"Unaweza kukokotoa PAYE mwenyewe ukijua bendi sahihi (bendi 2 = 8%, si 9%) na punguzo la kibinafsi (TZS 26,000/mwezi). Lakini: kwa usahihi wa hali ya juu na kuhakikisha unajumuisha makato yote yanayostahili — TRA IDRAS (taidras.tra.go.tz) ni chombo rasmi na cha kuaminika zaidi. Kwa mishahara rahisi: hisabati ya mkono inawezekana. Kwa mishahara ya ngumu (makato mengi, bonasi, NSSF, nk): tumia TRA IDRAS au mhesabu wa kodi.",
"question_en":"Can I as an employer calculate employee PAYE myself or must I use TRA IDRAS?",
"answer_en":"You can calculate PAYE yourself if you know the correct bands (band 2 = 8%, not 9%) and personal relief (TZS 26,000/month). But: for high-accuracy and to ensure all eligible deductions are included — TRA IDRAS (taidras.tra.go.tz) is the official and most reliable tool. For simple salaries: manual arithmetic is possible. For complex salaries (many deductions, bonuses, NSSF, etc.): use TRA IDRAS or a tax accountant.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

{"id":f"b008_paye_adv_011_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Bendi ya tatu ya PAYE (TZS 520,001-760,000) ni asilimia ngapi?",
"answer_sw":"Bendi ya tatu ya PAYE Tanzania ni asilimia 20. Mfumo wa bendi zote tano: Bendi 1 (0-270K): 0%; Bendi 2 (270K-520K): 8%; Bendi 3 (520K-760K): 20%; Bendi 4 (760K-1M): 25%; Bendi 5 (zaidi ya 1M): 30%. Ongezeko kutoka bendi 2 hadi bendi 3 ni kubwa — kutoka 8% hadi 20%. Hii inamaanisha mfanyakazi mwenye mshahara wa TZS 521,000 analipa 8% kwa sehemu ya bendi 2 NA 20% kwa TZS 1,000 ya bendi 3.",
"question_en":"What is the rate of the third PAYE band (TZS 520,001-760,000)?",
"answer_en":"The third PAYE band in Tanzania is 20%. All five band rates: Band 1 (0-270K): 0%; Band 2 (270K-520K): 8%; Band 3 (520K-760K): 20%; Band 4 (760K-1M): 25%; Band 5 (above 1M): 30%. The jump from band 2 to band 3 is large — from 8% to 20%. This means an employee earning TZS 521,000 pays 8% on the band 2 portion AND 20% on TZS 1,000 in band 3.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_paye_adv_012_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Ninajua viwango vya PAYE lakini ninahitaji hesabu ya sahihi ya PAYE ya mshahara wa TZS 900,000 — unaweza kunisaidia?",
"answer_sw":"Ninajua viwango vya PAYE Tanzania vizuri (bendi 1: 0%; bendi 2: 8%; bendi 3: 20%; bendi 4: 25%; bendi 5: 30%; punguzo: TZS 26,000/mwezi) lakini mahesabu ya mshahara mahususi yako nje ya mipaka yangu. Thibitisha na TRA IDRAS (taidras.tra.go.tz) au mshauri wa kodi aliyehitimu. Kwa mshahara wa TZS 900,000, bendi 1, 2, 3, na sehemu ya bendi 4 zitatumika — TRA IDRAS itahesabu sahihi.",
"question_en":"I know the PAYE rates but I need an accurate calculation for a salary of TZS 900,000 — can you help?",
"answer_en":"I know Tanzania's PAYE rates well (band 1: 0%; band 2: 8%; band 3: 20%; band 4: 25%; band 5: 30%; relief: TZS 26,000/month) but specific salary calculations are outside my coverage. Verify with TRA IDRAS (taidras.tra.go.tz) or a qualified tax adviser. For a TZS 900,000 salary, bands 1, 2, 3, and part of band 4 will apply — TRA IDRAS will calculate accurately.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"out_of_corpus_refusal","eval_set":False},

{"id":f"b008_paye_adv_013_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Je, bendi za PAYE zinabadilika kila mwaka au zinakaa sawa?",
"answer_sw":"Bendi za PAYE zinaweza kubadilika kila mwaka kupitia Finance Act inayotangazwa kila Julai. Mwaka 2025/2026, bendi ni: Bendi 1 (0-270K): 0%; Bendi 2 (270K-520K): 8%; Bendi 3 (520K-760K): 20%; Bendi 4 (760K-1M): 25%; Bendi 5 (zaidi ya 1M): 30%. Punguzo la kibinafsi: TZS 26,000/mwezi. Angalia Finance Act mpya kila Julai au wasiliana na TRA kuthibitisha bendi za sasa. Usitegemee viwango vya zamani bila kuthibitisha.",
"question_en":"Do PAYE bands change every year or do they remain the same?",
"answer_en":"PAYE bands may change annually through the Finance Act published each July. For 2025/2026, the bands are: Band 1 (0-270K): 0%; Band 2 (270K-520K): 8%; Band 3 (520K-760K): 20%; Band 4 (760K-1M): 25%; Band 5 (above 1M): 30%. Personal relief: TZS 26,000/month. Check the new Finance Act every July or contact TRA to confirm current bands. Do not rely on old rates without verifying.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment changing PAYE bands — review every July","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_paye_adv_014_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Bendi ya juu kabisa ya PAYE (30%) inaanza lini — ni kwa mapato yote zaidi ya TZS milioni moja?",
"answer_sw":"Ndiyo — kiwango cha 30% kinatumika kwenye sehemu ya mapato INAYOPITA TZS 1,000,000 kwa mwezi. Mapato ya TZS 0-1,000,000 yanapigwa kodi kwa bendi tofauti (0%, 8%, 20%, 25%). Sehemu inayozidi TZS 1,000,000 tu ndiyo inaathiriwa na 30%. Kwa hivyo mfanyakazi mwenye mshahara wa TZS 1,500,000 atalipa 30% kwenye TZS 500,000 tu (sehemu inayopita TZS 1M), si kwenye TZS 1.5M yote.",
"question_en":"When does the highest PAYE band (30%) start — is it on all income above TZS one million?",
"answer_en":"Yes — the 30% rate applies to the portion of income EXCEEDING TZS 1,000,000 per month. Income from TZS 0 to 1,000,000 is taxed at different bands (0%, 8%, 20%, 25%). Only the portion exceeding TZS 1,000,000 is affected by 30%. So an employee earning TZS 1,500,000 will pay 30% on TZS 500,000 only (the portion above TZS 1M), not on the full TZS 1.5M.",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_paye_adv_015_{DATE}","domain":"tier1a","subdomain":"paye_adversarial",
"question_sw":"Kwa muhtasari: bendi TANO za PAYE Tanzania kwa 2025/2026 — zitaje kwa usahihi kamili.",
"answer_sw":"Bendi TANO za PAYE Tanzania 2025/2026 — sahihi kamili: (1) TZS 0 hadi 270,000 = 0%; (2) TZS 270,001 hadi 520,000 = 8% (MUHIMU: si 9%); (3) TZS 520,001 hadi 760,000 = 20%; (4) TZS 760,001 hadi 1,000,000 = 25%; (5) Zaidi ya TZS 1,000,000 = 30%. Punguzo la kibinafsi: TZS 26,000 kwa mwezi. Kodi ya bendi inahusu sehemu ya mapato ndani ya bendi hiyo tu — si mshahara wote. Kwa mahesabu ya mshahara mahususi: tumia TRA IDRAS (taidras.tra.go.tz).",
"question_en":"Summary: the FIVE PAYE bands for Tanzania 2025/2026 — state them with complete accuracy.",
"answer_en":"FIVE PAYE bands for Tanzania 2025/2026 — complete accuracy: (1) TZS 0 to 270,000 = 0%; (2) TZS 270,001 to 520,000 = 8% (IMPORTANT: not 9%); (3) TZS 520,001 to 760,000 = 20%; (4) TZS 760,001 to 1,000,000 = 25%; (5) Above TZS 1,000,000 = 30%. Personal relief: TZS 26,000 per month. Band tax applies to the portion of income within that band only — not the full salary. For specific salary calculations: use TRA IDRAS (taidras.tra.go.tz).",
"primary_source_url":SRC_PAYE,"primary_source_name":SRC_NAME_PAYE,"source_type":"government_portal",
"effective_date":"2025-07-01","decay_risk":"annual",
"next_review_trigger":"Finance Act amendment — review every July","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

# ══════════════════════════════════════════════════════════
# FIX 9 — GN 487A DEPTH (15 pairs)
# EPZ, repeat offender, foreign-owned co + Tanzanian director,
# GN 487A vs work permits distinction
# ══════════════════════════════════════════════════════════

{"id":f"b008_gn487a_dpt_001_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"GN 487A na kibali cha kazi (work permit) — ni kitu kimoja au tofauti kabisa?",
"answer_sw":"Ni TOFAUTI KABISA — GN 487A na vibali vya kazi ni mifumo miwili tofauti ya kisheria inayosimamia masuala tofauti: GN 487A = LESENI YA BIASHARA — inazuia wageni kufanya AINA FULANI ZA BIASHARA hata kama wana haki ya kuishi na kufanya kazi Tanzania. Kibali cha kazi = SHERIA YA KAZI — inaruhusu mgeni kufanya kazi ya AJIRA kwa mwajiri wa Tanzania. Mgeni anaweza kuwa na kibali cha kazi halali cha kufanya kazi kama mhandisi mkuu — lakini bado anakiuka GN 487A akijaribu kufungua duka la rejareja.",
"question_en":"GN 487A and a work permit — are they the same thing or completely separate?",
"answer_en":"They are COMPLETELY SEPARATE — GN 487A and work permits are two different legal systems governing different matters: GN 487A = BUSINESS LICENSING — prohibits non-citizens from conducting CERTAIN TYPES OF BUSINESS even if they have the right to live and work in Tanzania. Work permit = LABOUR LAW — allows a non-citizen to do EMPLOYED WORK for a Tanzanian employer. A non-citizen may hold a valid work permit to work as a chief engineer — but still violates GN 487A if they try to open a retail shop.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or work permit regulations","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_dpt_002_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni ana kibali cha kazi cha mwaka mmoja. Je, kibali hiki kimempa ruhusa ya kufanya biashara ya jumla?",
"answer_sw":"Hapana — kibali cha kazi (work permit) kinamruhusu mgeni kufanya kazi kwa MWAJIRI MAALUM katika kazi iliyobainishwa kwenye kibali. Hakiruhusu kufanya biashara huru ya jumla au aina nyingine yoyote iliyopigwa marufuku na GN 487A. Biashara ya jumla imekatazwa wazi na GN 487A — kibali cha kazi hakibadilishi marufuku hii. Mgeni anayetaka kufanya biashara ya jumla Tanzania anahitaji zaidi ya kibali cha kazi — suala hili linahitaji ushauri wa kisheria.",
"question_en":"A non-citizen has a one-year work permit. Does this permit them to conduct wholesale trade?",
"answer_en":"No — a work permit allows a non-citizen to work for a SPECIFIC EMPLOYER in the job specified on the permit. It does not permit independent wholesale trade or any other business category prohibited by GN 487A. Wholesale trade is explicitly prohibited by GN 487A — a work permit does not change this prohibition. A non-citizen wishing to conduct wholesale trade in Tanzania needs more than a work permit — this matter requires legal advice.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or work permit regulations","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_dpt_003_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Kampuni ya Tanzania inayomilikiwa 100% na mgeni — inaweza kufanya biashara ya rejareja kama kampuni (si kama mtu binafsi)?",
"answer_sw":"Hapana — GN 487A inazuia biashara kwa wageni hata kwa njia ya kampuni. Ikiwa mgeni ndiye mmiliki wa 100% na/au mwenye nguvu za uamuzi wa kampuni inayofanya rejareja — hali hii inachukuliwa ukiukaji wa GN 487A. Muundo wa kampuni (limited liability) si ngao dhidi ya sheria hii. Idara ya Uhamiaji na TRA wanaangalia kwa makini umiliki wa kampuni wakati wa uchunguzi wa GN 487A.",
"question_en":"A Tanzanian company 100% owned by a non-citizen — can it conduct retail trade as a company (not as an individual)?",
"answer_en":"No — GN 487A prohibits businesses by non-citizens even through a company structure. If a non-citizen is 100% owner and/or decision-maker of a company conducting retail trade — this situation is treated as a GN 487A violation. The corporate structure (limited liability) is not a shield against this law. The Immigration Department and TRA scrutinise company ownership closely during GN 487A investigations.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_dpt_004_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Kampuni ya kimataifa inayomilikiwa na mgeni ina mkurugenzi (director) Mtanzania. Je, hii inafanya biashara ya rejareja iwe halali?",
"answer_sw":"Si kwa lazima. Kuwa na mkurugenzi Mtanzania kwenye ubao wa kampuni hakutoshi kuzuia tatizo la GN 487A kama mgeni bado ndiye mwenye nguvu za uamuzi za kweli za biashara. Idara ya Uhamiaji inaangalia: Ni nani mwenye hisa nyingi? Ni nani anayefanya maamuzi ya kila siku? Mkurugenzi Mtanzania anayefanya kazi kweli au ni jina tu? Ikiwa mkurugenzi Mtanzania ni wa bandia (nominal director), hali hii inaweza kuzingatiwa mpango wa kukwepa sheria.",
"question_en":"An internationally owned company has a Tanzanian director. Does this make retail trade legal?",
"answer_en":"Not necessarily. Having a Tanzanian director on the board is not sufficient to prevent a GN 487A problem if a non-citizen still holds the real decision-making power in the business. The Immigration Department looks at: Who holds the majority shares? Who makes day-to-day decisions? Is the Tanzanian director genuinely working or only a name? If the Tanzanian director is nominal (name-only), this arrangement may be treated as a scheme to circumvent the law.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_dpt_005_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni anayefanya kazi katika EPZ (Eneo Huru la Usindikaji) — GN 487A inazuia biashara zake pia?",
"answer_sw":"Makampuni ya EPZ (Export Processing Zones) na SEZ (Special Economic Zones) yanaweza kuwa na kanuni tofauti kutokana na makubaliano yao maalum ya kisheria na Serikali ya Tanzania. Suala hili si rahisi kujumuisha — EPZ inasimamiwa na Sheria ya EPZ na TIC (Tanzania Investment Centre) ambayo inaweza kutoa ruhusa maalum. Thibitisha hali ya kampuni yako ya EPZ moja kwa moja na TIC, EPZA (Export Processing Zones Authority), na Idara ya Uhamiaji ili kujua kama na kwa kiasi gani GN 487A inatumika.",
"question_en":"A non-citizen working in an EPZ (Export Processing Zone) — does GN 487A restrict their business too?",
"answer_en":"EPZ (Export Processing Zones) and SEZ (Special Economic Zones) companies may have different rules due to their special legal agreements with the Tanzanian government. This issue is not straightforward to generalise — EPZs are regulated by the EPZ Act and TIC (Tanzania Investment Centre) which may grant special permissions. Verify your specific EPZ company situation directly with TIC, EPZA (Export Processing Zones Authority), and the Immigration Department to know if and to what extent GN 487A applies.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"EPZ regulations or GN 487A amendment","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_dpt_006_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni alikamatwa kwa ukiukaji wa GN 487A mara ya pili — kuna adhabu maalum ya mara ya pili (recidivism)?",
"answer_sw":"GN 487A kama inavyosomeka haitaji adhabu maalum ya 'mara ya pili' au mfumo wa recidivism. Kila ukiukaji unashughulikiwa kwa kanuni za kawaida za korti za Tanzania ambazo zinazingatia historia ya mshtakiwa wakati wa kutoa hukumu. Korti inaweza kutoa adhabu kubwa zaidi kwa mgeni mwenye historia ya ukiukaji — lakini hii ni uamuzi wa korti, si sharti la kisheria lililowekwa na GN 487A. Kwa ufafanuzi zaidi: wasiliana na mwanasheria wa kisheria cha Tanzania.",
"question_en":"A non-citizen was caught violating GN 487A a second time — is there a special repeat offender (recidivism) penalty?",
"answer_en":"GN 487A as written does not provide for a specific 'second offence' penalty or recidivism system. Each violation is handled under normal Tanzanian court procedures which consider the defendant's history when sentencing. A court may impose a larger penalty for a non-citizen with a violation history — but this is a court decision, not a legal requirement set by GN 487A itself. For more clarification: contact a Tanzanian legal practitioner.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A adding recidivism provisions","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_dpt_007_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni ana leseni ya biashara ya Tanzania iliyotolewa na serikali ya mtaa — hii inamkinga dhidi ya GN 487A?",
"answer_sw":"Hapana — leseni ya biashara ya serikali ya mtaa haikinga dhidi ya GN 487A. Serikali za mitaa zina mamlaka ya kutoa leseni za biashara kwa madhumuni ya kawaida ya biashara. Lakini: kutoa leseni ya biashara kwa mgeni na biashara hiyo ikiwa kwenye orodha ya GN 487A ni kosa la utekelezaji wa serikali ya mtaa — haibadilishi adhabu ya shirika la kitaifa la uhamiaji. GN 487A inasimamia Idara ya Uhamiaji — si serikali za mitaa.",
"question_en":"A non-citizen has a business licence issued by local government — does this protect against GN 487A?",
"answer_en":"No — a local government business licence does not protect against GN 487A. Local governments have authority to issue business licences for general business purposes. But: issuing a business licence to a non-citizen for a business on the GN 487A list is a local government enforcement error — it does not change the national immigration authority's penalties. GN 487A is enforced by the Immigration Department — not local governments.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or business licensing regulations","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_dpt_008_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni anafanya kazi kama CEO wa kampuni kubwa ya biashara ya jumla. Je, ana tatizo la GN 487A?",
"answer_sw":"Mgeni kama CEO (mfanyakazi wa ajira) wa kampuni inayomilikiwa halisi na Watanzania — hali hii ni tofauti na kufanya biashara mwenyewe. GN 487A inazuia wageni kufanya biashara zilizoorodheshwa — si kwa lazima kufanya kazi kama mfanyakazi wa kampuni ya Watanzania. Hata hivyo: ikiwa mgeni ni CEO na pia mmiliki wa hisa nyingi — inaweza kuzingatiwa kufanya biashara, si kufanya kazi tu. Mstari huu mwembamba unahitaji ushauri wa kisheria kwa hali mahususi.",
"question_en":"A non-citizen works as CEO of a large wholesale trading company. Do they have a GN 487A problem?",
"answer_en":"A non-citizen as CEO (employed worker) of a company genuinely owned by Tanzanians — this situation differs from personally conducting a business. GN 487A prohibits non-citizens from conducting the listed businesses — not necessarily from working as an employee of a Tanzanian-owned company. However: if the non-citizen is CEO AND also majority shareholder — it may be treated as conducting business, not merely working. This fine line requires legal advice for the specific situation.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or related case law","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_dpt_009_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Tofauti kati ya GN 487A (biashara) na sheria ya kazi (labor law) ni nini kwa mgeni?",
"answer_sw":"Tofauti kuu kwa wageni: GN 487A (biashara): inazuia mgeni KUMILIKI au KUENDESHA biashara fulani. Ni kuhusu BIASHARA ya mgeni mwenyewe. Sheria ya kazi (Work Permit): inaruhusu mgeni kufanya KAZI ya AJIRA kwa kampuni ya Tanzania. Ni kuhusu mgeni kufanya kazi kwa MTU MWINGINE. Mgeni anaweza kuwa na kibali cha kazi halali cha kufanya kazi kama daktari mkuu — lakini akifungua kliniki yake binafsi, anakiuka GN 487A. Hizi ni mifumo miwili tofauti.",
"question_en":"What is the difference between GN 487A (business) and labour law for a non-citizen?",
"answer_en":"Key difference for non-citizens: GN 487A (business): prohibits a non-citizen from OWNING or RUNNING certain businesses. It is about the non-citizen's OWN BUSINESS. Labour law (Work Permit): permits a non-citizen to do EMPLOYED WORK for a Tanzanian company. It is about a non-citizen working for SOMEONE ELSE. A non-citizen may hold a valid work permit to work as a chief doctor — but if they open their own private clinic, they violate GN 487A. These are two different systems.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or immigration regulations","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_dpt_010_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Je, uwekezaji wa moja kwa moja wa kigeni (FDI) unaathiriwa na GN 487A?",
"answer_sw":"FDI (Foreign Direct Investment) na uwekezaji wa kimataifa mkubwa unaosimamiwa na TIC (Tanzania Investment Centre) na sheria ya uwekezaji unaweza kuwa na mwongozo tofauti kutoka kwa GN 487A. TIC inaweza kutoa hati za uwekezaji zinazomruhusu mgeni kufanya biashara kwa masharti maalum. Hata hivyo: FDI inayofanya biashara katika makundi yaliyopigwa marufuku na GN 487A (rejareja ndogo, salon, nk) bila idhini maalum ya TIC inaweza bado kukiuka GN 487A. Thibitisha hali yako na TIC na Idara ya Uhamiaji.",
"question_en":"Does foreign direct investment (FDI) get affected by GN 487A?",
"answer_en":"FDI and large international investments managed through TIC (Tanzania Investment Centre) and investment law may have different guidance from GN 487A. TIC may issue investment certificates that permit a non-citizen to conduct business under specific conditions. However: FDI conducting businesses in GN 487A prohibited categories (small retail, salons, etc.) without specific TIC authorisation may still violate GN 487A. Verify your situation with TIC and the Immigration Department.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or investment law","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_dpt_011_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni mwenye ruhusa ya ukaazi wa kudumu (permanent residence permit) — ana haki ya kufanya rejareja?",
"answer_sw":"Hapana — ruhusa ya ukaazi wa kudumu (permanent residence) inakuruhusu kuishi Tanzania kwa muda mrefu lakini haikubadilishi hadhi yako ya 'mgeni' kwa madhumuni ya GN 487A. GN 487A inaangalia URAIA wa Tanzania — si hali ya ukaazi. Mgeni mwenye ukaazi wa kudumu bado anakabiliwa na vikwazo vya GN 487A kwa biashara. Njia pekee ya kubadilisha hadhi hii ni kupata uraia wa Tanzania rasmi.",
"question_en":"A non-citizen with a permanent residence permit — do they have the right to conduct retail trade?",
"answer_en":"No — a permanent residence permit allows you to live in Tanzania long-term but does not change your 'non-citizen' status for GN 487A purposes. GN 487A looks at Tanzanian CITIZENSHIP — not residency status. A non-citizen with permanent residence still faces GN 487A restrictions on business. The only way to change this status is to obtain Tanzanian citizenship formally.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or citizenship law","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_dpt_012_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"GN 487A ilianza kutumika tarehe gani hasa — na operesheni ya utekelezaji ilifanyika lini?",
"answer_sw":"GN 487A ilianza kutumika tarehe 28 Julai 2025 — siku hiyo hiyo ilitangazwa kwenye Gazeti la Serikali. Operesheni ya utekelezaji wa kwanza ilifanyika kati ya tarehe 11 Septemba 2025 na 8 Oktoba 2025 ikiongozwa na Idara ya Uhamiaji. Jina kamili la amri: Business Licensing (Prohibition of Business Activities for Non-Citizens) Order 2025. Kutaja mwaka mwingine wowote (2023 au 2024) ni kosa — amri hii ni ya 2025.",
"question_en":"On exactly what date did GN 487A take effect — and when did the enforcement operation happen?",
"answer_en":"GN 487A took effect on 28 July 2025 — the same day it was gazetted in the Government Gazette. The first enforcement operation took place between 11 September 2025 and 8 October 2025 led by the Immigration Department. Full name of the order: Business Licensing (Prohibition of Business Activities for Non-Citizens) Order 2025. Citing any other year (2023 or 2024) is an error — this order is from 2025.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"standard","eval_set":False},

{"id":f"b008_gn487a_dpt_013_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Mgeni anamiliki hisa 49% na Mtanzania ana 51% — biashara ya rejareja ni halali?",
"answer_sw":"Umiliki wa hisa 51% na Mtanzania ni hatua nzuri lakini si dhamana kamili ya kuzuia tatizo la GN 487A. Idara ya Uhamiaji inachunguza: ni nani anayeendesha biashara halisi, ni nani mwenye nguvu za uamuzi, na kama umiliki wa Mtanzania ni wa kweli au wa bandia. Ikiwa mgeni ana 49% lakini ana nguvu kamili za uamuzi na Mtanzania ni mmiliki wa jina tu — hali hii inaweza kuzingatiwa ukiukaji. Muundo wa kisheria lazima uwe wa kweli.",
"question_en":"A non-citizen owns 49% of shares and a Tanzanian owns 51% — is retail trade legal?",
"answer_en":"A Tanzanian 51% shareholding is a good step but is not a complete guarantee against a GN 487A problem. The Immigration Department investigates: who actually runs the business, who holds decision-making power, and whether the Tanzanian ownership is genuine or nominal. If a non-citizen has 49% but holds full decision-making power and the Tanzanian is owner in name only — this situation may be treated as a violation. The legal structure must be genuine.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A or related case law","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"formal","pair_type":"adversarial","eval_set":False},

{"id":f"b008_gn487a_dpt_014_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Je, kuna mgawanyo wowote kati ya GN 487A na biashara za kidijitali (online business) za wageni?",
"answer_sw":"GN 487A inazuia biashara kwa wageni Tanzania Bara — lakini jinsi inavyotumika kwa biashara za kidijitali (online) bado si wazi kabisa katika mwongozo rasmi. Biashara ya kidijitali ambayo kimsingi inafanya 'retail trade' ya bidhaa na wateja wa Tanzania inaweza kuzingatiwa ikiwa ndani ya mipaka ya GN 487A hata kama inafanyika mtandaoni. Mwongozo huu maalum bado unaendelea kuwa katika mchakato wa kubainishwa. Thibitisha na Idara ya Uhamiaji na TRA.",
"question_en":"Is there any distinction between GN 487A and non-citizen digital (online) businesses?",
"answer_en":"GN 487A prohibits businesses by non-citizens in Tanzania Mainland — but how it applies to digital (online) businesses is not yet entirely clear in official guidance. An online business that in essence conducts 'retail trade' of goods with Tanzanian customers may be considered within GN 487A's scope even if conducted online. This specific guidance is still in the process of being clarified. Verify with the Immigration Department and TRA.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Regulatory guidance on digital business and GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"disambiguation","eval_set":False},

{"id":f"b008_gn487a_dpt_015_{DATE}","domain":"tier1a","subdomain":"gn487a_adversarial",
"question_sw":"Kwa muhtasari wa mada ngumu ya GN 487A: vitu 4 muhimu ambavyo mfanyabiashara yeyote lazima avijue.",
"answer_sw":"Vitu 4 muhimu vya GN 487A kwa mfanyabiashara: (1) NANI: Wageni (non-citizens) tu — Watanzania hawakabiwi vikwazo vya GN 487A. (2) NINI: Makundi 15 ya biashara yakiwemo rejareja, jumla, mobile money, ukarabati wa simu, salon, kinyozi, ushonaji, na mengine. (3) ADHABU: Mgeni = angalau TZS 10M NA kifungo NA visa kufutwa; Msaidizi Mtanzania = hadi TZS 5M AU kifungo miezi 3. (4) NJIA ZA KUKWEPA HAZIFANYI KAZI: Ndoa, ukaazi wa muda mrefu, kampuni ya Tanzania, 49%/51% bandia — zote hazizuii GN 487A bila uraia wa kweli wa Tanzania.",
"question_en":"Summary of the complex GN 487A topic: 4 critical things any business person must know.",
"answer_en":"4 critical GN 487A things for any business person: (1) WHO: Non-citizens only — Tanzanians are not subject to GN 487A restrictions. (2) WHAT: 15 business categories including retail, wholesale, mobile money, phone repair, hair salons, barbershops, tailoring, and others. (3) PENALTIES: Non-citizen = at least TZS 10M AND imprisonment AND visa revocation; Tanzanian facilitator = up to TZS 5M OR 3 months' imprisonment. (4) CIRCUMVENTION METHODS DO NOT WORK: Marriage, long residency, Tanzanian company, fake 49%/51% — none of these prevent GN 487A without genuine Tanzanian citizenship.",
"primary_source_url":SRC_GN487A,"primary_source_name":SRC_NAME_GN,"source_type":"official_gazette",
"effective_date":"2025-07-28","decay_risk":"event_triggered",
"next_review_trigger":"Amendment to GN 487A","verified_by":"founder_self_review",
"verified_date":"2026-06-12","register":"business_market","pair_type":"standard","eval_set":False},

]

OUT = "datasets/tier1a/raw_sources/raw_pairs_batch_008.jsonl"
with open(OUT, "a", encoding="utf-8") as f:
    for p in pairs:
        f.write(json.dumps(p, ensure_ascii=False) + "\n")

print(f"Part 3 written: {len(pairs)} pairs appended to {OUT}")
regs = {}
for p in pairs:
    r = p["register"]; regs[r] = regs.get(r,0)+1
for k,v in sorted(regs.items()):
    print(f"  {k}: {v} ({v/len(pairs)*100:.0f}%)")
