"""
Generate Batch C: 50 pairs
- paye_extended: 20 pairs (tier1a_paye_extended_001..020_20260603)
- income_tax: 15 pairs (tier1a_income_tax_001..015_20260603)
- business_licensing: 15 pairs (tier1a_biz_lic_001..015_20260603)

Sources:
- PAYE: CLAUDE.md locked facts (TRA portal timed out) — fallback to ITA/Finance Act 2025
- Income tax: CLAUDE.md locked facts (TRA portal timed out) — fallback to ITA Cap.332
- Business licensing: brela2.html + CLAUDE.md locked facts
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

BATCH_C = [
    # ── PAYE EXTENDED (20 pairs) ────────────────────────────────────────────
    {
        "id": "tier1a_paye_extended_001_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mfanyakazi anamaliza kazi baada ya miaka 10. Kampuni inalipa TZS 5,000,000 kama mafao ya mwisho. Je, PAYE inatolewa kwenye malipo hayo?",
        "answer_sw": "Ndiyo. Chini ya Sheria ya Kodi ya Mapato, malipo ya mwisho wa kazi kama vile mafao, gratuity na bonasi ya kustaafu yanajumuishwa kwenye mapato yanayotozwa kodi. Mwajiri lazima ahesabu PAYE kwenye malipo hayo na kuiwasilisha TRA ifikapo tarehe 7 ya mwezi unaofuata. Kiwango cha kodi kinatumika kulingana na jedwali la kawaida la PAYE — mapato ya mwezi huo yote pamoja. Unaweza kujua zaidi kwenye tra.go.tz.",
        "answer_en": "Yes. Under the Income Tax Act, employment termination benefits including gratuity, severance pay, and retirement bonuses are included in taxable employment income. The employer must calculate PAYE on these payments and remit to TRA by the 7th of the following month. The normal PAYE tax bands apply — total income for that month is taxed. See tra.go.tz for details.",
        "question_en": "An employee completes 10 years of service. The company pays TZS 5,000,000 as terminal benefits. Is PAYE deducted from this payment?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — Income Tax Act Cap.332",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_002_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Kampuni inampa mfanyakazi gari la kampuni kutumia nyumbani na kazini. Je, thamani ya gari hilo inatozwa PAYE?",
        "answer_sw": "Ndiyo. Matumizi ya kibinafsi ya gari la kampuni yanachukuliwa kama faida ya ajira (benefit in kind) na yanajumuishwa kwenye mapato yanayotozwa PAYE. TRA inakadiri thamani ya matumizi ya kibinafsi kulingana na kanuni. Mwajiri lazima aongeze thamani hiyo kwenye mshahara wa mwezi wakati anahesabu PAYE. Hoja kwamba gari ni la kazi peke yake haipokewi bila ushahidi wa kutosha.",
        "answer_en": "Yes. Personal use of a company car is treated as a benefit in kind and is included in taxable employment income subject to PAYE. TRA estimates the value of private use according to prescribed rules. The employer must add this deemed value to the employee's monthly salary when calculating PAYE. A claim that the car is used purely for business purposes requires sufficient evidence.",
        "question_en": "A company provides an employee with a company car for both home and work use. Is the value of the car use subject to PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — Income Tax Act Cap.332 s.7",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_003_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mfanyakazi anafanya kazi Tanzania na Kenya kwa asilimia 60 na 40 kwa mtiririko. Nani analipa PAYE nchini Tanzania?",
        "answer_sw": "Kwa Tanzania, PAYE inalipwa kwa sehemu ya mshahara inayohusiana na kazi iliyofanywa Tanzania (asilimia 60). Mwajiri anayemlipa mfanyakazi lazima ahifadhi rekodi wazi za siku za kufanya kazi kila nchi. Kama mwajiri ana makao makuu Tanzania, kawaida analipa PAYE kwenye mshahara wote kwanza, kisha anaweza kudai msamaha wa kodi (tax credit) kwa sehemu iliyotozwa Kenya ikiwa kuna makubaliano ya kuzuia utozwaji kodi mara mbili (DTA). Thibitisha mpango wako na mshauri wa kodi wa TRA.",
        "answer_en": "For Tanzania, PAYE applies to the portion of salary relating to work performed in Tanzania (60%). An employer paying the employee must maintain clear records of working days in each country. If the employer is resident in Tanzania, they typically withhold PAYE on total salary first, then a tax credit may be claimed for the portion taxed in Kenya under a double taxation agreement (DTA). Confirm your arrangement with a TRA-registered tax consultant.",
        "question_en": "An employee works 60% in Tanzania and 40% in Kenya. Who pays PAYE in Tanzania?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — Income Tax Act Cap.332 + DTA provisions",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "DTA amendment or Finance Act",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_004_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mwajiri anapaswa kuwasilisha fomu gani TRA mwishoni mwa mwaka wa mapato kwa kila mfanyakazi?",
        "answer_sw": "Mwajiri lazima aandae na kuwasilisha Fomu P9 kwa kila mfanyakazi ifikapo tarehe 31 Januari ya mwaka unaofuata mwaka wa mapato. Fomu P9 inaonyesha jumla ya mshahara wa mwaka, PAYE iliyokatwa, na mchango wa NSSF. Nakala moja inatolewa kwa mfanyakazi na moja inawasilishwa TRA. Kuchelewa kuwasilisha fomu P9 kunasababisha adhabu.",
        "answer_en": "An employer must prepare and submit Form P9 for each employee by 31 January of the year following the tax year. Form P9 shows the total annual salary, PAYE deducted, and NSSF contributions. One copy is given to the employee and one is filed with TRA. Late submission of Form P9 attracts penalties.",
        "question_en": "What form must an employer submit to TRA at the end of the tax year for each employee?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — P9 Annual Employer Return",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "TRA administrative circular",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_005_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Shamba la kahawa linaajiri wafanyakazi wa msimu wa mavuno kwa miezi 3 tu. Je, lazima litoe PAYE?",
        "answer_sw": "Ndiyo, ikiwa mshahara wa msimu unazidi kiwango kisichoweza kutozwa kodi. Kiwango cha msingi kisicotozwa kodi ni TZS 270,000 kwa mwezi. Kama mfanyakazi wa msimu anapata zaidi ya TZS 270,000 kwa mwezi, mwajiri lazima akatae PAYE ya mwezi huo na kuiwasilisha TRA ifikapo tarehe 7 ya mwezi unaofuata. Wafanyakazi wa msimu hawana msamaha maalum wa PAYE.",
        "answer_en": "Yes, if the seasonal salary exceeds the tax-free threshold. The tax-free threshold is TZS 270,000 per month. If a seasonal worker earns more than TZS 270,000 per month, the employer must deduct PAYE for that month and remit to TRA by the 7th of the following month. Seasonal workers have no special PAYE exemption.",
        "question_en": "A coffee farm employs seasonal workers for harvest for only 3 months. Must it deduct PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — Income Tax Act Cap.332",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to tax bands",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "rural_conversational",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_006_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Kampuni inalipa michango ya pension kwa niaba ya mfanyakazi kwenye mfuko ulioibuliwa na Serikali. Je, michango hiyo inatozwa PAYE?",
        "answer_sw": "Michango ya mwajiri kwenye mfuko wa pension ulioibuliwa (kama NSSF, PPF, GEPF) haijumuishwi kwenye mapato ya mfanyakazi yanayotozwa PAYE, mpaka kiasi kinachokubalika kisheria. Lakini michango ya ziada zaidi ya kikomo cha kisheria inaweza kutozwa. Michango ya mfanyakazi mwenyewe kwenye mifuko iliyoidhinishwa inaweza kudaiwa kama punguzo la kodi (allowable deduction) wakati wa mahesabu ya PAYE. Thibitisha kikomo halisi cha mwaka huu na TRA.",
        "answer_en": "Employer contributions to an approved pension fund (such as NSSF, PPF, GEPF) are not included in the employee's taxable employment income, up to the legally permitted limit. Contributions above the statutory ceiling may be taxable. Employee contributions to approved funds may be claimed as an allowable deduction when calculating PAYE. Verify the current year ceiling with TRA.",
        "question_en": "A company pays pension contributions on behalf of an employee to a government-approved fund. Are those contributions subject to PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — Income Tax Act Cap.332 pension provisions",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_007_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Kampuni yangu ilikata PAYE kidogo sana kwa mfanyakazi kwa makosa ya hesabu. Ninafanyaje marekebisho?",
        "answer_sw": "Unahitaji kuwasilisha TRA return ya marekebisho (amended return) kwa mwezi husika. Lipa tofauti ya PAYE iliyokosekana pamoja na riba ya kuchelewa (16% kwa mwaka). Taarisha TRA kupitia barua yenye maelezo ya kosa. Ikiwa kosa linagundulika kabla ya muda wa ukaguzi, kujisalimisha kwa hiari (voluntary disclosure) kunaweza kupunguza adhabu. Wasiliana na TRA service desk au ofisi ya karibu nawe.",
        "answer_en": "You need to file an amended PAYE return with TRA for the affected month. Pay the shortfall plus late payment interest (16% per annum). Notify TRA in writing with an explanation of the error. If the error is discovered before an audit, voluntary disclosure may reduce penalties. Contact the TRA service desk or nearest TRA office.",
        "question_en": "Our company deducted too little PAYE from an employee due to a calculation error. How do we correct this?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — amended return and voluntary disclosure",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "TRA administrative circular",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_008_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Wakati TRA inakagua PAYE ya kampuni yangu, wanakagua nini hasa?",
        "answer_sw": "Wakati wa ukaguzi wa PAYE, TRA wanakagua: orodha ya mishahara (payroll) kwa miaka yote inayopitiwa, rekodi za benki za malipo ya mshahara, mikataba ya ajira ya wafanyakazi, return za PAYE zilizowasilishwa, fomu za P9 zilizotolewa kwa wafanyakazi, vielelezo vya michango ya ziada kama posho za nyumba na usafiri, na malipo yoyote yanayosemekana kuwa ya 'mkopo' au 'kama ada'. Tofauti kati ya rekodi za benki na payroll ni dalili kuu ya udanganyifu.",
        "answer_en": "During a PAYE audit, TRA examines: payroll records for all years under review, bank statements showing salary payments, employment contracts, submitted PAYE returns, P9 forms issued to employees, documentation for additional payments such as housing and transport allowances, and any payments classified as 'loans' or 'fees'. Discrepancies between bank records and the payroll are a key fraud indicator.",
        "question_en": "When TRA audits our company's PAYE, what exactly do they examine?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — audit checklist",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "TRA audit methodology change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_009_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Wakala wa mauzo analipwa commission tu — hakuna mshahara wa msingi. Je, PAYE inahusu vipi?",
        "answer_sw": "Ndiyo, PAYE inatumika kwa wafanyakazi wanaolipwa commission peke yake. Kila mwezi, mwajiri anahesabu PAYE kwenye jumla ya commission iliyolipwa mwezi huo kwa kutumia jedwali la kawaida la PAYE. Mwezi bila commission = hakuna PAYE ya kulipa. Mwezi wa commission kubwa = PAYE kubwa zaidi. Mwajiri lazima aandike rekodi za miamala yote ya commission na PAYE inayohusiana.",
        "answer_en": "Yes, PAYE applies to employees paid commission only. Each month, the employer calculates PAYE on the total commission paid that month using the normal PAYE tax bands. A month with no commission = no PAYE due. A month with large commission = higher PAYE. The employer must record all commission transactions and the corresponding PAYE.",
        "question_en": "A sales agent is paid commission only — no base salary. How does PAYE apply?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — Income Tax Act Cap.332",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_010_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Kampuni inalipia mfanyakazi tikiti ya ndege ya kwenda mkutano wa biashara. Je, tikiti hiyo inatozwa PAYE?",
        "answer_sw": "Hapana, ikiwa safari ni ya biashara ya kweli na kampuni inalipa moja kwa moja au kumpa risiti ya malipo. Malipo ya gharama halisi za biashara zilizothibitishwa hayajumuishwi kwenye mapato yanayotozwa PAYE. Lakini ikiwa mfanyakazi anapewa posho ya jumla (lump sum) bila kuhitajika kutoa risiti, posho hiyo inatozwa PAYE. Akaunti za gharama lazima ziwe na kumbukumbu sahihi za safari.",
        "answer_en": "No, if the travel is genuine business travel and the company pays directly or reimburses against receipts. Reimbursement of actual documented business expenses is not included in taxable employment income. However, if the employee is given a flat allowance without requiring receipts, that allowance is subject to PAYE. Expense accounts must maintain proper travel records.",
        "question_en": "A company pays an employee's flight ticket to attend a business conference. Is that ticket subject to PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — expense reimbursement rules",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "TRA policy change on reimbursements",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_011_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mfanyakazi ana mapato mawili — mshahara wa kampuni ya A na kazi ya sehemu kwa kampuni ya B. Je, kila mwajiri anakata PAYE kiasi gani?",
        "answer_sw": "Kila mwajiri anakata PAYE kwenye mshahara wake peke yake kwa kutumia jedwali la kawaida. Tatizo ni kwamba mfanyakazi anapata msamaha wa TZS 270,000/mwezi mara mbili — moja kwa kila mwajiri — wakati anapaswa kupata mara moja tu. Mwishoni mwa mwaka, mfanyakazi anaweza kulazimika kulipa PAYE ya ziada ikiwa jumla ya mapato kutoka pande zote mbili inasababisha kodi ya juu zaidi. Mfanyakazi anapaswa kuripoti hali hii kwa TRA kupitia kujaza return ya mtu binafsi.",
        "answer_en": "Each employer withholds PAYE on their own salary payment using the normal tax bands. The problem is that the employee receives the TZS 270,000/month personal relief twice — once from each employer — when they are entitled to it only once. At year end, the employee may owe additional PAYE if combined income from both sources falls into a higher tax band. The employee should report this situation to TRA by filing an individual income tax return.",
        "question_en": "An employee has two incomes — a salary from Company A and part-time work at Company B. How much PAYE does each employer deduct?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — multiple employment income",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_012_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Adhabu gani inatumika ikiwa mwajiri halipi PAYE kwa wakati ifikapo tarehe 7 ya mwezi?",
        "answer_sw": "Ikiwa PAYE haijalipwa ifikapo tarehe 7 ya mwezi unaofuata, adhabu ya 5% ya kiwango kisicholipwa inatumika kwa kila mwezi wa ucheleweshaji au sehemu ya mwezi. Zaidi ya hayo, riba ya 16% kwa mwaka inaongezwa kwenye kiasi kisicholipwa. Adhabu hizi zinaendelea kukusanyika hadi PAYE yote ilipwe. TRA pia ina mamlaka ya kuchukua hatua za kisheria dhidi ya mwajiri asiyetii.",
        "answer_en": "If PAYE is not paid by the 7th of the following month, a 5% penalty on the unpaid amount applies for each month or part of a month of delay. Additionally, interest at 16% per annum is charged on the unpaid balance. These penalties continue to accumulate until the full PAYE is paid. TRA also has authority to take legal enforcement action against a non-compliant employer.",
        "question_en": "What penalty applies if an employer does not pay PAYE on time by the 7th of the month?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — penalties and interest",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to penalty rates",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_013_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Kampuni inampa mfanyakazi posho ya nyumba ya TZS 300,000 kila mwezi. Je, posho hiyo inatozwa PAYE?",
        "answer_sw": "Ndiyo. Posho ya nyumba (housing allowance) inajumuishwa kwenye mapato ya ajira yanayotozwa PAYE bila kujali kama inaitwa 'posho' au 'mshahara'. TZS 300,000 ya posho ya nyumba inaongezwa kwenye mshahara wa msingi kabla ya kuhesabu PAYE ya mwezi. Tofauti pekee ni ikiwa kampuni inadhihirisha nyumba yake wenyewe (company accommodation) — hapo thamani ya manufaa inakadiriwa tofauti.",
        "answer_en": "Yes. Housing allowance is included in taxable employment income subject to PAYE regardless of whether it is called an 'allowance' or 'salary'. The TZS 300,000 housing allowance is added to the basic salary before calculating monthly PAYE. The only difference is where the company provides its own accommodation (company accommodation) — in that case the value of the benefit is assessed differently.",
        "question_en": "A company pays an employee a housing allowance of TZS 300,000 per month. Is that allowance subject to PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — employment income inclusions",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_014_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Posho ya usafiri ya TZS 50,000 kwa mwezi inayolipwa kwa mfanyakazi — inatozwa PAYE au la?",
        "answer_sw": "Inategemea jinsi inavyolipwa. Ikiwa ni posho ya jumla (flat allowance) bila kuhitajika risiti — inatozwa PAYE. Ikiwa ni malipo ya gharama halisi za usafiri wa biashara yanayolipwa dhidi ya risiti — hayatozwi PAYE. Posho nyingi za usafiri zinazolipwa kwa wafanyakazi wa Tanzania zinachukuliwa kama sehemu ya mapato ya ajira na zinatozwa PAYE. Hakikisha una sera ya gharama wazi inayoelezea msingi wa malipo.",
        "answer_en": "It depends on how it is paid. If it is a flat allowance without requiring receipts — it is subject to PAYE. If it is reimbursement of actual business travel costs against receipts — it is not subject to PAYE. Most transport allowances paid to employees in Tanzania are treated as part of employment income and are subject to PAYE. Ensure you have a clear expenses policy explaining the basis of payment.",
        "question_en": "A transport allowance of TZS 50,000 per month paid to an employee — is it subject to PAYE or not?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — allowances and benefits",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act or TRA circular on allowances",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_015_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mfanyakazi mpya anaanza kazi Aprili badala ya Januari. Mwajiri anahesabu PAYE yake vipi kwa mwaka huo?",
        "answer_sw": "Mwajiri anahesabu PAYE kuanzia mwezi wa kwanza wa ajira (Aprili). Hakuna marekebisho ya nyuma kwa miezi ya kabla ya ajira. Kwa mwaka huo, mfanyakazi anaweza kupata msamaha wa kibinafsi (personal relief) kwa miezi 9 tu (Aprili–Desemba) kupitia mwajiri. Ikiwa mfanyakazi alifanya kazi pengine kabla ya Aprili na anapaswa kulipa kodi ya ziada, atajaza return ya mtu binafsi mwishoni mwa mwaka.",
        "answer_en": "The employer calculates PAYE from the first month of employment (April). There is no retrospective adjustment for months before employment. For that year, the employee receives personal relief for only 9 months (April–December) through the employer. If the employee worked elsewhere before April and owes additional tax, they will file an individual income tax return at year end.",
        "question_en": "A new employee starts work in April instead of January. How does the employer calculate PAYE for that year?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — new employee mid-year",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_016_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mfanyakazi anapata mshahara wa TZS 250,000 kwa mwezi tu. Je, mwajiri anahitajika kukata PAYE?",
        "answer_sw": "Hapana. Kiwango cha msingi kisichotozwa kodi ni TZS 270,000 kwa mwezi. Mshahara wa TZS 250,000 uko chini ya kikomo hiki, kwa hiyo hakuna PAYE ya kukatwa. Hata hivyo, mwajiri bado lazima awe na rekodi ya mfanyakazi na aweze kuthibitisha mshahara huu kwa ukaguzi wa TRA. Ikiwa mshahara utaongezwa juu ya TZS 270,000, PAYE itaanza kutumika mara moja.",
        "answer_en": "No. The tax-free monthly threshold is TZS 270,000. A salary of TZS 250,000 is below this threshold, so no PAYE is deducted. However, the employer must still maintain a record of the employee and be able to demonstrate this salary to TRA during an audit. If the salary rises above TZS 270,000, PAYE will apply immediately.",
        "question_en": "An employee earns only TZS 250,000 per month. Must the employer deduct PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — tax-free threshold",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to tax bands",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_017_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mfanyakazi anapata overtime ya TZS 200,000 na bonus ya TZS 300,000 mwezi huu. Je, vinatozwa PAYE?",
        "answer_sw": "Ndiyo. Overtime na bonus zote zinaongezwa kwenye mshahara wa kawaida wa mwezi huo kabla ya kuhesabu PAYE. Kwa mfano, mshahara wa msingi wa TZS 500,000 + overtime TZS 200,000 + bonus TZS 300,000 = mapato ya mwezi TZS 1,000,000. PAYE inakokotolewa kwenye TZS 1,000,000 kulingana na jedwali la PAYE. Hakuna msamaha maalum wa overtime au bonus Tanzania.",
        "answer_en": "Yes. Overtime and bonuses are both added to the regular monthly salary before calculating PAYE. For example: basic salary TZS 500,000 + overtime TZS 200,000 + bonus TZS 300,000 = monthly income TZS 1,000,000. PAYE is calculated on TZS 1,000,000 according to the PAYE tax bands. There is no special exemption for overtime or bonuses in Tanzania.",
        "question_en": "An employee receives overtime of TZS 200,000 and a bonus of TZS 300,000 this month. Are they subject to PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — income inclusions",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_018_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mwajiri anatoa cheti gani kwa mfanyakazi wakati anamaliza kazi ili kuthibitisha PAYE iliyokatwa?",
        "answer_sw": "Mwajiri anatoa Fomu P45 (au hati sawa) ikionyesha jumla ya mshahara na PAYE iliyokatwa hadi tarehe ya kumaliza kazi. Fomu hii inasaidia mwajiri mpya kuhesabu PAYE kwa usahihi kwa sehemu ya mwaka iliyobaki. Pia, ifikapo Januari 31 ya mwaka unaofuata, mwajiri anatoa Fomu P9 ikionyesha mapato ya mwaka mzima na PAYE yote iliyokatwa. Mfanyakazi anahifadhi fomu hizi kwa matumizi ya return ya kodi ya mtu binafsi.",
        "answer_en": "The employer issues Form P45 (or equivalent) showing total earnings and PAYE deducted up to the date of leaving. This form helps the new employer calculate PAYE correctly for the remainder of the year. Also, by 31 January of the following year, the employer issues Form P9 showing full-year earnings and total PAYE deducted. The employee retains these forms for their individual tax return.",
        "question_en": "What certificate does an employer give an employee when they leave employment to confirm the PAYE deducted?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — P45 and P9 forms",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "TRA administrative form change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_019_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Kampuni inalipia mfanyakazi chakula cha mchana (lunch) kila siku kiwanda. Je, chakula hicho kinatozwa PAYE?",
        "answer_sw": "Inategemea. Chakula kinachotolewa kwenye chumba cha chakula cha kampuni (canteen) kwa wafanyakazi wote kwa bei ya chini au bure kawaida halionekani kama mapato yanayotozwa kodi. Lakini ikiwa kampuni inalipia chakula cha mfanyakazi mmoja mmoja kwenye mgahawa au kutoa posho ya chakula ya pesa — inajumuishwa kwenye mapato ya ajira na inatozwa PAYE. Kwa ufafanuzi zaidi wa hali yako mahususi, thibitisha na mshauri wa kodi wa TRA.",
        "answer_en": "It depends. Meals provided in a company canteen available to all employees at a subsidized or free rate are generally not treated as taxable income. However, if the company pays for individual meals at a restaurant or provides a cash meal allowance — this is included in employment income and is subject to PAYE. For clarity on your specific situation, confirm with a TRA-registered tax consultant.",
        "question_en": "A company pays for an employee's daily lunch at the factory. Is that meal subject to PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — benefits in kind",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "TRA circular on benefits in kind",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_paye_extended_020_20260603",
        "domain": "tier1a",
        "subdomain": "paye_extended",
        "question_sw": "Mfanyakazi ana hisa za kampuni anayofanyia kazi. Anapopata hisa au dividendi — anatozwa PAYE?",
        "answer_sw": "Hisa zinazotolewa kama sehemu ya fidia ya ajira (employee share scheme) zinatozwa PAYE kwa thamani ya soko wakati wa kupewa. Dividendi zinazolipwa kwa hisa hizo baadaye zinatozwa kodi ya kizuizi ya 5% (kwa wakazi wa Tanzania) — si PAYE. Kwa mipango tata ya hisa au options, thibitisha na mshauri wa kodi — muda na thamani ya utozaji unaweza kutofautiana. Rekodi sahihi za thamani ya hisa ni muhimu.",
        "answer_en": "Shares granted as part of employment compensation (employee share scheme) are subject to PAYE at market value at the time of grant. Dividends paid on those shares subsequently are subject to 5% withholding tax (for Tanzania residents) — not PAYE. For complex share schemes or options, confirm with a tax consultant — the timing and value of taxation can vary. Accurate records of share values are essential.",
        "question_en": "An employee holds shares in the company they work for. When they receive shares or dividends — are they subject to PAYE?",
        "primary_source_url": "https://www.tra.go.tz/page/pay-as-you-earn-paye",
        "primary_source_name": "TRA PAYE — share schemes and dividends",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },

    # ── INCOME TAX (15 pairs) ────────────────────────────────────────────────
    {
        "id": "tier1a_income_tax_001_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kiwango cha kodi ya mapato ya kampuni (corporate income tax) Tanzania ni kiasi gani?",
        "answer_sw": "Kiwango cha kawaida cha kodi ya mapato ya kampuni Tanzania ni asilimia 30 ya faida inayotozwa kodi. Kampuni zilizoorodheshwa kwenye Soko la Hisa la Dar es Salaam (DSE) zinapata kiwango cha pungufu cha asilimia 25. Kampuni ndogo zinazofanya biashara kwa njia ya mfumo wa kodi ya makisio (presumptive tax) zinalipa kwa njia tofauti kulingana na mapato. Kiwango hiki kinaweza kubadilika kufuatia Sheria ya Fedha ya kila mwaka.",
        "answer_en": "The standard corporate income tax rate in Tanzania is 30% of taxable profit. Companies listed on the Dar es Salaam Stock Exchange (DSE) benefit from a reduced rate of 25%. Small businesses operating under the presumptive tax system pay at different rates based on turnover. This rate may change following each annual Finance Act.",
        "question_en": "What is the corporate income tax rate in Tanzania?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — Income Tax Act Cap.332",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_002_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Muda wa mwisho wa kuwasilisha return ya kodi ya mapato ya kampuni TRA ni lini?",
        "answer_sw": "Kampuni lazima iwasilishe return ya kodi ya mapato ndani ya miezi sita (6) baada ya mwisho wa mwaka wa fedha. Kwa kampuni nyingi zinazomaliza mwaka wa fedha Desemba 31, tarehe ya mwisho ni Juni 30 ya mwaka unaofuata. Ikiwa mwaka wa fedha unaishia tarehe nyingine, hesabu miezi 6 kutoka tarehe hiyo. Kuchelewa kuwasilisha return kunasababisha adhabu na riba.",
        "answer_en": "A company must file its income tax return within six (6) months after the end of the financial year. For companies with a December 31 year end, the deadline is 30 June of the following year. If the financial year ends on a different date, count 6 months from that date. Late filing attracts penalties and interest.",
        "question_en": "What is the deadline for filing a company income tax return with TRA?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — filing deadlines",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_003_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kodi ya awali (provisional tax) ni nini na kampuni inalipaje?",
        "answer_sw": "Kodi ya awali ni malipo ya mapema ya kodi ya mapato yanayofanywa wakati wa mwaka wa fedha kabla return ya mwisho haijafungwa. Kampuni inalipa kwa awamu tatu: awamu ya kwanza ifikapo mwisho wa mwezi wa 6 wa mwaka wa fedha, ya pili ifikapo mwisho wa mwezi wa 9, na ya tatu ifikapo mwisho wa mwezi wa 12. Kila awamu ni sawa na robo ya kodi inayokadiriwa ya mwaka. Tofauti kati ya kodi ya awali iliyolipwa na kodi halisi ya mwaka inalipwa au kurudishwa wakati return ya mwisho inawasilishwa.",
        "answer_en": "Provisional tax is an advance payment of income tax made during the financial year before the final return is filed. A company pays in three instalments: first instalment by the end of month 6 of the financial year, second by end of month 9, and third by end of month 12. Each instalment equals approximately one quarter of the estimated annual tax. The difference between provisional tax paid and the actual annual tax is settled or refunded when the final return is filed.",
        "question_en": "What is provisional tax and how does a company pay it?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — provisional tax instalments",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_004_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kampuni ya Tanzania inapokea dividendi kutoka kampuni nyingine ya Tanzania. Je, dividendi hiyo inatozwa kodi ya kampuni?",
        "answer_sw": "Dividendi zinazolipwa kati ya kampuni za Tanzania zinazohusika zinalipwa kwa kodi ya kizuizi (withholding tax) ya asilimia 5 wakati zinalipwa — hii inalipwa na kampuni inayolipa dividendi. Mpokeaji wa dividendi (kampuni nyingine ya Tanzania) haijumuishi dividendi hii kwenye mapato yake yanayotozwa kodi ya kampuni, kwa sababu kodi ya kizuizi inamaliza wajibu wa kodi kwa dividendi hiyo.",
        "answer_en": "Dividends paid between resident Tanzanian companies are subject to 5% withholding tax at the time of payment — paid by the company paying the dividend. The recipient company (another Tanzanian company) does not include this dividend in its corporate income tax base, because the withholding tax constitutes full and final settlement of the tax liability on that dividend.",
        "question_en": "A Tanzanian company receives dividends from another Tanzanian company. Is that dividend subject to corporate income tax?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — dividend withholding",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_005_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Gharama zipi za biashara zinaweza kukatwa (deductible) wakati wa kuhesabu kodi ya mapato ya kampuni?",
        "answer_sw": "Gharama zinazoweza kukatwa ni zile zilizotumika kabisa na kipekee kwa ajili ya biashara, zikiwa ni pamoja na: mishahara ya wafanyakazi, kodi ya nyumba ya ofisi au kiwanda, malipo ya mkopo ya biashara (riba), gharama za umeme na maji, gharama za masoko na utangazaji, na uchakavu wa mali (depreciation kwa kiwango kilichoandikwa kisheria). Gharama ambazo haziwezi kukatwa ni pamoja na: faini za kisheria, gharama za kibinafsi za mmiliki, malipo ya kampuni zinazohusiana zaidi ya thamani ya soko, na hongo.",
        "answer_en": "Deductible expenses are those incurred wholly and exclusively for business purposes, including: employee salaries, office or factory rent, business loan interest, electricity and water costs, marketing and advertising expenses, and asset depreciation (at prescribed rates). Non-deductible expenses include: legal fines and penalties, personal expenses of the owner, above-market payments to related parties, and bribes.",
        "question_en": "Which business expenses can be deducted when calculating corporate income tax?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — deductible expenses",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_006_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kampuni inanunua mashine ya TZS 50,000,000. Gharama ya mashine hiyo inakatwa kwa mwaka mmoja au inagawanywa miaka mingi?",
        "answer_sw": "Gharama ya mashine haiwezi kukatwa yote kwa mwaka mmoja. Inagawanywa kwa njia ya uchakavu (depreciation) kulingana na kiwango kilichoandikwa na TRA kulingana na darasa la mali. Kwa mfano, mashine za viwandani mara nyingi zinaangukia darasa la 37.5% kwa njia ya kufuta kwa msingi unaopungua (reducing balance method). Kiwango sahihi kinategemea aina ya mali. TRA inachapisha jedwali la madarasa ya mali na viwango vyake.",
        "answer_en": "The cost of machinery cannot be deducted entirely in one year. It is spread over multiple years through depreciation at rates prescribed by TRA according to the asset class. For example, industrial machinery typically falls in the 37.5% class under the reducing balance method. The exact rate depends on the asset type. TRA publishes a schedule of asset classes and their rates.",
        "question_en": "A company purchases machinery for TZS 50,000,000. Is the cost of the machinery deducted in one year or spread over many years?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — capital allowances",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to depreciation rates",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_007_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kampuni inapata hasara ya TZS 20,000,000 mwaka huu. Je, hasara hiyo inaweza kubebwa mbele na kupunguza kodi ya miaka ijayo?",
        "answer_sw": "Ndiyo. Hasara ya biashara inayothibitishwa na TRA inaweza kubebwa mbele na kutumiwa kupunguza mapato yanayotozwa kodi ya miaka ijayo. Hata hivyo, kuna kikomo cha muda: hasara inaweza kubebwa mbele kwa kipindi fulani tu kulingana na Sheria ya Kodi ya Mapato — thibitisha muda halisi wa sasa na TRA au mshauri wa kodi kwa sababu kanuni hii inapitiwa mara kwa mara. Hasara haiwezi kubebwa nyuma (carry back) nchini Tanzania.",
        "answer_en": "Yes. A business loss confirmed by TRA can be carried forward and used to reduce taxable income in future years. However, there is a time limit: losses can only be carried forward for a specific period under the Income Tax Act — confirm the current period with TRA or a tax consultant as this rule is reviewed periodically. Losses cannot be carried back in Tanzania.",
        "question_en": "A company incurs a loss of TZS 20,000,000 this year. Can that loss be carried forward to reduce tax in future years?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — loss carry forward",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_008_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kodi ya makisio (presumptive tax) ni nini na biashara gani zinaistahili?",
        "answer_sw": "Kodi ya makisio ni mfumo wa kodi uliorahisishwa kwa biashara ndogo ambazo hazihitajiki kutunza vitabu kamili vya uhasibu. Biashara zinazostahili ni zile zenye mapato ya mwaka kati ya TZS 4,000,000 na TZS 100,000,000. Kodi inalipwa kulingana na jedwali la kiwango kilichowekwa awali kulingana na aina ya biashara na eneo — si kwa faida halisi. Biashara zenye mapato zaidi ya TZS 100,000,000 lazima zitumie mfumo wa kawaida wa uhasibu na kodi ya mapato ya kampuni.",
        "answer_en": "Presumptive tax is a simplified tax regime for small businesses that are not required to maintain full accounting records. Eligible businesses are those with annual turnover between TZS 4,000,000 and TZS 100,000,000. Tax is paid according to a predetermined rate schedule based on business type and location — not on actual profit. Businesses with turnover above TZS 100,000,000 must use the normal accounting system and corporate income tax.",
        "question_en": "What is presumptive tax and which businesses qualify for it?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — presumptive tax regime",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to thresholds",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_009_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Tofauti kati ya PAYE na kodi ya mapato ya kampuni ni nini?",
        "answer_sw": "PAYE (Pay As You Earn) ni kodi inayokatwa na mwajiri kutoka mshahara wa mfanyakazi kila mwezi na kuiwasilisha TRA. Ni kodi ya mfanyakazi, si mwajiri. Kodi ya mapato ya kampuni ni kodi inayolipwa na kampuni yenyewe kwenye faida yake baada ya kutoa gharama zinazoruhusiwa. Kampuni inaweza kulipa PAYE kwa niaba ya wafanyakazi wake NA kulipa kodi ya mapato ya kampuni kwenye faida yake — hizi ni wajibu tofauti mbili.",
        "answer_en": "PAYE (Pay As You Earn) is tax withheld by an employer from an employee's salary each month and remitted to TRA. It is the employee's tax, not the employer's. Corporate income tax is tax paid by the company itself on its profits after allowing permitted expenses. A company may pay PAYE on behalf of its employees AND pay corporate income tax on its profits — these are two separate obligations.",
        "question_en": "What is the difference between PAYE and corporate income tax?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax vs PAYE",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "ITA major amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "disambiguation",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_010_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kampuni ya Tanzania inamilikiwa na kampuni mama ya nje. Sheria ya kuzuia uchepushwaji wa faida (thin capitalisation) inaathiri vipi mkopo kutoka kwa kampuni mama?",
        "answer_sw": "Sheria ya udhaifu wa mtaji (thin capitalisation) Tanzania inazuia ukato wa riba inayolipwa kwa mmiliki wa nje ikiwa deni la kampuni linazidi mara tatu ya mtaji wake (uwiano wa 3:1 wa deni kwa mtaji). Riba inayolipwa kwenye deni linalozidi kikomo hiki haiwezi kukatwa kama gharama ya biashara. Kanuni hii inalenga kuzuia kampuni za kimataifa kupeleka faida nje ya Tanzania kwa njia ya mikopo ya bandia yenye riba kubwa. Thibitisha muundo wako wa fedha na mshauri wa kodi.",
        "answer_en": "Tanzania's thin capitalisation rules limit the deductibility of interest paid to a foreign parent company if the company's debt exceeds three times its equity (3:1 debt-to-equity ratio). Interest on debt exceeding this limit cannot be deducted as a business expense. This rule is designed to prevent multinational companies from shifting profits out of Tanzania through artificial high-interest loans. Confirm your financing structure with a tax consultant.",
        "question_en": "A Tanzanian company is owned by a foreign parent. How does the thin capitalisation rule affect loans from the parent company?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — thin capitalisation",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_011_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Mtu mmoja ana nyumba za kupangisha na anapata kodi ya TZS 2,000,000 kwa mwezi. Atalipa kodi ya mapato vipi?",
        "answer_sw": "Mapato ya kodi ya nyumba (rental income) yanapaswa kutangazwa kwenye return ya kodi ya mtu binafsi kila mwaka. Kiwango cha kodi ya makisio kwa mapato ya kodi ni asilimia 15 ya mapato ghafi ya kodi bila gharama kukatwa — hii ni kodi ya mwisho (final withholding). Kama mpangaji ni shirika au biashara iliyosajiliwa, lazima wakatae kodi ya kizuizi ya 15% wakati wanapomlipia mwenye nyumba na kuiwasilisha TRA. Mwenye nyumba binafsi lazima aandikishe mapato hayo kwenye TIN na system ya TRA.",
        "answer_en": "Rental income must be declared in the individual income tax return each year. The withholding tax rate on rental income is 15% of gross rental receipts without deducting expenses — this is a final tax. If the tenant is a registered company or business, they must withhold 15% at the time of paying the landlord and remit it to TRA. The individual landlord must register this income with their TIN in the TRA system.",
        "question_en": "An individual owns rental properties and receives rent of TZS 2,000,000 per month. How do they pay income tax?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA — rental income withholding tax",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_012_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Benki inalipa riba ya TZS 500,000 kwa akaunti ya akiba ya mteja. Je, riba hiyo inatozwa kodi?",
        "answer_sw": "Ndiyo. Riba inayolipwa na benki kwa akaunti za akiba ya wakazi wa Tanzania inatozwa kodi ya kizuizi ya asilimia 10. Benki inakataa kodi hii moja kwa moja na kuiwasilisha TRA kabla mteja hajapata riba yake halisi. Hii ni kodi ya mwisho kwa watu binafsi — hawahitajiki kutangaza riba hii kwenye return ya kodi ya mtu binafsi. Kwa makampuni, riba ya benki inaweza kujumuishwa kwenye mapato ya biashara yanayotozwa kodi ya kawaida.",
        "answer_en": "Yes. Interest paid by a bank on savings accounts for Tanzanian residents is subject to 10% withholding tax. The bank deducts this tax directly and remits it to TRA before the customer receives their net interest. This is a final tax for individuals — they do not need to declare this interest in an individual income tax return. For companies, bank interest may be included in business income subject to normal corporate tax.",
        "question_en": "A bank pays interest of TZS 500,000 on a customer's savings account. Is that interest subject to tax?",
        "primary_source_url": "https://www.tra.go.tz/page/withholding-tax",
        "primary_source_name": "TRA — interest withholding tax",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_013_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kampuni ya uwekezaji iliyoidhinishwa (TIC) inapata msamaha wa kodi. Je, msamaha huo unaweza kudumishwa daima?",
        "answer_sw": "Hapana. Misamaha ya kodi inayotolewa na Kituo cha Uwekezaji Tanzania (TIC) chini ya Sheria ya Uwekezaji wa Tanzania ina kipindi maalum cha miaka kadhaa. Kampuni lazima itimize masharti ya uwekezaji (kama vile mimi wa uwekezaji, idadi ya wafanyakazi, na sekta) kudumisha msamaha. Msamaha unaweza kuondolewa ikiwa masharti hayatimizwi au mwaka wake unaisha bila kuhuishwa. Angalia hati yako ya usajili wa TIC kwa masharti mahususi na muda.",
        "answer_en": "No. Tax incentives granted by the Tanzania Investment Centre (TIC) under the Tanzania Investment Act have a specific period of several years. The company must meet investment conditions (such as investment amount, employee numbers, and sector) to maintain the exemption. The exemption may be withdrawn if conditions are not met or its term expires without renewal. Review your TIC registration certificate for specific conditions and duration.",
        "question_en": "A TIC-approved investment company receives a tax exemption. Can that exemption be maintained permanently?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — TIC investment incentives",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "event_triggered",
        "next_review_trigger": "TIC incentive policy change or Investment Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_014_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kodi ya chini ya lazima (alternative minimum tax) Tanzania ni nini?",
        "answer_sw": "Tanzania ina mfumo wa kodi ya chini ya lazima (AMT) ambao unaweza kutumika kwa kampuni ambazo zinadai hasara au vikato vingi vya kodi na hazilipaji kodi yoyote kwa miaka mingi. Kwa mujibu wa Sheria ya Kodi ya Mapato, kampuni zinazopata mapato ghafi ya zaidi ya kiasi fulani lakini zinadai kutolipa kodi zinaweza kulazimishwa kulipa kiwango cha chini. Maelezo kamili ya mfumo huu na vizingiti vyake thibitisha na mshauri wa kodi wa TRA kwa sababu kanuni zinaweza kubadilika.",
        "answer_en": "Tanzania has an alternative minimum tax (AMT) mechanism that may apply to companies claiming losses or large deductions and paying no tax for many years. Under the Income Tax Act, companies earning above a certain gross income but claiming zero tax liability may be required to pay a minimum amount. For full details on this mechanism and its thresholds, confirm with a TRA-registered tax consultant as the rules may change.",
        "question_en": "What is the alternative minimum tax in Tanzania?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA Corporation Tax — alternative minimum tax",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "formal",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_income_tax_015_20260603",
        "domain": "tier1a",
        "subdomain": "income_tax",
        "question_sw": "Kampuni inalijaza return ya kodi ya mapato kwenye mfumo gani wa TRA?",
        "answer_sw": "Kampuni inawasilisha return ya kodi ya mapato kupitia mfumo wa mtandaoni wa TRA unaojulikana kama IDRAS (Integrated Domestic Revenue Administration System) au mfumo wake wa kibinafsi wa TRA e-filing. Kampuni lazima iwe na TIN iliyosajiliwa na akaunti ya IDRAS. Baada ya kujaza return mtandaoni, malipo yanafanywa kupitia GePG (Government e-Payment Gateway) — benki au simu za pesa zinazoungana na mfumo huu. Epuka kuwasilisha kwa karatasi kwa sababu TRA inasisitiza e-filing.",
        "answer_en": "A company submits its income tax return through TRA's online system known as IDRAS (Integrated Domestic Revenue Administration System) or TRA's own e-filing platform. The company must have a registered TIN and an IDRAS account. After completing the online return, payment is made via GePG (Government e-Payment Gateway) — banks or mobile money services connected to this system. Avoid paper filing as TRA emphasises e-filing.",
        "question_en": "Through which TRA system does a company file its income tax return?",
        "primary_source_url": "https://www.tra.go.tz/page/corporation-tax",
        "primary_source_name": "TRA — IDRAS e-filing system",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "TRA system change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },

    # ── BUSINESS LICENSING (15 pairs) ─────────────────────────────────────────
    {
        "id": "tier1a_biz_lic_001_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Nini tofauti kati ya usajili wa biashara BRELA na leseni ya biashara ya serikali ya mtaa?",
        "answer_sw": "BRELA (Business Registrations and Licensing Agency) inasajili biashara kisheria — yaani inazipa hadhi ya kisheria ya kufanya biashara Tanzania kama kampuni au jina la biashara. Leseni ya biashara ya serikali ya mtaa (LGA) ni ruhusa ya kufanya shughuli mahususi katika eneo la mtaa fulani — inatolewa na Halmashauri husika. Biashara nyingi zinahitaji ZOTE mbili: usajili wa BRELA kwanza, kisha leseni ya LGA ya eneo unakofanya biashara. Ni wajibu tofauti mbili za kisheria.",
        "answer_en": "BRELA (Business Registrations and Licensing Agency) legally registers a business — giving it a legal identity to operate in Tanzania as a company or business name. The Local Government Authority (LGA) business licence is a permit to conduct specific activities in a particular area — issued by the relevant council. Most businesses need BOTH: BRELA registration first, then an LGA licence for the area where they operate. They are two separate legal obligations.",
        "question_en": "What is the difference between BRELA business registration and a local government business licence?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — business registration vs LGA licensing",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Business Activities Registration Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "disambiguation",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_002_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Leseni ya biashara ya serikali ya mtaa inatoka kwa nani na inahusu nini hasa?",
        "answer_sw": "Leseni ya biashara inatolewa na Halmashauri ya Manispaa, Mji, au Wilaya (LGA) ambapo biashara inafanywa. Inaidhinisha aina ya shughuli za biashara zinazoruhusiwa, idadi ya watumishi, na eneo. Inahitajika kwa biashara zote zinazofanya kazi katika Tanzania Bara, ikiwa ni pamoja na maduka, migahawa, ofisi za ushauri, na biashara za mitaani. Leseni inahitajika kuhuishwa kila mwaka — kawaida ifikapo Januari 31.",
        "answer_en": "A business licence is issued by the Municipal, Town, or District Council (LGA) where the business operates. It authorises the specific types of business activities permitted, number of employees, and location. It is required for all businesses operating in Tanzania Mainland, including shops, restaurants, consulting offices, and street vendors. The licence must be renewed annually — usually by 31 January.",
        "question_en": "Who issues a local government business licence and what specifically does it cover?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — LGA business licence",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Local Government Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_003_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Adhabu gani inatumika kwa biashara inayofanya kazi bila leseni ya serikali ya mtaa?",
        "answer_sw": "Kufanya biashara bila leseni ya LGA ni kosa la kisheria nchini Tanzania. Adhabu zinaweza kujumuisha: faini za pesa, kufungwa kwa biashara hadi leseni ipatikane, na hata mashtaka ya jinai dhidi ya mmiliki wa biashara. Mwanzo kawaida ni onyo na faini la awali, lakini ufuatiliaji unaweza kusababisha kufungwa kwa biashara. Halmashauri nyingi zina maafisa wa ukaguzi wanaosafiri mara kwa mara kuangalia leseni. Usijaribu kufanya biashara bila leseni — gharama ya leseni ni ndogo ukilinganisha na adhabu.",
        "answer_en": "Operating a business without an LGA licence is a criminal offence in Tanzania. Penalties may include: monetary fines, closure of the business until a licence is obtained, and even criminal prosecution of the business owner. The initial response is typically a warning and an initial fine, but continued non-compliance can lead to business closure. Many councils have inspection officers who patrol regularly to check licences. Do not attempt to operate without a licence — the licence cost is small compared to the penalties.",
        "question_en": "What penalty applies to a business operating without a local government licence?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — LGA licence compliance",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Local Government Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_004_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Mgahawa wangu unahitaji leseni maalum zaidi ya leseni ya kawaida ya LGA?",
        "answer_sw": "Ndiyo. Mgahawa na biashara za chakula zinahitaji leseni maalum za ziada, ambazo ni pamoja na: leseni ya chakula (food handling certificate) kutoka kwa Mamlaka ya Chakula na Dawa Tanzania (TFDA/TMDA), cheti cha afya (health certificate) cha watumishi wote wanaoshughulikia chakula, ukaguzi wa mazingira na usafi wa mazingira (environmental health inspection) kutoka Halmashauri, na wakati mwingine leseni ya biashara ya vinywaji. Ukaguzi wa mara kwa mara hufanywa na maafisa wa afya wa Halmashauri.",
        "answer_en": "Yes. Restaurants and food businesses require additional special licences beyond the standard LGA licence, including: a food handling certificate from the Tanzania Food and Drugs Authority (TFDA/TMDA), health certificates for all food handlers, an environmental and public health inspection from the Council, and sometimes a beverages business licence. Regular inspections are carried out by council health officers.",
        "question_en": "Does my restaurant need additional licences beyond the standard LGA licence?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA + TMDA — food business licensing",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "TMDA Act amendment or LGA licence category change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_005_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Biashara yangu ya uuzaji wa pombe inahitaji nini zaidi ya leseni ya LGA?",
        "answer_sw": "Uuzaji wa pombe (mvinyo, bia, na vinywaji vikali) unahitaji leseni maalum ya vinywaji vikali (liquor licence) inayotolewa na Halmashauri husika. Tanzania ina kanuni kali za usalama wa vinywaji: uuzaji kwa watoto chini ya miaka 18 ni kosa la jinai. Muda wa kufungua duka la pombe pia udhibitiwa na Halmashauri. Zaidi ya hayo, biashara za kutengeneza pombe (breweries) zinahitaji leseni za ziada kutoka TRA (excise duty registration) na TMDA. Nenda Halmashauri yako kwa fomu za leseni ya vinywaji.",
        "answer_en": "Selling alcohol (wine, beer, and spirits) requires a special liquor licence issued by the relevant Council. Tanzania has strict alcohol safety regulations: selling to children under 18 is a criminal offence. Opening hours for alcohol outlets are also regulated by the Council. Additionally, businesses manufacturing alcohol (breweries) require additional licences from TRA (excise duty registration) and TMDA. Go to your Council for liquor licence application forms.",
        "question_en": "My alcohol sales business needs what beyond the standard LGA licence?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA + LGA — liquor licence requirements",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Liquor Act or LGA regulation amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_006_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Biashara ya kuhamisha pesa (money transfer) inahitaji leseni gani Tanzania?",
        "answer_sw": "Biashara ya kuhamisha pesa inahitaji leseni ya maalum kutoka Benki Kuu ya Tanzania (BoT) chini ya Sheria ya Huduma za Malipo ya Mwaka 2015. Hii ni pamoja na: wakala wa kampuni kubwa ya pesa kama M-Pesa au Airtel Money (wanayohitaji idhini ya kampuni mama), au mwenye leseni wa kujitegemea wa huduma za malipo. Leseni za BoT ni za aina nyingi — thibitisha aina ya huduma unayotaka kutoa. GN 487A (Julai 2025) pia inapiga marufuku raia wasio Watanzania kufanya biashara ya kuhamisha pesa.",
        "answer_en": "A money transfer business requires a special licence from the Bank of Tanzania (BoT) under the Payment Services Act 2015. This includes: being an agent of a large money company like M-Pesa or Airtel Money (requiring parent company authorisation), or being an independent licensed payment service provider. BoT licences come in multiple categories — confirm the type of service you wish to provide. GN 487A (July 2025) also prohibits non-Tanzanian citizens from conducting money transfer business.",
        "question_en": "What licence does a money transfer business need in Tanzania?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BoT Payment Services Act 2015 + GN 487A",
        "source_type": "government_portal",
        "effective_date": "2025-07-28",
        "decay_risk": "event_triggered",
        "next_review_trigger": "BoT Payment Services Act amendment or GN 487A revision",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_007_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Biashara ya utalii (tour operator) inahitaji leseni gani Tanzania?",
        "answer_sw": "Biashara ya utalii inahitaji leseni ya mwendeshaji wa utalii (tour operator licence) kutoka Bodi ya Utalii Tanzania (TTB — Tanzania Tourist Board). Pia inahitaji: usajili wa BRELA kama kampuni au jina la biashara, leseni ya LGA ya halmashauri husika, na TIN/VAT ikiwa mapato yanazidi kizingiti. Kwa safari za mwituni (wildlife safaris), leseni ya ziada kutoka TAWA (Tanzania Wildlife Authority) inaweza kuhitajika. Leseni ya TTB inahuishwa kila mwaka na inahitaji uthibitisho wa uwezo wa kifedha na kitaaluma.",
        "answer_en": "A tourism business requires a tour operator licence from the Tanzania Tourist Board (TTB). It also requires: BRELA registration as a company or business name, an LGA licence from the relevant council, and TIN/VAT if income exceeds the threshold. For wildlife safaris, an additional licence from TAWA (Tanzania Wildlife Authority) may be required. The TTB licence is renewed annually and requires proof of financial and professional capacity.",
        "question_en": "What licence does a tourism business (tour operator) need in Tanzania?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "TTB — tour operator licence + BRELA",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Tourism Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_008_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Kampuni ya ujenzi inahitaji leseni gani kabla ya kuanza kuchukua mikataba ya ujenzi?",
        "answer_sw": "Kampuni ya ujenzi lazima iandikishwe na Bodi ya Usajili wa Wakandarasi (CRB — Contractors Registration Board) chini ya Wizara ya Ujenzi. CRB ina madarasa ya usajili (darasa A hadi G) kulingana na uwezo wa fedha na uzoefu wa kampuni. Mkataba wa ujenzi unaozidi kiwango cha darasa la kampuni hauwezi kukubaliwa kisheria. Pia inahitaji: usajili wa BRELA, leseni ya LGA, TIN, na wakati mwingine vibali vya mazingira. Usajili wa CRB unahuishwa kila mwaka.",
        "answer_en": "A construction company must register with the Contractors Registration Board (CRB) under the Ministry of Works. CRB has registration classes (Class A through G) based on the company's financial capacity and experience. A construction contract exceeding the company's class limit cannot be legally accepted. Also required: BRELA registration, LGA licence, TIN, and sometimes environmental permits. CRB registration is renewed annually.",
        "question_en": "What licence does a construction company need before taking on construction contracts?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "CRB — contractor registration + BRELA",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "CRB Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_009_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Kampuni ya dawa au kliniki ya kibinafsi inahitaji leseni gani Tanzania?",
        "answer_sw": "Kliniki ya kibinafsi na duka la dawa vinahitaji: idhini ya kufungua (facility licence) kutoka Wizara ya Afya au Bodi ya Madawa Tanzania (Medical Council of Tanganyika), usajili wa daktari/mfamasia kutoka Baraza la Madawa (MCT) au Baraza la Wauguzi, leseni ya TMDA kwa biashara za dawa, leseni ya LGA ya halmashauri husika, na usajili wa BRELA. Ukaguzi wa TMDA hufanywa kabla ya kufungua na mara kwa mara baada ya kufungua. Kufungua bila idhini ni kosa zito la jinai.",
        "answer_en": "A private clinic and pharmacy require: a facility operating licence from the Ministry of Health or Medical Council of Tanganyika (MCT), individual registration of the doctor/pharmacist from MCT or Nursing Council, a TMDA licence for pharmaceutical businesses, an LGA licence from the relevant council, and BRELA registration. TMDA inspection is conducted before opening and periodically thereafter. Opening without authorisation is a serious criminal offence.",
        "question_en": "What licence does a pharmaceutical company or private clinic need in Tanzania?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "TMDA + MCT + BRELA — medical facility licensing",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Medical Practitioners Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_010_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Nnataka kuingiza bidhaa kutoka nje ya nchi na kuzisambaza Tanzania. Ninahitaji leseni ya uingizaji bidhaa?",
        "answer_sw": "Ndiyo. Uingizaji wa bidhaa Tanzania unahitaji: TIN iliyosajiliwa na TRA, nambari ya msimbo wa biashara (TIN-based importer code) kutoka TRA, na wakati mwingine leseni maalum ya bidhaa fulani — kwa mfano, dawa (TMDA), chakula (TMDA), silaha (Wizara ya Mambo ya Ndani). Bidhaa zote zinazoingia Tanzania zinapita forodha na zinaweza kukaguliwa. Ikiwa unaingiza zaidi ya TZS 200,000,000 kwa mwaka, ulazimishwa kusajili VAT. Angalia pia orodha ya bidhaa zilizopigwa marufuku au zinazohitaji vibali maalum.",
        "answer_en": "Yes. Importing goods to Tanzania requires: a TIN registered with TRA, an importer code (TIN-based) from TRA, and sometimes a specific product licence — for example, medicines (TMDA), food (TMDA), weapons (Ministry of Interior). All goods entering Tanzania pass through customs and may be inspected. If you import more than TZS 200,000,000 per year, VAT registration is required. Also check the list of prohibited goods or goods requiring special permits.",
        "question_en": "I want to import goods from abroad and distribute them in Tanzania. Do I need an import licence?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "TRA + BRELA — import licence requirements",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment or TMDA regulation change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_011_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Biashara yangu inafanywa mtandaoni tu — siuzi bidhaa za kimwili, ninauza huduma za kidijitali. Je, ninahitaji leseni yoyote?",
        "answer_sw": "Ndiyo. Biashara za mtandaoni (online businesses) Tanzania zinahitaji usajili wa kawaida wa biashara: usajili wa BRELA kama jina la biashara au kampuni, TIN kutoka TRA, na leseni ya LGA ikiwa una ofisi au anwani ya biashara. Pia, tangu Sheria ya Fedha 2022, huduma za kidijitali zinazotolewa nchini Tanzania zinatozwa Kodi ya Huduma za Kidijitali (Digital Service Tax — DST) ya asilimia 2 ya mapato ghafi. Ikiwa mapato yako yanazidi kizingiti cha VAT, lazima usajili VAT pia.",
        "answer_en": "Yes. Online businesses in Tanzania require standard business registration: BRELA registration as a business name or company, a TIN from TRA, and an LGA licence if you have an office or business address. Also, since the Finance Act 2022, digital services provided in Tanzania are subject to Digital Service Tax (DST) of 2% of gross revenue. If your income exceeds the VAT threshold, VAT registration is also required.",
        "question_en": "My business operates online only — I don't sell physical goods, just digital services. Do I need any licence?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA + TRA — online business registration",
        "source_type": "government_portal",
        "effective_date": "2022-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to DST",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_012_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Faida za kufanya biashara ndani ya Eneo Maalum la Uchumi (Special Economic Zone — SEZ) Tanzania ni zipi?",
        "answer_sw": "Biashara zilizoidhinishwa kwenye SEZ Tanzania zinapata faida kadhaa: msamaha wa kodi ya mapato ya kampuni kwa miaka 10 ya kwanza, msamaha wa VAT na ushuru wa forodha kwenye bidhaa za uingizaji zinazotumiwa kwenye uzalishaji, msamaha wa SDL, na msamaha wa mrabaha wa ardhi. Baada ya miaka 10, kiwango cha kodi kinapungua. Usajili unafanywa kupitia Mamlaka ya Maeneo Maalum ya Uchumi Tanzania (EPZA/SEZA). Bidhaa zinazotengenezwa SEZ zinaweza kuuzwa nje ya nchi au ndani ya Tanzania (na ushuru wa forodha unaotumika kwa mauzo ya ndani).",
        "answer_en": "Businesses approved in a Tanzania SEZ receive several benefits: corporate income tax exemption for the first 10 years, VAT and customs duty exemption on imported inputs used in production, SDL exemption, and land rent exemption. After 10 years, a reduced tax rate applies. Registration is through the Tanzania Special Economic Zones Authority (EPZA/SEZA). Goods manufactured in an SEZ can be exported or sold domestically (with applicable customs duty on domestic sales).",
        "question_en": "What are the benefits of operating a business within a Special Economic Zone (SEZ) in Tanzania?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "EPZA/SEZA — SEZ incentives",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "annual",
        "next_review_trigger": "SEZ Act amendment or Finance Act",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_013_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Kampuni ya media (radio, televisheni, au gazeti) inahitaji leseni gani Tanzania?",
        "answer_sw": "Kampuni za media Tanzania zinahitaji leseni kutoka Mamlaka ya Mawasiliano Tanzania (TCRA — Tanzania Communications Regulatory Authority). Redio na televisheni zinahitaji leseni ya utangazaji (broadcasting licence) na leseni ya maudhui (content licence). Magazeti yanahitaji usajili wa chapisho (publication registration) kutoka Wizara ya Habari. Yote yanahitaji pia: usajili wa BRELA, TIN, na leseni ya LGA. Leseni ya TCRA ina ada na masharti ya kufuata kanuni za utangazaji.",
        "answer_en": "Media companies in Tanzania require a licence from the Tanzania Communications Regulatory Authority (TCRA). Radio and television stations need a broadcasting licence and a content licence. Newspapers require publication registration from the Ministry of Information. All also require: BRELA registration, TIN, and an LGA licence. The TCRA licence has fees and conditions to comply with broadcasting regulations.",
        "question_en": "What licence does a media company (radio, television, or newspaper) need in Tanzania?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "TCRA + BRELA — media licensing",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Electronic and Postal Communications Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_014_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Biashara yangu ya kuuza bidhaa mtandaoni inatumia Jumia au platform nyingine. Je, ninahitaji leseni tofauti ya kuuza mtandaoni?",
        "answer_sw": "Hapana leseni ya ziada maalum ya mauzo ya mtandaoni peke yake. Lakini biashara yako inahitaji: usajili wa BRELA (ikiwa bado hujafanya), TIN, na leseni ya LGA ikiwa una eneo la biashara. Kama mnunuzi ni biashara iliyosajiliwa na ununuzi unazidi TZS 500,000, wanalazimika kukata kodi ya kizuizi. Ikiwa mapato yako ya jumla yanazidi kizingiti cha VAT (TZS 200,000,000/mwaka), lazima usajili VAT na kutoa risiti za EFD au VFD kwa malipo yote.",
        "answer_en": "No special separate licence specifically for online selling alone. But your business requires: BRELA registration (if not yet done), a TIN, and an LGA licence if you have a physical business location. If the buyer is a registered business and the purchase exceeds TZS 500,000, they are required to withhold tax. If your total income exceeds the VAT threshold (TZS 200,000,000/year), you must register for VAT and issue EFD/VFD receipts for all payments.",
        "question_en": "My business sells products online through Jumia or another platform. Do I need a special online selling licence?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA + TRA — e-commerce registration",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment or TRA e-commerce circular",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_biz_lic_015_20260603",
        "domain": "tier1a",
        "subdomain": "business_licensing",
        "question_sw": "Leseni ya biashara ya LGA inahuishwa lini na ada yake inategemeana na nini?",
        "answer_sw": "Leseni ya biashara ya LGA lazima ihuishwe kila mwaka, kawaida ifikapo tarehe 31 Januari. Kuchelewa kuhuisha kunasababisha faini za ucheleweshaji. Ada ya leseni inategemea aina ya biashara, ukubwa wake (kulingana na mapato au eneo la jengo), na halmashauri husika. Ada zinaweza kutofautiana sana kati ya halmashauri moja na nyingine. Nenda ofisi ya halmashauri yako na hati za biashara kujua ada halisi ya mwaka huu na tarehe ya mwisho ya malipo.",
        "answer_en": "The LGA business licence must be renewed annually, usually by 31 January. Late renewal attracts delay penalties. The licence fee depends on the type of business, its size (based on income or floor space), and the relevant council. Fees can vary significantly between different councils. Go to your council office with business documents to find out the exact fee for this year and the payment deadline.",
        "question_en": "When is the LGA business licence renewed and what does the fee depend on?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA + LGA — annual licence renewal",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "annual",
        "next_review_trigger": "LGA fee schedule change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
]

# Load existing questions for dedup check
dedup_path = os.path.join(ROOT, "datasets", "tier1a", "raw_sources", "existing_questions.txt")
existing_questions = set()
if os.path.exists(dedup_path):
    with open(dedup_path, encoding="utf-8") as f:
        existing_questions = {line.strip().lower() for line in f if line.strip()}

# Dedup filter
filtered = []
skipped = 0
for pair in BATCH_C:
    q_sw = pair["question_sw"].lower().strip()
    q_en = pair["question_en"].lower().strip()
    if q_sw in existing_questions or q_en in existing_questions:
        print(f"  SKIP (duplicate): {pair['id']}")
        skipped += 1
    else:
        filtered.append(pair)
        existing_questions.add(q_sw)
        existing_questions.add(q_en)

print(f"Batch C: {len(filtered)} new pairs, {skipped} skipped as duplicates")

# Append to batch_002
batch_path = os.path.join(ROOT, "datasets", "tier1a", "raw_sources", "raw_pairs_batch_002.jsonl")
existing_pairs = []
with open(batch_path, encoding="utf-8") as f:
    for line in f:
        existing_pairs.append(json.loads(line))

all_pairs = existing_pairs + filtered
with open(batch_path, "w", encoding="utf-8") as out:
    for p in all_pairs:
        out.write(json.dumps(p, ensure_ascii=False) + "\n")

print(f"batch_002 now has {len(all_pairs)} pairs")

# Update existing_questions.txt
with open(dedup_path, "w", encoding="utf-8") as out:
    for q in sorted(existing_questions):
        out.write(q + "\n")
print(f"existing_questions.txt updated: {len(existing_questions)} questions")
