"""
Generate Batch D: 43 pairs
- stamp_duty: 10 pairs (tier1a_stamp_duty_001..010_20260603)
- skills_levy_ext: 8 pairs (tier1a_sdl_ext_001..008_20260603)
- nssf_disputes: 8 pairs (tier1a_nssf_disp_001..008_20260603)
- brela_changes: 10 pairs (tier1a_brela_chg_001..010_20260603)
- tax_disputes: 7 pairs (tier1a_tax_disp_001..007_20260603)

Sources:
- stamp_duty: datasets/tier1a/raw_sources/scraped/stamp_duty.html (confirmed rates)
- skills_levy: CLAUDE.md locked facts (Finance Act 2025)
- nssf_disputes: datasets/tier1a/raw_sources/scraped/nssf2.html
- brela_changes: datasets/tier1a/raw_sources/scraped/brela2.html
- tax_disputes: CLAUDE.md locked facts (ITA Cap.332)
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

BATCH_D = [
    # ── STAMP DUTY (10 pairs) ────────────────────────────────────────────────
    # Confirmed from stamp_duty.html: 30-day rule, specific rates per schedule
    {
        "id": "tier1a_stamp_duty_001_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Kodi ya stempu (stamp duty) ni nini na nyaraka gani zinaathirika nazo Tanzania?",
        "answer_sw": "Kodi ya stempu ni ushuru unaolipwa kwa hati maalum zinazotajwa kwenye Sheria ya Kodi ya Stempu (Stamp Duty Act, Cap. 189). Hati zinazohitaji kodi ya stempu ni pamoja na: mikataba ya manunuzi ya mali isiyohamia (ardhi/nyumba), makubaliano ya kukodi (lease/tenancy agreements), uhamishaji wa hisa za kampuni, makubaliano ya mikopo, hati za kuasisi ushirika, na mamlaka ya mwakilishi (power of attorney). Hati isiyopigwa stempu haiwezi kutumika kama ushahidi mahakamani.",
        "answer_en": "Stamp duty is a tax paid on specified documents listed under the Stamp Duty Act (Cap. 189). Documents requiring stamp duty include: conveyances of immovable property (land/buildings), lease and tenancy agreements, transfer of company shares, loan agreements, partnership deeds, and powers of attorney. A document without stamp duty cannot be admitted as evidence in court.",
        "question_en": "What is stamp duty and which documents are subject to it in Tanzania?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty — Stamp Duty Act Cap.189",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to stamp duty schedule",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_002_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Kiwango cha kodi ya stempu kwenye uhamishaji wa hisa za kampuni (share transfer) ni kiasi gani?",
        "answer_sw": "Kiwango cha kodi ya stempu kwenye uhamishaji wa hisa ni asilimia 1 ya thamani ya hisa iliyoidhinishwa na bodi (the value of the shares as approved by the Board). Hii inatumika kwa hisa za kampuni zilizosajiliwa Tanzania, hati za deni (debentures), na faida inayohusiana na hati za amana, bima, au dhamana. Mwuzaji wa hisa kwa kawaida ndiye anayebeba wajibu wa kulipa kodi ya stempu, isipokuwa pande mbili zikubaliane vinginevyo.",
        "answer_en": "The stamp duty rate on share transfers is 1% of the value of the shares as approved by the Board. This applies to shares in Tanzanian registered companies, debentures, and interests secured by bonds, mortgage deeds, or insurance policies. The seller of the shares is typically the party bearing the stamp duty obligation unless the two parties agree otherwise.",
        "question_en": "What is the stamp duty rate on a company share transfer?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty Act Cap.189 — share transfer schedule",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_003_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Kodi ya stempu kwenye mkataba wa kukodi nyumba (tenancy/lease agreement) inahesabiwaje?",
        "answer_sw": "Kodi ya stempu kwenye mkataba wa kukodi nyumba au ardhi ni asilimia 1 ya kodi ya mwaka iliyowekwa (annual reserved rent) — hii inatumika kwa mikataba yote ya kukodi bila kujali muda. Kwa mfano, kodi ya TZS 500,000 kwa mwezi = kodi ya mwaka TZS 6,000,000. Kodi ya stempu = 1% × 6,000,000 = TZS 60,000. Mkataba lazima upigwe stempu ndani ya siku 30 baada ya kutiwa saini, vinginevyo adhabu inatumika.",
        "answer_en": "Stamp duty on a tenancy or lease agreement is 1% of the annual reserved rent — this applies to all lease agreements regardless of duration. For example, rent of TZS 500,000 per month = annual rent TZS 6,000,000. Stamp duty = 1% × 6,000,000 = TZS 60,000. The agreement must be stamped within 30 days of signing, otherwise a penalty applies.",
        "question_en": "How is stamp duty on a tenancy/lease agreement calculated?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty Act Cap.189 — lease schedule",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_004_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Kodi ya stempu kwenye uhamishaji wa ardhi au nyumba (property transfer) ni kiasi gani?",
        "answer_sw": "Kodi ya stempu kwenye mabadiliko ya mali isiyohamia (exchange of property) ni asilimia 0.5 kwa TZS 100,000 ya kwanza ya thamani, kisha asilimia 1 ya thamani inayozidi TZS 100,000. Zaidi ya hilo, uhamishaji wa ardhi na nyumba unaweza pia kuathiriwa na Kodi ya Faida ya Mtaji (Capital Gains Tax). Thibitisha mahesabu na mshauri wa kodi kwa miamala mikubwa ya mali isiyohamia.",
        "answer_en": "Stamp duty on an exchange of immovable property (land or buildings) is 0.5% on the first TZS 100,000 of value, then 1% on the value exceeding TZS 100,000. Additionally, transfer of land and buildings may also attract Capital Gains Tax. Confirm calculations with a tax consultant for large immovable property transactions.",
        "question_en": "What is the stamp duty rate on a land or building transfer (property transfer)?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty Act Cap.189 — property exchange schedule",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_005_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Makubaliano ya mkopo kati ya kampuni mbili yanahitaji kodi ya stempu?",
        "answer_sw": "Ndiyo. Makubaliano ya mkopo (loan agreement) yanajumuishwa kwenye hati zinazohitaji kodi ya stempu. Kiwango kinatofautiana kulingana na aina ya hati: kama ni 'agreement or memorandum of agreement' ya kawaida, kodi ya stempu ni TZS 2,000. Kwa hati za pawn, hypothecation, au deposit ya hati za umiliki wa mali (title deeds), kodi ni pia TZS 2,000. Makubaliano ya mkopo lazima yapigwe stempu ndani ya siku 30 baada ya kutiwa saini.",
        "answer_en": "Yes. Loan agreements are included among instruments requiring stamp duty. The rate depends on the type of instrument: for a standard 'agreement or memorandum of agreement', stamp duty is TZS 2,000. For instruments of pawn, hypothecation, or deposit of title deeds, the duty is also TZS 2,000. Loan agreements must be stamped within 30 days of signing.",
        "question_en": "Does a loan agreement between two companies require stamp duty?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty Act Cap.189 — agreement schedule",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_006_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Ndani ya muda gani hati lazima ipigwe stempu baada ya kutiwa saini?",
        "answer_sw": "Hati zote zinazohitaji kodi ya stempu zilizotiwa saini Tanzania lazima zipigwe stempu ndani ya siku 30 (thelathini) baada ya kutiwa saini. Kama hati imetiwa saini nje ya Tanzania lakini inahusiana na mali au jambo linalofanywa Tanzania, nayo lazima ipigwe stempu ndani ya siku 30 baada ya kuingia Tanzania. Wakati wa kupeleka hati kwa Afisa wa Stempu kwa tathmini (adjudication), siku hizo hazihesabiwi kwenye siku 30.",
        "answer_en": "All instruments requiring stamp duty that are signed in Tanzania must be stamped within 30 (thirty) days of signing. If an instrument is signed outside Tanzania but relates to property or a matter performed in Tanzania, it must also be stamped within 30 days of entering Tanzania. The time period during which the instrument is lodged with the Stamp Duty Officer for adjudication is excluded from the 30-day period.",
        "question_en": "Within what period must a document be stamped after it is signed?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty Act Cap.189 — 30-day rule",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "Stamp Duty Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_007_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Adhabu gani inatumika kwa hati isiyopigwa stempu inayowasilishwa mahakamani?",
        "answer_sw": "Hati isiyopigwa stempu haiwezi kukubalika kama ushahidi mahakamani bila kwanza kulipa kodi ya stempu inayostahili pamoja na adhabu inayotozwa na Mahakama. Pia, mtu anayetumia hati isiyo na stempu kama ushahidi anaweza kulazimishwa kulipa kodi ya stempu yenyewe. Zaidi ya hayo, Sheria ya Kodi ya Stempu ina adhabu za jinai kwa kukwepa kwa makusudi. Daima piga stempu hati ndani ya siku 30 kuepuka matatizo makubwa mahakamani.",
        "answer_en": "A document without stamp duty cannot be admitted as evidence in court without first paying the applicable stamp duty plus a penalty imposed by the Court. Additionally, a person seeking to use an unstamped document as evidence may be ordered to pay the stamp duty themselves. Furthermore, the Stamp Duty Act carries criminal penalties for deliberate evasion. Always stamp documents within 30 days to avoid major problems in court.",
        "question_en": "What penalty applies to an unstamped document submitted as evidence in court?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty Act Cap.189 — penalties for unstamped instruments",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "Stamp Duty Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_008_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Je, kuna msamaha wowote wa kodi ya stempu Tanzania?",
        "answer_sw": "Ndiyo. Kuna baadhi ya misamaha ya kodi ya stempu chini ya Sheria ya Kodi ya Stempu, ikiwa ni pamoja na: hati zinazofanywa na au kwa ajili ya Serikali ya Tanzania, hati zinazohusiana na mazingira ya dharura ya umma, na hati maalum zilizoorodheshwa kwenye jedwali la msamaha wa sheria. Wakati wa shaka kuhusu kama hati yako inastahili msamaha, wasiliana na Afisa wa Stempu wa TRA au ofisi ya TRA iliyo karibu nawe.",
        "answer_en": "Yes. There are some stamp duty exemptions under the Stamp Duty Act, including: instruments made by or for the Government of Tanzania, instruments relating to public emergency circumstances, and specific instruments listed in the exemption schedule of the Act. When in doubt about whether your document qualifies for an exemption, contact the TRA Stamp Duty Officer or your nearest TRA office.",
        "question_en": "Are there any stamp duty exemptions in Tanzania?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty Act Cap.189 — exemptions",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to stamp duty exemptions",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_009_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Kodi ya stempu inalipwa vipi kwa TRA?",
        "answer_sw": "Kodi ya stempu inalipwa kupitia mfumo wa GePG (Government e-Payment Gateway) au moja kwa moja kwenye ofisi za TRA. Unaweza kulipa kupitia benki zinazoshiriki au simu za pesa zilizounganishwa na GePG. Baada ya malipo, hati inapelekwa kwa Afisa wa Stempu wa TRA ili atiwe muhuri (stamped). Unaweza pia kuwasiliana na ofisi ya TRA au kituo cha huduma za TRA kwa msaada wa mchakato.",
        "answer_en": "Stamp duty is paid through the GePG (Government e-Payment Gateway) system or directly at TRA offices. You can pay through participating banks or mobile money services connected to GePG. After payment, the document is taken to the TRA Stamp Duty Officer for stamping. You can also contact a TRA office or TRA service centre for assistance with the process.",
        "question_en": "How is stamp duty paid to TRA?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty — GePG payment",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "TRA payment system change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_stamp_duty_010_20260603",
        "domain": "tier1a",
        "subdomain": "stamp_duty",
        "question_sw": "Wakati kampuni mpya inaandikishwa, Hati ya Kuasisi Ushirika (Memorandum of Association) inahitaji kodi ya stempu?",
        "answer_sw": "Ndiyo. Memorandum of Association ya kampuni inahitaji kodi ya stempu ya TZS 10,000 kulingana na jedwali la Sheria ya Kodi ya Stempu. Hati hii lazima ipigwe stempu wakati wa usajili wa kampuni au kabla ya hapo. Kwa ushirika (partnership), ada ya kodi ya stempu inategemea mtaji wa ushirika: TZS 1,000 kama mtaji hauzidi TZS 10,000; TZS 5,000 kama mtaji kati ya TZS 100,000 na TZS 1,000,000; na TZS 10,000 katika hali nyingine.",
        "answer_en": "Yes. A company's Memorandum of Association requires stamp duty of TZS 10,000 under the schedule of the Stamp Duty Act. This document must be stamped at the time of company registration or earlier. For a partnership deed, the stamp duty depends on the partnership capital: TZS 1,000 if capital does not exceed TZS 10,000; TZS 5,000 if capital is between TZS 100,000 and TZS 1,000,000; and TZS 10,000 in other cases.",
        "question_en": "When a new company is registered, does the Memorandum of Association require stamp duty?",
        "primary_source_url": "https://www.tra.go.tz/page/stamp-duty",
        "primary_source_name": "TRA Stamp Duty Act Cap.189 — MoA and partnership schedule",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },

    # ── SKILLS LEVY EXTENDED (8 pairs) ─────────────────────────────────────
    {
        "id": "tier1a_sdl_ext_001_20260603",
        "domain": "tier1a",
        "subdomain": "skills_levy_extended",
        "question_sw": "Waajiri wa EPZ (Export Processing Zone) wanaweza kusamehewa SDL?",
        "answer_sw": "Kampuni zilizosajiliwa rasmi kwenye EPZ Tanzania zinaweza kupata msamaha wa SDL kama sehemu ya msururu wa motisha za uwekezaji. Hata hivyo, msamaha huu si wa kiotomatiki — kampuni lazima ithibitishe hadhi yake ya EPZ na EPZA na kupata idhini maalum ya msamaha kutoka TRA. Angalia hati yako ya usajili wa EPZ kwa masharti. Ikiwa hujapata msamaha rasmi, wajibu wa SDL bado upo hadi utakapopata uthibitisho wa maandishi kutoka TRA.",
        "answer_en": "Companies formally registered in a Tanzania Export Processing Zone (EPZ) may be eligible for SDL exemption as part of the investment incentive package. However, this exemption is not automatic — the company must confirm its EPZ status with EPZA and obtain a specific exemption approval from TRA. Check your EPZ registration certificate for conditions. If you have not received formal exemption, the SDL obligation remains until you receive written confirmation from TRA.",
        "question_en": "Can employers in an Export Processing Zone (EPZ) be exempted from SDL?",
        "primary_source_url": "https://www.tra.go.tz/page/skills-development-levy-sdl",
        "primary_source_name": "TRA SDL — EPZ incentives",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "event_triggered",
        "next_review_trigger": "EPZ Act amendment or TRA SDL circular",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_sdl_ext_002_20260603",
        "domain": "tier1a",
        "subdomain": "skills_levy_extended",
        "question_sw": "Mwajiri anaweza kuomba msamaha wa SDL vipi?",
        "answer_sw": "Mwajiri anayetaka msamaha wa SDL lazima aandike ombi rasmi kwa Kamishna wa TRA akitoa sababu za kisheria za msamaha, kama vile hadhi ya EPZ, hali ya shirika lisilo la faida, au msamaha mwingine uliowekwa kisheria. Ombi linapaswa kuambatanishwa na: cheti cha usajili wa shirika, hati inayothibitisha hadhi ya msamaha (k.m. cheti cha EPZA au hati ya shirika lisilo la faida), na nyaraka za BRELA. TRA itapitia ombi na kutoa uamuzi kwa maandishi. Usidai msamaha kabla ya kupata uamuzi wa TRA.",
        "answer_en": "An employer seeking SDL exemption must write a formal application to the TRA Commissioner General stating the legal grounds for exemption, such as EPZ status, non-profit organisation status, or another statutory exemption. The application should be accompanied by: the organisation's registration certificate, documentation confirming exemption status (e.g., EPZA certificate or non-profit deed), and BRELA documents. TRA will review the application and issue a written decision. Do not claim exemption before receiving TRA's written decision.",
        "question_en": "How can an employer apply for an SDL exemption?",
        "primary_source_url": "https://www.tra.go.tz/page/skills-development-levy-sdl",
        "primary_source_name": "TRA SDL — exemption application procedure",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "TRA SDL administrative circular",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_sdl_ext_003_20260603",
        "domain": "tier1a",
        "subdomain": "skills_levy_extended",
        "question_sw": "SDL inahesabiwaje — inatumika kwenye mshahara wa msingi peke yake au posho pia?",
        "answer_sw": "SDL inahesabiwaje kwa Tanzania inategemea tafsiri ya 'gross emoluments' ya mwajiri. Kwa ujumla, SDL ya 3.5% inahesabiwaje kwenye jumla ya fidia ya ajira inayolipwa kwa wafanyakazi, ikiwa ni pamoja na mshahara wa msingi, posho za nyumba, usafiri, chakula, na malipo mengine yanayohusiana na ajira. Hata hivyo, malipo ya gharama za biashara halisi yanayopigiwa risiti kawaida hayajumuishwi. Kwa tafsiri sahihi ya mwaka huu, wasiliana na TRA au mshauri wa kodi.",
        "answer_en": "SDL calculation in Tanzania depends on the interpretation of 'gross emoluments' by the employer. Generally, SDL at 3.5% is calculated on the total employment compensation paid to employees, including basic salary, housing allowances, transport, meals, and other employment-related payments. However, genuine business expense reimbursements supported by receipts are typically excluded. For precise interpretation for this year, contact TRA or a tax consultant.",
        "question_en": "How is SDL calculated — does it apply to basic salary only or allowances too?",
        "primary_source_url": "https://www.tra.go.tz/page/skills-development-levy-sdl",
        "primary_source_name": "TRA SDL — calculation base",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment or TRA SDL circular",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_sdl_ext_004_20260603",
        "domain": "tier1a",
        "subdomain": "skills_levy_extended",
        "question_sw": "Kampuni yangu inafunza wanafunzi (apprentices) chini ya mpango wa serikali. Je, hii inaathiri wajibu wa SDL?",
        "answer_sw": "Hali ya wanafunzi wa mafunzo na SDL inategemea muundo wa mpango: ikiwa mwanafunzi analipwa posho ya mafunzo (training allowance) tu — si mshahara kamili wa ajira — posho hiyo inaweza kutolewa kwenye msingi wa SDL. Ikiwa mwanafunzi anachukuliwa kama mfanyakazi kamili na analipwa mshahara, SDL inatumika. Mipango ya mafunzo iliyoidhinishwa na serikali inaweza kuwa na masharti tofauti — thibitisha na VETA (Vocational Education and Training Authority) na TRA kabla ya kuamua jinsi ya kuhesabu.",
        "answer_en": "The SDL treatment of apprentices depends on the programme structure: if the apprentice receives only a training allowance — not a full employment salary — that allowance may be excluded from the SDL base. If the apprentice is treated as a full employee and paid a salary, SDL applies. Government-approved training programmes may have different conditions — confirm with VETA (Vocational Education and Training Authority) and TRA before deciding how to calculate.",
        "question_en": "My company trains apprentices under a government scheme. Does this affect the SDL obligation?",
        "primary_source_url": "https://www.tra.go.tz/page/skills-development-levy-sdl",
        "primary_source_name": "TRA SDL — apprenticeship treatment",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "event_triggered",
        "next_review_trigger": "VETA Act amendment or TRA circular on apprenticeship SDL",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_sdl_ext_005_20260603",
        "domain": "tier1a",
        "subdomain": "skills_levy_extended",
        "question_sw": "Shirika lisilo la faida (NGO au asasi ya kiraia) linalipa SDL?",
        "answer_sw": "NGO na asasi za kiraia zilizosajiliwa rasmi zinaweza kupata msamaha wa SDL — lakini si kwa kiotomatiki. Mashirika lazima yathibitishe hadhi yao ya msamaha kwa TRA kila mwaka. Ikiwa NGO inaajiri wafanyakazi na inalipa mishahara, na bado haina msamaha rasmi wa maandishi kutoka TRA, wajibu wa SDL unabaki. Mashirika yanayopokea msamaha lazima yathibitishe mwaka kwa mwaka kwamba bado yanastahili.",
        "answer_en": "NGOs and civil society organisations that are formally registered may qualify for SDL exemption — but not automatically. Organisations must confirm their exemption status with TRA annually. If an NGO employs staff and pays salaries, and does not yet have a formal written exemption from TRA, the SDL obligation remains. Organisations receiving exemption must confirm annually that they still qualify.",
        "question_en": "Does a non-profit organisation (NGO or civil society) pay SDL?",
        "primary_source_url": "https://www.tra.go.tz/page/skills-development-levy-sdl",
        "primary_source_name": "TRA SDL — NGO exemption",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment or TRA circular",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_sdl_ext_006_20260603",
        "domain": "tier1a",
        "subdomain": "skills_levy_extended",
        "question_sw": "Kampuni inayomilikiwa na Serikali (parastatal) inalipa SDL?",
        "answer_sw": "Kwa ujumla ndiyo — taasisi zinazomilikiwa na Serikali (parastatals) kama TANESCO, TPA, na NMB zinazolipa mishahara ya wafanyakazi zinatakiwa kulipa SDL kama mwajiri mwingine yeyote, isipokuwa zitakazokuwa zimepata msamaha maalum kutoka TRA. Waajiri wote wenye wafanyakazi 10 au zaidi wanalipa SDL ya 3.5% ya mishahara ya jumla. Hali ya kila parastatal inaweza kutofautiana — thibitisha na TRA kwa shirika lako maalum.",
        "answer_en": "Generally yes — government-owned institutions (parastatals) such as TANESCO, TPA, and NMB that pay employee salaries are required to pay SDL like any other employer, unless they have received a specific exemption from TRA. All employers with 10 or more employees pay SDL at 3.5% of gross payroll. Each parastatal's situation may vary — confirm with TRA for your specific organisation.",
        "question_en": "Does a government-owned company (parastatal) pay SDL?",
        "primary_source_url": "https://www.tra.go.tz/page/skills-development-levy-sdl",
        "primary_source_name": "TRA SDL — parastatal obligation",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment or TRA circular",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_sdl_ext_007_20260603",
        "domain": "tier1a",
        "subdomain": "skills_levy_extended",
        "question_sw": "TRA inafanya ukaguzi wa SDL vipi na wanakagua nini?",
        "answer_sw": "TRA wanaweza kufanya ukaguzi wa SDL kwa mpango au baada ya kupokea taarifa za udanganyifu. Wakati wa ukaguzi, TRA wanakagua: orodha za mishahara (payroll) kwa miaka inayopitiwa, rekodi za benki za malipo ya mishahara, return za SDL zilizowasilishwa, mikataba ya ajira, na rekodi za kuidhinisha wafanyakazi. Tofauti kati ya mishahara iliyotangazwa kwenye return za PAYE na ile ya SDL ni dalili ya tatizo. Kuhifadhi rekodi za mishahara kwa miaka 5 angalau ni lazima.",
        "answer_en": "TRA may conduct SDL audits on a planned basis or after receiving fraud reports. During an audit, TRA examines: payroll records for the years under review, bank statements showing salary payments, submitted SDL returns, employment contracts, and staff confirmation records. A discrepancy between salaries declared on PAYE returns and SDL returns is a red flag. Maintaining payroll records for at least 5 years is mandatory.",
        "question_en": "How does TRA conduct an SDL audit and what do they examine?",
        "primary_source_url": "https://www.tra.go.tz/page/skills-development-levy-sdl",
        "primary_source_name": "TRA SDL — audit procedure",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "TRA audit methodology change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_sdl_ext_008_20260603",
        "domain": "tier1a",
        "subdomain": "skills_levy_extended",
        "question_sw": "Pesa za SDL zinakwenda wapi na zinatumika kwa nini?",
        "answer_sw": "Mapato ya SDL yanakusanywa na TRA na kupelekwa Hazina ya Serikali. Fedha hizo zinatumiwa kufadhili mfumo wa elimu ya ufundi na mafunzo ya ujuzi Tanzania kupitia VETA (Vocational Education and Training Authority) na vyuo vya ufundi (FDCs). Lengo ni kuimarisha ujuzi wa nguvu kazi ya Tanzania. Mwajiri hana haki ya kudai marejesho ya SDL kwa sababu mafunzo fulani yanafanywa ndani ya kampuni — hii ni wajibu wa kisheria wa kawaida.",
        "answer_en": "SDL revenue is collected by TRA and transferred to the Government Treasury. The funds are used to finance Tanzania's vocational education and skills training system through VETA (Vocational Education and Training Authority) and technical colleges (FDCs). The goal is to strengthen the skills of Tanzania's workforce. An employer has no right to claim SDL refunds on the grounds that some training is conducted internally — this is a standard statutory obligation.",
        "question_en": "Where does SDL money go and what is it used for?",
        "primary_source_url": "https://www.tra.go.tz/page/skills-development-levy-sdl",
        "primary_source_name": "TRA SDL — VETA funding purpose",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "VETA Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },

    # ── NSSF DISPUTES (8 pairs) ──────────────────────────────────────────────
    {
        "id": "tier1a_nssf_disp_001_20260603",
        "domain": "tier1a",
        "subdomain": "nssf_disputes",
        "question_sw": "NSSF imetoa tathmini ya michango ya ziada dhidi ya kampuni yangu ambayo naona ni makosa. Naweza kupinga vipi?",
        "answer_sw": "Unaweza kupinga tathmini ya NSSF kwa njia zifuatazo: kwanza, wasiliana na ofisi ya NSSF kwa maandishi ndani ya siku 30 baada ya kupokea tathmini, ukitoa ushahidi wa payroll yako halisi (rekodi za mshahara, slips za malipo, na rekodi za benki). Ikiwa tathmini bado hairidhishi, unaweza kupiga rufaa kwa Mkurugenzi Mtendaji wa NSSF. Kama bado hujaridhika, uzo unaendelea hadi Mahakama ya Kazi (Labour Court). Hifadhi rekodi zote za malipo ya NSSF na mishahara kwa miaka 5 ili kujibu tathmini.",
        "answer_en": "You can dispute an NSSF assessment in these steps: first, contact the NSSF office in writing within 30 days of receiving the assessment, providing evidence of your actual payroll (salary records, payslips, and bank records). If the assessment is still unsatisfactory, you can appeal to the NSSF Director General. If still unsatisfied, the dispute proceeds to the Labour Court. Keep all NSSF payment and salary records for 5 years to respond to assessments.",
        "question_en": "NSSF has issued an excess contribution assessment against my company that I believe is wrong. How can I dispute it?",
        "primary_source_url": "https://www.nssf.go.tz/pages/payment-of-contributions",
        "primary_source_name": "NSSF — contribution dispute procedure",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "NSSF Act amendment or Labour Court rules change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_nssf_disp_002_20260603",
        "domain": "tier1a",
        "subdomain": "nssf_disputes",
        "question_sw": "NSSF inaweza kukagua rekodi za mishahara za kampuni yangu?",
        "answer_sw": "Ndiyo. NSSF ina mamlaka ya kisheria ya kukagua rekodi za mishahara (payroll inspection) za mwajiri yeyote aliyesajiliwa. Wakaguzi wa NSSF wanaweza kutembelea mahali pa biashara na kuomba: orodha za mishahara, slips za malipo, rekodi za benki za malipo ya mshahara, mikataba ya ajira, na rekodi za michango ya NSSF iliyolipwa. Mwajiri ana wajibu wa kisheria wa kutoa nyaraka hizi kwa wakaguzi wa NSSF. Kukosa kushirikiana na ukaguzi ni kosa la kisheria.",
        "answer_en": "Yes. NSSF has the legal authority to inspect the payroll records of any registered employer. NSSF inspectors may visit the business premises and request: payroll lists, payslips, bank records of salary payments, employment contracts, and records of NSSF contributions paid. An employer has a legal obligation to provide these documents to NSSF inspectors. Failure to cooperate with an inspection is a legal offence.",
        "question_en": "Can NSSF inspect my company's payroll records?",
        "primary_source_url": "https://www.nssf.go.tz/pages/payment-of-contributions",
        "primary_source_name": "NSSF — employer inspection powers",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "NSSF Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_nssf_disp_003_20260603",
        "domain": "tier1a",
        "subdomain": "nssf_disputes",
        "question_sw": "NSSF inachukua hatua gani dhidi ya mwajiri asiyolipa michango ya wafanyakazi?",
        "answer_sw": "NSSF ina hatua kadhaa za utekelezaji dhidi ya waajiri wasiotii: kwanza, onyo rasmi na hati ya kudai malipo. Kama malipo hayafanyiki, NSSF inaweza: kutumia kisheria ili kunyang'anya mali za mwajiri, kutoa amri ya kushikilia akaunti za benki, kupeleka kesi mahakamani ya kazi au jinai, na kutoa faini ya 5% kwa kila mwezi wa ucheleweshaji wa michango isiyolipwa. Waajiri wanaohukumiwa wanaweza pia kupoteza haki ya kupata mikataba ya serikali.",
        "answer_en": "NSSF has several enforcement steps against non-compliant employers: first, a formal warning and demand notice for payment. If payment is not made, NSSF may: use legal process to seize employer assets, issue orders to freeze bank accounts, take the matter to a labour or criminal court, and impose a 5% penalty for each month of delay on unpaid contributions. Convicted employers may also lose the right to obtain government contracts.",
        "question_en": "What action does NSSF take against an employer who does not pay employee contributions?",
        "primary_source_url": "https://www.nssf.go.tz/pages/payment-of-contributions",
        "primary_source_name": "NSSF — enforcement against non-compliant employers",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "NSSF Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_nssf_disp_004_20260603",
        "domain": "tier1a",
        "subdomain": "nssf_disputes",
        "question_sw": "Mfanyakazi anawezaje kuangalia historia ya michango yake ya NSSF?",
        "answer_sw": "Mfanyakazi anaweza kuangalia historia ya michango yake ya NSSF kwa njia zifuatazo: kupitia portal ya NSSF mtandaoni kwenye nssf.go.tz kwa kutumia nambari yake ya uanachama, kutembelea ofisi yoyote ya NSSF na kadi ya utambulisho, au kupiga simu ya huduma kwa wateja wa NSSF. Kauli ya michango (contribution statement) inaweza kuombwa na inakuonyesha kila mchango uliofanywa na mwajiri wako. Ikiwa michango haikuingia kwenye akaunti yako ijapokuwa mwajiri anasema amelipa, piga kengele mara moja.",
        "answer_en": "An employee can check their NSSF contribution history through: the NSSF online portal at nssf.go.tz using their membership number, visiting any NSSF office with identification, or calling the NSSF customer service line. A contribution statement can be requested and shows every contribution made by your employer. If contributions are not appearing in your account despite the employer claiming to have paid, raise the issue immediately.",
        "question_en": "How can an employee check their NSSF contribution history?",
        "primary_source_url": "https://www.nssf.go.tz/pages/payment-of-contributions",
        "primary_source_name": "NSSF — member contribution statement",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "NSSF portal system change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_nssf_disp_005_20260603",
        "domain": "tier1a",
        "subdomain": "nssf_disputes",
        "question_sw": "Mfanyakazi anayestaafu anapokea mafao ya NSSF vipi?",
        "answer_sw": "Mfanyakazi anayestaafu baada ya kufikia umri wa miaka 60 (au 55 kwa wafanyakazi wa uchimbaji madini) anapaswa: kuwasilisha fomu ya madai ya mafao (benefit claim form) katika ofisi yoyote ya NSSF, kuambatanisha hati za utambulisho, barua ya kuthibitisha kustaafu kutoka kwa mwajiri, na cheti cha kuzaliwa. NSSF itatathmini miaka ya uchangiaji (minimum 180 months/miaka 15 kwa mafao kamili). Malipo yanafanywa kupitia akaunti ya benki. Kwa staafu wa kabla ya wakati, thibitisha masharti na NSSF.",
        "answer_en": "An employee retiring at age 60 (or 55 for mining sector employees) must: submit a benefit claim form at any NSSF office, attach identification documents, a retirement confirmation letter from the employer, and a birth certificate. NSSF will assess the contribution years (minimum 180 months/15 years for full benefits). Payment is made via bank account. For early retirement, confirm conditions with NSSF.",
        "question_en": "How does a retiring employee receive their NSSF pension benefits?",
        "primary_source_url": "https://www.nssf.go.tz/pages/payment-of-contributions",
        "primary_source_name": "NSSF — retirement benefit claim process",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "annual",
        "next_review_trigger": "NSSF Act amendment to retirement age or benefit calculation",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_nssf_disp_006_20260603",
        "domain": "tier1a",
        "subdomain": "nssf_disputes",
        "question_sw": "Je, mfanyakazi anaweza kuondoa mchangoa wake wa NSSF kabla ya kustaafu?",
        "answer_sw": "Kwa ujumla hapana — michango ya NSSF haiwezi kuondolewa kabla ya kustaafu. Hata hivyo, kuna hali chache za kisheria ambazo zinaweza kuruhusu madai kabla ya wakati: kuwa na ulemavu mkubwa wa kudumu (permanent total disability), kifo cha mwanachama (ambapo mzigo unalipwa kwa wategemezi), au kuacha Tanzania kwa muda wa kudumu. Madai ya kawaida ya uchovu, msongo wa maisha, au tatizo la fedha hayatoi haki ya kuondoa kabla ya wakati. NSSF ni mfumo wa akiba ya muda mrefu — si akaunti ya benki inayoweza kufunguliwa wakati wowote.",
        "answer_en": "Generally no — NSSF contributions cannot be withdrawn before retirement. However, there are a few statutory circumstances that may allow early claims: permanent total disability, death of the member (in which case a survivor benefit is paid), or permanently leaving Tanzania. Ordinary claims of financial hardship, life pressures, or personal financial problems do not give a right to early withdrawal. NSSF is a long-term savings system — not a bank account that can be accessed at any time.",
        "question_en": "Can an employee withdraw their NSSF contributions before retirement?",
        "primary_source_url": "https://www.nssf.go.tz/pages/payment-of-contributions",
        "primary_source_name": "NSSF — early withdrawal conditions",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "NSSF Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_nssf_disp_007_20260603",
        "domain": "tier1a",
        "subdomain": "nssf_disputes",
        "question_sw": "Mfanyakazi anafariki kabla ya kustaafu. Familia yake inapata mafao gani ya NSSF?",
        "answer_sw": "Familia ya mfanyakazi aliyefariki inastahili mafao ya maisha (survivor benefits) kutoka NSSF. Wategemezi wa kisheria (mke/mume, watoto chini ya miaka 18, na wazazi wanaotegemea) wanaweza kudai: mafao ya kifo (death grant) — malipo ya mara moja — na mafao ya urithi (survivors pension) kwa wategemezi. Kuomba mafao haya, familia inapaswa: kwenda ofisi ya NSSF na cheti cha kifo, hati za utambulisho wa wategemezi, cheti cha ndoa, na cheti cha kuzaliwa kwa watoto. Madai lazima yafanyike ndani ya muda maalum.",
        "answer_en": "The family of a deceased employee is entitled to survivor benefits from NSSF. Legal dependants (spouse, children under 18, and dependent parents) may claim: a death grant (lump sum payment) and a survivor's pension for dependants. To claim these benefits, the family must: go to an NSSF office with a death certificate, identification documents of dependants, a marriage certificate, and birth certificates of children. Claims must be made within a specific time period.",
        "question_en": "An employee dies before retirement. What NSSF benefits does their family receive?",
        "primary_source_url": "https://www.nssf.go.tz/pages/payment-of-contributions",
        "primary_source_name": "NSSF — survivor benefit claim",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "NSSF Act amendment to survivor benefits",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_nssf_disp_008_20260603",
        "domain": "tier1a",
        "subdomain": "nssf_disputes",
        "question_sw": "Mfanyakazi anabadilisha kazi kutoka kampuni A hadi kampuni B. Michango yake ya NSSF inahamia vipi?",
        "answer_sw": "Michango ya NSSF haihitajiki 'kuhamia' — inabaki kwenye akaunti ya NSSF ya mwanachama na inaendelea kujengwa bila kujali mabadiliko ya mwajiri. Nambari ya NSSF ya mwanachama inabaki ile ile, na mwajiri mpya anaendelea kuchangia kwenye nambari hiyo ile. Mfanyakazi anapaswa kumwarifu mwajiri mpya nambari yake ya NSSF mara anapokuwa ameajiriwa. Kama mwajiri mpya hajui nambari yako ya NSSF, unaweza kuomba nambari kutoka ofisi yoyote ya NSSF au kwa kutumia portal ya mtandaoni.",
        "answer_en": "NSSF contributions do not need to 'transfer' — they remain in the member's NSSF account and continue to accumulate regardless of employer changes. The member's NSSF number stays the same, and the new employer continues contributing to that same number. The employee should inform the new employer of their NSSF number when they start work. If the new employer does not know your NSSF number, you can request it from any NSSF office or through the online portal.",
        "question_en": "An employee changes jobs from Company A to Company B. How do their NSSF contributions transfer?",
        "primary_source_url": "https://www.nssf.go.tz/pages/payment-of-contributions",
        "primary_source_name": "NSSF — portability and job change",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "NSSF Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },

    # ── BRELA CHANGES (10 pairs) ─────────────────────────────────────────────
    {
        "id": "tier1a_brela_chg_001_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Kampuni inabadilisha mkurugenzi wake (director). Mchakato wa BRELA ni upi?",
        "answer_sw": "Kubadilisha mkurugenzi wa kampuni kunahitaji: uamuzi wa bodi (board resolution) ukimteua mkurugenzi mpya na kumalizia mamlaka ya mkurugenzi wa zamani, kuwasilisha Fomu 23 (Taarifa ya Mabadiliko ya Wakurugenzi) kwa BRELA ndani ya siku 14 baada ya mabadiliko, kulipa ada inayohusiana, na kuwasilisha hati za utambulisho za mkurugenzi mpya. BRELA itasasisha rekodi na kutoa uthibitisho. Kuchelewa kuwasilisha mabadiliko kunasababisha adhabu.",
        "answer_en": "Changing a company director requires: a board resolution appointing the new director and ending the authority of the outgoing director, filing Form 23 (Notice of Change of Directors) with BRELA within 14 days of the change, paying the associated fee, and submitting identification documents of the new director. BRELA will update the records and issue confirmation. Late filing of changes attracts penalties.",
        "question_en": "A company is changing its director. What is the BRELA process?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — director change procedure",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Companies Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_002_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Kampuni inataka kubadilisha jina lake. Inafuata mchakato gani wa BRELA?",
        "answer_sw": "Kubadilisha jina la kampuni kunahitaji: kupitisha azimio maalum (special resolution) la wanahisa wenye asilimia 75 ya kura kuunga mkono mabadiliko ya jina, kuomba kuidhinishwa kwa jina jipya na BRELA kwa ajili ya uthibitisho wa upatikanaji, kuwasilisha maombi rasmi ya mabadiliko ya jina kwa BRELA na ada, na kupata cheti kipya cha usajili kikiwa na jina jipya. Baada ya mabadiliko ya jina, lazima usasishe nyaraka zote za kisheria, akaunti za benki, na leseni nyingine zote.",
        "answer_en": "Changing a company name requires: passing a special resolution by shareholders holding at least 75% of votes supporting the name change, applying to BRELA to approve the new name for availability confirmation, submitting a formal name change application to BRELA with fees, and receiving a new registration certificate with the new name. After the name change, you must update all legal documents, bank accounts, and all other licences.",
        "question_en": "A company wants to change its name. What BRELA process does it follow?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — company name change procedure",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Companies Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_003_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Kampuni inataka kuongeza mtaji wake wa hisa (share capital). Inafanyaje?",
        "answer_sw": "Kuongeza mtaji wa hisa kunahitaji: kupitisha azimio la kawaida (ordinary resolution) la wanahisa, kuwasilisha fomu ya taarifa ya mabadiliko ya mtaji kwa BRELA ndani ya muda uliowekwa, kulipa ada ya usajili inayohusiana na ongezeko la mtaji, na kusasisha Hati ya Muundo wa Kampuni (Memorandum and Articles of Association) ikiwa inahitajika. BRELA itasasisha rekodi za kampuni. Ongezeko la mtaji linaweza pia kuathiri uwiano wa umiliki wa wanahisa (dilution) — thibitisha na mshauri wa kisheria.",
        "answer_en": "Increasing share capital requires: passing an ordinary resolution of shareholders, filing a capital change notification form with BRELA within the prescribed period, paying the associated registration fee based on the capital increase, and updating the Memorandum and Articles of Association if required. BRELA will update the company records. A share capital increase may also affect shareholder ownership proportions (dilution) — confirm with a legal adviser.",
        "question_en": "A company wants to increase its share capital. How does it do this?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — share capital increase procedure",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Companies Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_004_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Mwanahisa mmoja anamuuzia mwingine hisa zake. Je, BRELA inahitaji taarifa ya uhamishaji huu?",
        "answer_sw": "Ndiyo. Uhamishaji wa hisa kati ya wanahisa lazima uripotiwe BRELA. Mchakato ni: kuandaa hati ya uhamishaji wa hisa (instrument of transfer), kupiga stempu hati hiyo (kodi ya stempu ya 1% — ona Stamp Duty Act), kuwasilisha taarifa ya mabadiliko ya wanahisa kwa BRELA, na kusasisha daftari la wanahisa (register of members) la kampuni. BRELA itasasisha rekodi na kutoa uthibitisho wa mabadiliko ya umiliki. Bila taarifa ya BRELA, uhamishaji hauna nguvu ya kisheria.",
        "answer_en": "Yes. Transfer of shares between shareholders must be reported to BRELA. The process is: prepare an instrument of transfer, stamp the instrument (1% stamp duty — see Stamp Duty Act), file a shareholder change notification with BRELA, and update the company's register of members. BRELA will update records and issue confirmation of the ownership change. Without BRELA notification, the transfer has no legal force.",
        "question_en": "One shareholder sells their shares to another. Does BRELA need to be notified of this transfer?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — share transfer procedure",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Companies Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_005_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Kampuni inataka kufuta usajili wake (deregistration) rasmi. Mchakato wa BRELA ni upi?",
        "answer_sw": "Kufuta usajili wa kampuni kwa hiari (voluntary dissolution) kunahitaji: kupitisha azimio maalum la wanahisa (75%+), kuteuwa msimamizi wa likwidesheni (liquidator), kulipa madeni yote ya kampuni na kukusanya madai, kuwasilisha taarifa za mwisho za uhasibu, na kuomba kufutwa kwa jina kutoka BRELA. Mahakama inaweza pia kuagiza kufutwa kwa lazima. Utaratibu huu unaweza kuchukua miezi kadhaa. Kabla ya kufuta, hakikisha TRA, NSSF, na mashirika mengine yote yamesafirishwa na madeni yalipwa.",
        "answer_en": "Voluntary company deregistration requires: passing a special resolution by shareholders (75%+), appointing a liquidator, paying all company debts and collecting receivables, submitting final accounting statements, and applying for name removal from BRELA. A court may also order compulsory winding up. This process may take several months. Before deregistration, ensure TRA, NSSF, and all other agencies are settled and all debts are paid.",
        "question_en": "A company wants to formally deregister (dissolution). What is the BRELA process?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — company dissolution procedure",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Companies Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_006_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Kampuni isiyofanya biashara (dormant company) bado ina wajibu wowote wa BRELA?",
        "answer_sw": "Ndiyo. Kampuni iliyolala (dormant company) bado ina wajibu wa kisheria wa: kuwasilisha ripoti ya kila mwaka (annual return) kwa BRELA kila mwaka, kulipa ada ya ripoti ya kila mwaka, na kudumisha mkurugenzi aliyesajiliwa na anwani ya makao makuu. Kutowasilisha ripoti ya kila mwaka hata kampuni ikiwa haifanyi biashara kunasababisha faini na hatimaye kufutwa kwa jina na BRELA. Ikiwa hutaki kulipa ada hizi kila mwaka, fikiria kufuta usajili wa kampuni rasmi.",
        "answer_en": "Yes. A dormant (inactive) company still has legal obligations to: file an annual return with BRELA every year, pay the annual return fee, and maintain a registered director and registered office address. Failing to file the annual return even when the company is inactive attracts fines and eventually striking off by BRELA. If you do not want to pay these fees annually, consider formally deregistering the company.",
        "question_en": "A company that is not trading (dormant company) — does it still have any BRELA obligations?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — dormant company annual return",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Companies Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_007_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Kampuni ya nje (foreign company) inaweza kusajili tawi lake (branch) Tanzania vipi?",
        "answer_sw": "Kampuni ya kigeni inayotaka kusajili tawi Tanzania lazima iwasilishe kwa BRELA: hati za shirika la kampuni mama (Memorandum and Articles ya nchi ya asili), uthibitisho wa uhalali wa kampuni mama nchini yake, majina na anwani za wakurugenzi wa kampuni mama, jina la mwakilishi wa tawi Tanzania, na ada ya usajili. Tawi lazima pia lipate TIN, leseni ya LGA, na vibali vingine vinavyohusiana na biashara inayofanywa. GN 487A (Julai 2025) inazuia raia wasio Watanzania kufanya biashara fulani maalum.",
        "answer_en": "A foreign company wishing to register a branch in Tanzania must submit to BRELA: the parent company incorporation documents (Memorandum and Articles from the country of origin), proof of the parent company's legal existence in its home country, names and addresses of the parent company's directors, the name of the branch representative in Tanzania, and a registration fee. The branch must also obtain a TIN, an LGA licence, and other permits relevant to the business. GN 487A (July 2025) prohibits non-Tanzanian citizens from conducting certain specified businesses.",
        "question_en": "How can a foreign company register its branch in Tanzania?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — foreign company branch registration",
        "source_type": "government_portal",
        "effective_date": "2025-07-28",
        "decay_risk": "event_triggered",
        "next_review_trigger": "Companies Act amendment or GN 487A revision",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_008_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Ninataka kubadilisha biashara yangu ya mmiliki mmoja (sole trader) na kuifanya kampuni ya kikomo cha dhima (limited company). Ninafanyaje?",
        "answer_sw": "Kubadilisha biashara ya mmiliki mmoja kuwa kampuni ya kikomo cha dhima si 'kubadilisha' rasmi — ni kuanzisha kampuni mpya na BRELA. Mchakato ni: jaza fomu za usajili wa kampuni mpya ya kikomo cha dhima, lipa ada ya usajili, pata nambari ya TIN mpya kwa kampuni, hamisha mali na mikataba ya biashara ya zamani kwenye kampuni mpya (kwa kuzingatia mambo ya kodi na kisheria), na unaweza kuacha biashara ya mmiliki mmoja ikifunga. Pata ushauri wa mshauri wa kisheria au mhasibu kabla ya kubadilisha ili kuelewa athari za kodi.",
        "answer_en": "Converting a sole trader business to a limited company is not a formal 'conversion' — it is registering a new company with BRELA. The process is: complete new limited company registration forms with BRELA, pay the registration fee, obtain a new TIN for the company, transfer the assets and contracts of the old business to the new company (considering tax and legal implications), and you may close the sole trader business. Seek advice from a legal adviser or accountant before switching to understand the tax implications.",
        "question_en": "I want to convert my sole trader business into a limited company. How do I do this?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — sole trader to limited company conversion",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "stable",
        "next_review_trigger": "Companies Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_009_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "Ada za usajili wa BRELA kwa kampuni mpya ni kiasi gani?",
        "answer_sw": "Ada za usajili wa BRELA zinatofautiana kulingana na aina ya kampuni na mtaji ulioandikishwa. Kwa kampuni za ndani (private/public limited companies), ada inategemea mtaji wa hisa ulioandikishwa — kampuni za mtaji mdogo (chini ya TZS 1,000,000) zinalipa ada tofauti na kampuni za mtaji mkubwa. Pia kuna ada ya usajili wa jina la biashara (business name), ushirika (partnership), na kampuni za kigeni (foreign companies). Nenda moja kwa moja kwenye tovuti ya BRELA (brela.go.tz) au ofisi ya BRELA kwa jedwali la sasa la ada kwani zinaweza kubadilika mwaka hadi mwaka.",
        "answer_en": "BRELA registration fees vary based on the type of company and registered share capital. For domestic companies (private/public limited companies), the fee depends on the registered share capital — companies with small capital (below TZS 1,000,000) pay different fees from large-capital companies. There are also fees for business name registration, partnerships, and foreign companies. Go directly to the BRELA website (brela.go.tz) or BRELA office for the current fee schedule as fees may change year to year.",
        "question_en": "What are the BRELA registration fees for a new company?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — registration fee schedule",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "annual",
        "next_review_trigger": "BRELA fee schedule update",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_brela_chg_010_20260603",
        "domain": "tier1a",
        "subdomain": "brela_changes",
        "question_sw": "BRELA ina portal ya mtandaoni kwa ajili ya usajili? Ninawezaje kuitumia?",
        "answer_sw": "Ndiyo. BRELA ina mfumo wa usajili wa mtandaoni unaoruhusu usajili na uwasilishaji wa hati bila kuhitaji kwenda ofisi. Unaweza kufikia portal kupitia tovuti ya brela.go.tz. Hatua za kimsingi ni: tengeneza akaunti ya mtumiaji, chagua aina ya usajili unaotaka (kampuni, jina la biashara, ushirika), jaza fomu za mtandaoni, pakia hati zinazohitajika, lipa ada kupitia GePG au mfumo wa malipo ulioungwa mkono. Usajili wa mtandaoni unaokoa muda na safari. Kwa msaada wa kina, BRELA ina ofisi kuu Dar es Salaam na ofisi za kanda.",
        "answer_en": "Yes. BRELA has an online registration system that allows registration and document submission without needing to visit the office. You can access the portal through the BRELA website at brela.go.tz. The basic steps are: create a user account, select the type of registration you want (company, business name, partnership), complete the online forms, upload required documents, pay the fee via GePG or the supported payment system. Online registration saves time and travel. For detailed assistance, BRELA has its main office in Dar es Salaam and regional offices.",
        "question_en": "Does BRELA have an online portal for registration? How can I use it?",
        "primary_source_url": "https://www.brela.go.tz",
        "primary_source_name": "BRELA — online portal",
        "source_type": "government_portal",
        "effective_date": "2025-01-01",
        "decay_risk": "annual",
        "next_review_trigger": "BRELA portal system upgrade",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },

    # ── TAX DISPUTES (7 pairs) ───────────────────────────────────────────────
    {
        "id": "tier1a_tax_disp_001_20260603",
        "domain": "tier1a",
        "subdomain": "tax_disputes",
        "question_sw": "TRA imetoa tathmini ya kodi ambayo ninaona ni makosa. Ninaweza kupinga vipi na ndani ya muda gani?",
        "answer_sw": "Unaweza kupinga tathmini ya TRA kwa kuwasilisha hoja ya pingamizi rasmi (notice of objection) kwa Kamishna wa TRA ndani ya siku 30 baada ya kupokea tathmini. Hoja lazima iwe kwa maandishi na ieleze kwa undani sababu za kisheria za kupingana na tathmini, ikiambatana na ushahidi wa kutosha (rekodi za uhasibu, risiti, mikataba). Kamishna atapitia hoja na kutoa uamuzi ndani ya siku 90. Muhimu: Siku 30 za kuwasilisha hoja ni muda wa kisheria usiopanuliwa kwa urahisi — usipoteze muda.",
        "answer_en": "You can dispute a TRA assessment by submitting a formal notice of objection to the TRA Commissioner General within 30 days of receiving the assessment. The objection must be in writing and explain in detail the legal grounds for disputing the assessment, accompanied by sufficient evidence (accounting records, receipts, contracts). The Commissioner will review the objection and issue a decision within 90 days. Important: the 30-day period for filing an objection is a statutory deadline not easily extended — do not waste time.",
        "question_en": "TRA has issued a tax assessment that I believe is wrong. How can I dispute it and within what time?",
        "primary_source_url": "https://www.tra.go.tz",
        "primary_source_name": "TRA — tax objection procedure (ITA/VATCA)",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "Tax Revenue Appeals Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_tax_disp_002_20260603",
        "domain": "tier1a",
        "subdomain": "tax_disputes",
        "question_sw": "Muda wa kuwasilisha hoja ya pingamizi ya kodi TRA ni siku 30. Je, muda huu unaweza kuongezwa?",
        "answer_sw": "Kwa ujumla muda wa siku 30 ni mgumu kuongezwa. Sheria ya Mapato ya Kodi (Tax Revenue Appeals Act) inaweka muda huu kama masharti ya awali — kushindwa kuwasilisha ndani ya siku 30 kunaweza kusababisha hoja yako kutokubalika. Hata hivyo, kwa hali za kipekee za nguvu ya lazima (force majeure) au ushahidi wa thabiti kwamba haikuwezekana kuwasilisha kwa wakati, Kamishna anaweza kwa hiari kuruhusu upanuzi. Hii ni nadra sana. Kila wakati, boresha hoja na uwasilishe ndani ya siku 30 — usitegemee kupata upanuzi.",
        "answer_en": "Generally the 30-day period is very difficult to extend. The Tax Revenue Appeals Act treats this period as a condition precedent — failing to file within 30 days may result in your objection being rejected as inadmissible. However, in exceptional cases of genuine force majeure or strong evidence that filing was genuinely impossible, the Commissioner may at discretion allow an extension. This is very rare. Always prepare your objection and file within 30 days — do not rely on getting an extension.",
        "question_en": "The deadline for filing a TRA tax objection is 30 days. Can this period be extended?",
        "primary_source_url": "https://www.tra.go.tz",
        "primary_source_name": "TRA — tax objection 30-day deadline",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "Tax Revenue Appeals Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_tax_disp_003_20260603",
        "domain": "tier1a",
        "subdomain": "tax_disputes",
        "question_sw": "Bodi ya Rufaa za Mapato ya Kodi (Tax Revenue Appeals Board — TRAB) inahusika vipi kwenye mgawanyiko wa kodi?",
        "answer_sw": "TRAB ndiyo hatua ya pili ya rufaa baada ya hoja ya pingamizi kutofanikiwa kwa Kamishna. Ikiwa Kamishna wa TRA ametoa uamuzi dhidi yako, unaweza kupiga rufaa kwa TRAB ndani ya siku 30 baada ya kupokea uamuzi wa Kamishna. TRAB ni mahakama ya pekee ya kodi yenye wajumbe wa mwanasheria, mtaalamu wa kodi, na mfanyabiashara. TRAB inasikia mashauri, inachunguza ushahidi, na inatoa uamuzi. Ikiwa bado hujaridhika na uamuzi wa TRAB, unaweza kwenda Mahakama ya Rufaa ya Mapato ya Kodi (Tax Revenue Appeals Tribunal).",
        "answer_en": "TRAB is the second stage of appeals after an objection to the Commissioner is unsuccessful. If the TRA Commissioner has ruled against you, you may appeal to TRAB within 30 days of receiving the Commissioner's decision. TRAB is a specialised tax court comprising a legal member, a tax expert, and a business representative. TRAB hears submissions, examines evidence, and issues a ruling. If still unsatisfied with TRAB's decision, you may proceed to the Tax Revenue Appeals Tribunal.",
        "question_en": "How does the Tax Revenue Appeals Board (TRAB) fit into a tax dispute?",
        "primary_source_url": "https://www.tra.go.tz",
        "primary_source_name": "TRA — Tax Revenue Appeals Board (TRAB)",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "Tax Revenue Appeals Act amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_tax_disp_004_20260603",
        "domain": "tier1a",
        "subdomain": "tax_disputes",
        "question_sw": "Wakati wa ukaguzi wa TRA, mlipa kodi ana haki gani anayopaswa kujua?",
        "answer_sw": "Wakati wa ukaguzi wa TRA, mlipa kodi ana haki zifuatazo: haki ya kupewa taarifa ya mapema ya ukaguzi (advance notice) isipokuwa ukaguzi wa ghafla ulioidhinishwa kisheria, haki ya kuomba nakala ya amri ya ukaguzi, haki ya kuwasiliana na mshauri wa kodi au wakili wakati wote wa ukaguzi, haki ya kujibu maswali kwa maandishi badala ya kwa mdomo, haki ya kupinga matokeo ya ukaguzi kabla ya tathmini ya mwisho, na haki ya kupata nakala ya ripoti ya ukaguzi. Msaada wa mshauri wa kodi uliosajiliwa unasaidia kulinda haki hizi.",
        "answer_en": "During a TRA audit, the taxpayer has the following rights: the right to receive advance notice of the audit (except for a court-authorised surprise audit), the right to request a copy of the audit order, the right to consult a tax adviser or lawyer at all times during the audit, the right to respond to questions in writing rather than verbally, the right to challenge audit findings before a final assessment is issued, and the right to receive a copy of the audit report. Support from a registered tax consultant helps protect these rights.",
        "question_en": "During a TRA audit, what rights does the taxpayer have that they should know?",
        "primary_source_url": "https://www.tra.go.tz",
        "primary_source_name": "TRA — taxpayer rights during audit",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "Taxpayers' Rights Charter revision",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_tax_disp_005_20260603",
        "domain": "tier1a",
        "subdomain": "tax_disputes",
        "question_sw": "Utaratibu wa ufafanuzi wa hiari (voluntary disclosure) wa TRA unanifahamisha nini na ninapata faida gani?",
        "answer_sw": "Utaratibu wa ufafanuzi wa hiari unaruhusu mlipa kodi kutangaza makosa ya kodi bila kusubiri ukaguzi wa TRA. Faida za ufafanuzi wa hiari ni: kupunguza adhabu (mara nyingi kwa asilimia 50 au zaidi) kulingana na jinsi unavyoshirikiana na TRA, kupunguza uwezekano wa mashtaka ya jinai kwa ukwepaji makusudi wa kodi, na kuonyesha nia njema ya kutii sheria. Unahitaji: kuwasilisha taarifa kamili ya mapato/hasara iliyokosekana, kulipa kodi kamili inayostahili, na kuomba rasmi kupitia TRA. Toa taarifa kabla ya TRA kukujua — ikiwa TRA wameshaanza kukuchunguza, hakuna faida za ufafanuzi wa hiari.",
        "answer_en": "The voluntary disclosure procedure allows a taxpayer to declare tax errors without waiting for a TRA audit. Benefits of voluntary disclosure include: reduced penalties (often by 50% or more) depending on the degree of cooperation with TRA, reduced risk of criminal prosecution for deliberate tax evasion, and demonstrating good faith compliance. You need to: submit a complete statement of missing income/tax, pay the full tax owed, and apply formally through TRA. Disclose before TRA discovers you — if TRA has already started investigating you, voluntary disclosure benefits no longer apply.",
        "question_en": "What does TRA's voluntary disclosure procedure offer and what benefits do I receive?",
        "primary_source_url": "https://www.tra.go.tz",
        "primary_source_name": "TRA — voluntary disclosure procedure",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "Tax Revenue Acts amendment",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_tax_disp_006_20260603",
        "domain": "tier1a",
        "subdomain": "tax_disputes",
        "question_sw": "Kodi ya TRA inayodaiwa ni kubwa sana kulipa mara moja. Je, TRA inakubali malipo kwa awamu (instalment plan)?",
        "answer_sw": "Ndiyo. TRA inaweza kukubaliana na mpango wa malipo kwa awamu kwa mlipa kodi anayeonyesha nia njema ya kulipa lakini ana ugumu wa kifedha wa kulipa kwa mara moja. Ili kupata mpango wa malipo: wasiliana na ofisi ya TRA haraka iwezekanavyo (kabla ya hatua za utekelezaji), wasilisha ombi rasmi la maandishi ukieleza hali yako ya kifedha, toa mpango wa malipo uliopendekezwa ukionyesha kiasi na muda wa kila awamu, na TRA itafanya tathmini. Riba itaendelea kutumika wakati wa mpango wa malipo. Kukimbia au kutojitokeza mbele ya TRA kunasababisha hatua kali zaidi.",
        "answer_en": "Yes. TRA may agree to an instalment payment plan for a taxpayer who demonstrates genuine intent to pay but has financial difficulty paying all at once. To obtain a payment plan: contact the TRA office as soon as possible (before enforcement steps begin), submit a formal written application explaining your financial situation, provide a proposed payment schedule showing the amount and timing of each instalment, and TRA will make an assessment. Interest will continue to apply during the payment plan period. Avoiding or not appearing before TRA leads to harsher enforcement action.",
        "question_en": "The TRA tax owed is too large to pay all at once. Will TRA accept payment by instalments?",
        "primary_source_url": "https://www.tra.go.tz",
        "primary_source_name": "TRA — instalment payment plan",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "stable",
        "next_review_trigger": "TRA enforcement policy change",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
    {
        "id": "tier1a_tax_disp_007_20260603",
        "domain": "tier1a",
        "subdomain": "tax_disputes",
        "question_sw": "TRA ina muda gani wa kisheria wa kutoa tathmini ya kodi baada ya mwaka wa kodi kupita?",
        "answer_sw": "Chini ya Sheria ya Kodi ya Mapato na sheria za kodi nyingine Tanzania, TRA kwa ujumla ina miaka 5 kuanzia tarehe ya mwisho ya kuwasilisha return ya kodi kuwasilisha tathmini dhidi ya mlipa kodi ambaye aliwasilisha return. Kwa mlipa kodi ambaye hakuwasilisha return kabisa, TRA inaweza kutoa tathmini wakati wowote — hakuna kikomo cha muda. Kwa udanganyifu au ukwepaji wa makusudi, muda huo unaweza kuwa mrefu zaidi. Hifadhi rekodi zako za uhasibu kwa angalau miaka 5 ili kujibu tathmini yoyote ndani ya muda huo.",
        "answer_en": "Under the Income Tax Act and other Tanzanian tax laws, TRA generally has 5 years from the date of the final deadline for filing a tax return to issue an assessment against a taxpayer who filed a return. For a taxpayer who did not file a return at all, TRA may issue an assessment at any time — there is no time limit. For fraud or deliberate evasion, the period may be longer. Keep your accounting records for at least 5 years to be able to respond to any assessment within this period.",
        "question_en": "What is the statutory time limit for TRA to issue a tax assessment after the tax year has passed?",
        "primary_source_url": "https://www.tra.go.tz",
        "primary_source_name": "TRA — limitation period for tax assessments",
        "source_type": "government_portal",
        "effective_date": "2025-07-01",
        "decay_risk": "annual",
        "next_review_trigger": "Finance Act amendment to limitation period",
        "verified_by": "pending_founder_review",
        "verified_date": "pending_founder_review",
        "register": "business_market",
        "pair_type": "standard",
        "eval_set": False
    },
]

# Load existing questions for dedup check
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
dedup_path = os.path.join(ROOT, "datasets", "tier1a", "raw_sources", "existing_questions.txt")
existing_questions = set()
if os.path.exists(dedup_path):
    with open(dedup_path, encoding="utf-8") as f:
        existing_questions = {line.strip().lower() for line in f if line.strip()}

# Dedup filter
filtered = []
skipped = 0
for pair in BATCH_D:
    q_sw = pair["question_sw"].lower().strip()
    q_en = pair["question_en"].lower().strip()
    if q_sw in existing_questions or q_en in existing_questions:
        print(f"  SKIP (duplicate): {pair['id']}")
        skipped += 1
    else:
        filtered.append(pair)
        existing_questions.add(q_sw)
        existing_questions.add(q_en)

print(f"Batch D: {len(filtered)} new pairs, {skipped} skipped as duplicates")

# Append to batch_002
batch_path = os.path.join(ROOT, "datasets", "tier1a", "raw_sources", "raw_pairs_batch_002.jsonl")
existing_pairs = []
with open(batch_path, encoding="utf-8") as f:
    for line in f:
        existing_pairs.append(json.loads(line))

all_pairs = existing_pairs + filtered
with open(batch_path, "w", encoding="utf-8") as out:
    for p in all_pairs:
        out.write(json.dumps(p, ensure_ascii=False) + "\n")

print(f"batch_002 now has {len(all_pairs)} pairs")

# Update existing_questions.txt
with open(dedup_path, "w", encoding="utf-8") as out:
    for q in sorted(existing_questions):
        out.write(q + "\n")
print(f"existing_questions.txt updated: {len(existing_questions)} questions")
